build.gradle, src/examples/java/ChannelListenerExample.java, src/examples/java/ExampleUtils.java, src/examples/java/GuildListenerExample.java, src/examples/java/MessageListenerExample.java, src/main/java/net/dv8tion/jda/JDA.java, src/main/java/net/dv8tion/jda/JDABuilder.java, src/main/java/net/dv8tion/jda/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/handle/EntityBuilder.java, src/main/java/net/dv8tion/jda/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/VoiceChangeHandler.java, src/main/java/net/dv8tion/jda/requests/Requester.java, src/main/java/net/dv8tion/jda/requests/WebSocketClient.java
Release of v1.0.2
Added proxy support
Moved the getConfig method in the example classes to an ExampleUtil class.
Some NPE fixes for weird Discord api returns.
=> Release of v1.0.2.

README.md, build.gradle, src/examples/java/ChannelListenerExample.java, src/examples/java/ExampleUtils.java, src/examples/java/GuildListenerExample.java, src/examples/java/MessageListenerExample.java, src/main/java/net/dv8tion/jda/JDA.java, src/main/java/net/dv8tion/jda/JDABuilder.java, src/main/java/net/dv8tion/jda/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/handle/EntityBuilder.java, src/main/java/net/dv8tion/jda/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/VoiceChangeHandler.java, src/main/java/net/dv8tion/jda/requests/Requester.java, src/main/java/net/dv8tion/jda/requests/WebSocketClient.java
This actually apipears as a rerelease of v1.0.2 due to stupidity on my part of not bumping version and destroy git history.
Added proxy support
Moved the getConfig method in the example classes to an ExampleUtil class.
Some NPE fixes for weird Discord api returns.
=> Re-Release of v1.0.2

src/main/java/net/dv8tion/jda/entities/impl/AccountManagerImpl.java
null avatars would throw a JSONException without this fix
=> Small fix to suppot accounts without avatars

src/main/java/net/dv8tion/jda/entities/Guild.java, src/main/java/net/dv8tion/jda/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/utils/InviteUtil.java
This was created by Almighty, I'm just doing the PR because I'm impatient.
=> Added Guild#getInvites(). 

build.gradle
=> groovify build.gradle

README.md
=> Added a bot auth example to the readme.

src/main/java/net/dv8tion/jda/entities/Game.java, src/main/java/net/dv8tion/jda/entities/User.java, src/main/java/net/dv8tion/jda/entities/impl/GameImpl.java, src/main/java/net/dv8tion/jda/entities/impl/UserImpl.java, src/main/java/net/dv8tion/jda/handle/EntityBuilder.java, src/main/java/net/dv8tion/jda/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/ReadyHandler.java, src/main/java/net/dv8tion/jda/managers/AccountManager.java
Added ability to detect Twitch streams in User#getCurrentGame()
Added ability to set Twitch stream in AccountManager#setStreaming(Game, Url)
Added Game and GameImpl to handle future game types
=> Adding support for setting and receiving streaming status.

src/main/java/net/dv8tion/jda/entities/User.java, src/main/java/net/dv8tion/jda/entities/impl/UserImpl.java
Discord has default avatars for users (used when they either have not set an avatar, or have removed their avatar)
=> Add default avatar

src/main/java/net/dv8tion/jda/entities/Guild.java, src/main/java/net/dv8tion/jda/entities/impl/GuildImpl.java
I'd be tickled pink if you gave this the green light.
=> Add getColorDeterminantRoleForUser

src/main/java/net/dv8tion/jda/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/audio/AudioReceiveHandler.java, src/main/java/net/dv8tion/jda/audio/AudioSendHandler.java, src/main/java/net/dv8tion/jda/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/audio/CombinedAudio.java, src/main/java/net/dv8tion/jda/audio/Decoder.java, src/main/java/net/dv8tion/jda/audio/UserAudio.java, src/main/java/net/dv8tion/jda/managers/impl/AudioManagerImpl.java
Added receiving audio!!!!!
Includes ability to receive combined (all users at once) and specific user audio.
=> Audio receiving

src/main/java/net/dv8tion/jda/entities/Channel.java, src/main/java/net/dv8tion/jda/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/entities/impl/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/utils/PermissionUtil.java
Also made old methods deprecated (together with a little note)
=> Created new checkPermission methods using varargs

src/main/java/net/dv8tion/jda/entities/Guild.java, src/main/java/net/dv8tion/jda/entities/impl/GuildImpl.java
Added Guild#getUserById, Guild#getUsersByName, Guild#getRolesByName, and Guild#getEffectiveNameForUser
=> Added convenience methods in Guild

src/main/java/net/dv8tion/jda/utils/ApplicationUtil.java
Avoiding potential ban reason.
=> Switched login for ApplicationUtil to token instead of email/pass.

src/main/java/net/dv8tion/jda/entities/Emote.java, src/main/java/net/dv8tion/jda/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/handle/EntityBuilder.java, src/main/java/net/dv8tion/jda/handle/GuildEmojisUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/GuildLeaveHandler.java
now remove emotes from guild maps properly.
=> Switched guild collection in EmoteImpl to Set

src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberBanEvent.java, src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberLeaveEvent.java, src/main/java/net/dv8tion/jda/handle/GuildMemberBanHandler.java, src/main/java/net/dv8tion/jda/handle/GuildMemberRemoveHandler.java
Compiled for `clean wrapper javadocJar fatJar` with no errors and was tested on my own bot.
=> Added oldRoles field to both GuildMemberLeave- and BanEvent

src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberBanEvent.java, src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberLeaveEvent.java, src/main/java/net/dv8tion/jda/handle/GuildMemberBanHandler.java, src/main/java/net/dv8tion/jda/handle/GuildMemberRemoveHandler.java
Now cleaning nickname map on member removal as well.
=> Added oldNick field to both GuildMemberLeave- and BanEvent. 

src/main/java/net/dv8tion/jda/entities/impl/GameImpl.java
.equals() now correctly checks each element
.hashCode() generates hash based on game, url, and type
git diff why you being so weird
=> fixed .equals and added .hashCode() in GameImpl

src/main/java/net/dv8tion/jda/entities/Channel.java, src/main/java/net/dv8tion/jda/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/entities/impl/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/utils/PermissionUtil.java
Also made Channel#checkPermission(User, Permission...) default.
=> Giving ability to check Permissions for Role in a Channel.

README.md
Suggestions/Feedback appreciated.
=> Updated README.md for 3.x

src/main/java/net/dv8tion/jda/Permission.java
=> Added MANAGE_EMOTES permission

src/main/java/net/dv8tion/jda/JDABuilder.java
(PR #136 with DV8 suggestions)
=> Add and Remove Listeners accepting Multiple

src/main/java/net/dv8tion/jda/hooks/AnnotatedEventManager.java
1. Now supports an Class as input, So only Static Methods are used
2. Now accepts multiple methods of the same Event (2 ReadyEvents, as Example)
(Test: http://hastebin.com/iyalepurub.java )
=> AnnotatedEventManager revamp

src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java
Also added a special check in case the mentioned user is not in the same guild
=> Fixing mistake in Message#getContent

src/main/java/net/dv8tion/jda/core/Permission.java
=> Adding missing permissions

src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
Fixes the is not snowflake error when using the method deleteMessages(Collection<Message> messages).
=> Fix snowflake error for method deleteMessages

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/Region.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/hooks/AnnotatedEventManager.java, src/main/java/net/dv8tion/jda/core/hooks/EventListener.java
Just updating the changes to JDA 3.
(Quick note: The `src/main/java/net/dv8tion/jda/core/hooks/EventListener.java` change wasn't made directly made by me but rather by the IntelliJ)
=> Fixed Discord Regions, AnnotatedEventManager and multiple Listeners

src/main/java/net/dv8tion/jda/core/entities/Icon.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java
I also cleaned up the mistakes caused by the Icon addition in createEmote and cleaned up the GuildController class.
=> Icon documentation

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/MessageBuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageEmbedImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
MessageBuilder has a settable embed field
EmbedBuilder can take an embed as a parameter
PrivateChannelImpl and TextChannelImpl will send the embed if it exists
=> MessageEmbed now has toJSONObject instead of toJSONString

src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
I added a direct way to convert a message to a JSONObject for internal use.
This is used in MessageChannel#sendMessage(Message) and Message#editMessage(Message).
In addition, I added Args.notNull checks to ensure a working method.
=> Added MessageImpl#toJSONObject

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java
IllegalStateException -> IllegalArgumentException
Much more lenient URL regex
=> EmbedBuilder patch

src/main/java/net/dv8tion/jda/core/Permission.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/MessageReactionAddEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/MessageReactionRemoveAllEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/MessageReactionRemoveEvent.java, src/main/java/net/dv8tion/jda/core/handle/MessageReactionBulkRemoveHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
=> 🎊 Reactions 🎊

src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java
=> Added MessageChannel#editMessageById

src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
fixed Date header
perform less math for more accurate values
=> header and time calculation changes

src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java
This should fix issues with concurrent calls to the modified methods.
=> Made a few methods in MessageImpl synchronized

src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
Ref. #191 
Note: I also updated the log message for errors in updateBucket
=> Adding missing ErrorResponse constants

src/main/java/net/dv8tion/jda/core/MessageBuilder.java
=> MessageBuilder update, comments welcome

src/main/java/net/dv8tion/jda/core/entities/User.java, src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java, src/main/java/net/dv8tion/jda/core/utils/WidgetUtil.java
first pass on WidgetUtil
added getEffectiveAvatarUrl to User and UserImpl
=> Widget Util

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
no more https check
can add a MessageEmbed.Field object
added isEmpty() method
removed unused imports
fixed deprecated messagebuilder method usage
added permission check for embed + empty message
made lock final because my IDE kept yelling at me
=> EmbedBuilder bugfixes, changes, and permission check

src/main/java/net/dv8tion/jda/JDABuilder.java, src/main/java/net/dv8tion/jda/entities/impl/JDAImpl.java
This should fix the 401 errors after updating account settings.
As this breaks the build entirely I consider this one worth merging, even for a deprecated version.
=> Fixed an error in AccountManager#update

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/Webhook.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/WebhookImpl.java, src/main/java/net/dv8tion/jda/core/managers/AccountManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/managers/GuildManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/WebhookManager.java, src/main/java/net/dv8tion/jda/core/managers/WebhookManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/fields/WebhookField.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/impl/WebhookAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/WebhookAction.java
This implementation adds functionality for:
- Creating a Webhook
- Modifying a Webhook
- Deleting a Webhook
- Getting Webhooks for a Channel
This implementation does not add functionality for:
- POSTing to a Webhook
=> Webhook pass

src/examples/java/MessageListenerExample.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/Requester.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/CompletedFuture.java, src/main/java/net/dv8tion/jda/core/requests/restaction/RequestFuture.java, src/main/java/net/dv8tion/jda/core/requests/restaction/WebhookAction.java
Added new methods:
- complete()
- complete(boolean shouldQueue)
- submit()
- submit(boolean shouldQUeue)
Made block(...) deprecated.
Added ability to cancel requests after they were queued.
=> Improved RestAction functionality

src/examples/java/MessageListenerExample.java
- Fixed a small typo on JDA example
=> Fix small typo

src/main/java/net/dv8tion/jda/core/Permission.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/RoleAction.java
Added `RoleAction` and `ChannelAction` to create either a Role or Channel with preset settings.
This is not yet finished and needs proper documentation which I will add once the role creation changes are rolled out.
~~When creating a channel via `ChannelAction`the permissions of the provided PermissionOverrides are not applied (possible discord bug?). This needs to be investigated before merging.~~ Checked.
=> Added new RestAction extensions

src/main/java/net/dv8tion/jda/core/requests/RestAction.java
allow to override the default success/failure consumers
=> RestAction default behavior

src/main/java/net/dv8tion/jda/core/JDABuilder.java
=> Another Typo

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
I'm not pushing this directly to development because I need @DV8FromTheWorld to verify this.
=> Fixed PermissionOverride cache bug

src/main/java/net/dv8tion/jda/core/entities/Channel.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java
Idk why we don't have this already but here it is 🌱
=> Added PermissionOverrideAction

README.md
Moved to DV8FromTheWorld:development
=> Re-opened: Fixed `Event Methods` link in README.md

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/requests/RateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/IBucket.java
and implemented it for reaction adding, see [#182](https://github.com/hammerandchisel/discord-api-docs/issues/182)
=> Added a way to hardcode custom rate limits

src/main/java/net/dv8tion/jda/core/Permission.java
Remake of the last pr, hopefully I didn't screw this one up
=> Readable permission names

src/main/java/net/dv8tion/jda/bot/JDABot.java, src/main/java/net/dv8tion/jda/bot/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/bot/entities/impl/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/bot/entities/impl/JDABotImpl.java, src/main/java/net/dv8tion/jda/client/JDAClient.java, src/main/java/net/dv8tion/jda/client/entities/Application.java, src/main/java/net/dv8tion/jda/client/entities/AuthorizedApplication.java, src/main/java/net/dv8tion/jda/client/entities/impl/ApplicationImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/AuthorizedApplicationImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/JDAClientImpl.java, src/main/java/net/dv8tion/jda/client/managers/ApplicationManager.java, src/main/java/net/dv8tion/jda/client/managers/ApplicationManagerUpdatable.java, src/main/java/net/dv8tion/jda/client/managers/fields/ApplicationField.java, src/main/java/net/dv8tion/jda/client/requests/restaction/ApplicationAction.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/managers/AccountManager.java, src/main/java/net/dv8tion/jda/core/managers/AccountManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/GuildManager.java, src/main/java/net/dv8tion/jda/core/managers/GuildManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/PermOverrideManager.java, src/main/java/net/dv8tion/jda/core/managers/RoleManager.java, src/main/java/net/dv8tion/jda/core/managers/RoleManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/WebhookManager.java, src/main/java/net/dv8tion/jda/core/managers/WebhookManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/requests/Route.java
Hope I didn't forget ~~anything~~ too much :pray:
=> Applications! Bot invites!

README.md
While reading the readme file I found this small mistake, which is not good for a high level API like JDA so I thought we should fix this up.
=> Fixed a minor mistake in readme file.

README.md, src/main/java/net/dv8tion/jda/client/entities/RelationshipType.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Cleaned up README
Removed deprecated methods
Fixed issue related to Members in a Guild on GuildLeaveEvent.
=> Ready development for 3.0 release

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
This will store the time it takes for discord to ack our heartbeat in milliseconds.
=> Added JDA#getPing

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java
This seems like a logical addition to the library as many messages are from Guilds, and reducing ceremony would be desirable.
=> Add getMember() to Message.

src/main/java/net/dv8tion/jda/client/requests/restaction/pagination/MentionPaginationAction.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/ReactionPaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/package-info.java
Note: The specified channel need not be in the same guild as this is not from interest for copying its values
=> Added GuildController#createCopyOfChannel

src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/managers/Presence.java, src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/core/requests/Request.java
New approach for unknown/server error handling.
=> Added handling for unknown error responses

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/VoiceServerUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
This will ensure that the mWs reading thread will no longer be blocked by connecting audio websockets.
This will fix several NPEs for openAudioConnection and closeAudioConnection
=> Fixes concerning opening AudioWebSocket connections

src/main/java/net/dv8tion/jda/client/managers/EmoteManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/Permission.java, src/main/java/net/dv8tion/jda/core/entities/Channel.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/IPermissionHolder.java, src/main/java/net/dv8tion/jda/core/entities/PermissionOverride.java, src/main/java/net/dv8tion/jda/core/entities/Role.java, src/main/java/net/dv8tion/jda/core/entities/impl/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/core/events/emote/package-info.java, src/main/java/net/dv8tion/jda/core/events/emote/update/package-info.java, src/main/java/net/dv8tion/jda/core/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/AudioManager.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/managers/GuildManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/fields/PermissionField.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Changed some structure and design for the PermissionOverrideImpl internals
=> Cleanup for PermissionUtil and fixed user_limit check.

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
added EmbedBuilder#getFields for an editable list of embed fields
modified related methods to not disturb EntityBuilder while still providing checks
=> PR for editing fields in an EmbedBuilder

src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java
see https://github.com/hammerandchisel/discord-api-docs/pull/267
=> Added 50021 error response

src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java
=> Added a check for dms between 2 bots

src/main/java/net/dv8tion/jda/core/MessageBuilder.java
Useful for creating a lot of messages in a loop without having to make a new instance of this builder.
(Pls accept me)
=> Added clear method

src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
This should resolve #360 and #357 
I have asked @Frederikam to test these changes in production.
=> Fixed race condition in audio sending causing audio to speed up

src/main/java/net/dv8tion/jda/bot/JDABot.java, src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/bot/sharding/ShardManagerBuilder.java
Finishes and fixes existing JavaDoc for ShardManager and related classes.
=> ShardManager JavaDoc

src/main/java/net/dv8tion/jda/core/WebSocketCode.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/handle/ReadyHandler.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/managers/impl/PresenceImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
I hate having to look these up...
=> Added WebSocketCode class containing op code constants

src/main/java/net/dv8tion/jda/core/entities/Invite.java
This needs to wait for #400 due to possible conflicts.
=> Added Invite#getURL()

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
On close code 1000 our session has been dropped, we will never be able to resume on it.
=> Invalidate session on close code 1000

src/main/java/net/dv8tion/jda/core/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/events/channel/text/update/TextChannelUpdateNSFWEvent.java, src/main/java/net/dv8tion/jda/core/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
=> Implemented NSFW flag

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
This should now backoff properly for invalidate by closing the websocket
With that it also properly handles IDENTIFY rate limits that would otherwise cause tons of OP 9 responses
Compare to updated official discord documentation on OP 9
=> Improve invalidate handling

build.gradle, src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildMemberUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/utils/Checks.java, src/main/java/net/dv8tion/jda/core/utils/Helpers.java, src/main/java/net/dv8tion/jda/core/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/core/utils/SimpleLog.java, src/main/java/net/dv8tion/jda/core/utils/tuple/ImmutablePair.java, src/main/java/net/dv8tion/jda/core/utils/tuple/MutablePair.java, src/main/java/net/dv8tion/jda/core/utils/tuple/Pair.java, src/main/java/net/dv8tion/jda/core/utils/tuple/package-info.java
This should sort lots of compatibility issues with frameworks such as bukkit or spigot.
I'm open for suggestions to name the `Helpers` class.
=> Remove lang3 dependency

src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
Added a Javadoc for the static REMOVE object.
Removed redudant modifiers.
Let me know if any changes are to be made or you can make them yourself I enabled allowing edits from maintainers.
=> Improvements to patch-embed-removal

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/Member.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java
See hammerandchisel/discord-api-docs#329
=> Implemented default channel changes

.gitignore, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/audio/ConnectionRequest.java, src/main/java/net/dv8tion/jda/core/audio/ConnectionStage.java, src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/VoiceServerUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/VoiceStateUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Now all requests will work in the same system
- Connecting to a VoiceChannel
- Re-connecting to a VoiceChannel
- Disconnecting from a VoiceChannel
This should counter some unwanted race-conditions with the old system.
=> Changed audio connection requests

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
The old code used a `StringBuilder` with the default capacity and made a new String for each 128 byte chunk.
=> Rewrite decompression to use less allocations and regrows

src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java
Was missing previously so wasn't able to be overridden via ListenerAdapter subclasses
=> + TextChannelUpdateParentEvent to ListenerAdapter

build.gradle, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/handle/EventCache.java, src/main/java/net/dv8tion/jda/core/hooks/AnnotatedEventManager.java, src/main/java/net/dv8tion/jda/core/hooks/InterfacedEventManager.java, src/main/java/net/dv8tion/jda/core/managers/AudioManager.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/GuildLock.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/Requester.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java, src/main/java/net/dv8tion/jda/core/utils/SimpleLog.java, src/main/java/net/dv8tion/jda/webhook/WebhookClient.java
This change will bump the version to 3.3.1
=> Switched to SLF4J for logging

src/main/java/net/dv8tion/jda/core/managers/impl/PresenceImpl.java
Make sure the setPresence call has the right parameters so that it does update correctly :)
=> Fix the presence change

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
I created the Issues and Pull Request templates as mentioned in #486 for Hacktoberfest. Looking for feedback.
=> Added Issues and Pull Request templates

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/events/guild/update/GuildUpdateRegionEvent.java, src/main/java/net/dv8tion/jda/core/handle/GuildUpdateHandler.java
This can be useful to debug which regions are not currently supported by JDA.
=> Updated regions to use raw strings in Guild

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Related:
https://github.com/discordapp/discord-api-docs/pull/408
=> Add zlib compression support

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
The field "self" actually is called "me"
https://discordapp.com/developers/docs/resources/channel#reaction-object
=> Correct reactions parsing

src/main/java/net/dv8tion/jda/client/events/message/group/react/GenericGroupMessageReactionEvent.java, src/main/java/net/dv8tion/jda/client/requests/restaction/pagination/MentionPaginationAction.java, src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/events/message/guild/react/GenericGuildMessageReactionEvent.java, src/main/java/net/dv8tion/jda/core/events/message/priv/react/GenericPrivateMessageReactionEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/MessagePaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/ReactionPaginationAction.java
This adds documentation explaining how to send images and referencing them from a `MessageEmbed`.
Additionally this adds more examples to `PaginationAction` and renames an old naming convention that is rather confusing.
=> General cleanup of documentation and naming conventions

src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/entities/Game.java, src/main/java/net/dv8tion/jda/core/managers/Presence.java, src/main/java/net/dv8tion/jda/core/utils/WidgetUtil.java
This adds the new game types allowing to show up as `Listening...` and `Watching...`
=> Added new game types

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/events/guild/update/GuildUpdateFeaturesEvent.java, src/main/java/net/dv8tion/jda/core/handle/GuildUpdateHandler.java, src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/managers/GuildManager.java, src/main/java/net/dv8tion/jda/core/managers/GuildManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
This PR adds the method `Guild#getFeatures()` that returns `List<Strings>` describing a Guild's features as given by Discord.
**Possible (currently known) features are:**
- VIP_REGIONS
- VANITY_URL
- INVITE_SPLASH
- VERIFIED
- MORE_EMOJI
Edit:
=> Added ability to get a Guild's features (vip voice, verified, ...)

src/main/java/net/dv8tion/jda/core/events/http/HttpRequestEvent.java
Response#rawResponse is a nullable field and some methods in the HttpRequestEvent don't treat it like it is (though some do, like HttpRequestEvent#getResponseHeaders). This adds the missing checks.
=> Add missing null checks in HttpRequestEvent

src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
This fixes a small logic error when denied ADMINISTRATOR permission would cause invalid permission checks and also improves some logic efficiency.
=> Improve some logic in PermissionUtil

build.gradle, src/main/java/net/dv8tion/jda/core/entities/Category.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/RichPresence.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManagerUpdatable.java, src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/GuildAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/webhook/package-info.java
This updates what is needed to release 3.4.0
=> Added some since tags, bumped version, removed old deprecated methods

src/main/java/net/dv8tion/jda/core/entities/Emote.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java, src/main/java/net/dv8tion/jda/core/handle/GuildEmojisUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
This PR adds a `Emote#isAnimated` member to check whether or not the `Emote` is an animated custom emoji or not, as well as proper handling for the new property.
=> First pass on animated emote support

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
This adds `Guild#getBanList` and allows to see reasons
=> Support for viewing ban reasons

src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildRoleDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/PresenceUpdateHandler.java
This removes all caching of delete events to prevent unwanted behaviour.
Additionally, since nitro now allows to change your discriminator, I've added handling for discriminator updates.
=> Removed caching of delete events

src/main/java/net/dv8tion/jda/core/requests/RequestFuture.java
This allows to use more of the hidden functionality that is only available for the CompletableFuture implementation.
Additionally you can now do:
```java
List<RequestFuture<?>> all = new ArrayList<>();
for (int i = 0; i< 10; i++) 
all.add(channel.sendMessage("test " + i).submit());
RequestFuture.allOf(all).thenRun(() -> System.out.println("Done!"));
```
=> Improved RequestFuture interface

src/main/java/net/dv8tion/jda/core/requests/Response.java
Makes the parsing of HTTP responses lazy. This can improve both performance and the memory footprint of HTTP requests.
We don't always need the response of an HTTP request, thus we also can avoid parsing it on every request.
=> Lazy evaluation of HTTP responses

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java, src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
Fixes message mention parsing to only return actually mentioned Users/Members/Roles via `getMentionedX()` methods instead of all entities that are found via regex matcher.
This removes strings resembling mentions but not actually being mentions (for example ones in code blocks or non-mentionable roles) from being treated as actually mentioning.
=> Fixed Message#getMentionedX() methods returning non-mentioned entities

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/utils/SessionControllerAdapter.java
=> Fixed a few issues with session startup and close

src/main/java/net/dv8tion/jda/core/Region.java
Adding Japan region to the enum.
=> Add Japan region

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/requests/Route.java
This can be used to see the regions for a specific guild.
=> Added Guild#retrieveRegions

src/main/java/net/dv8tion/jda/core/events/message/GenericMessageEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageBulkDeleteEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageDeleteEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageEmbedEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageReceivedEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageUpdateEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/core/events/message/react/MessageReactionRemoveAllEvent.java
This is a simple PR, this just adds `getGuild()` to GenericMessageEvent since it is just added in implementations.
=> Restructure GenericMessageEvent

src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
This makes sure we only add users/roles/channels once to the list
=> Make mentions distinct

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Game.java, src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
Now you can also look at spotify details in presences.
Documentation is not very clear because discord hasn't updated their documentation yet.
Example JSON:
```json
{
"assets": {
"large_image":"spotify:8351a630c907a985143102b9466f4d2dab27ae9e",
"large_text":"Lukas Graham"
},
"timestamps": {
"start":1517831446419,
"end":1517831683719
},
"name":"Spotify",
"flags":48,
"session_id":"09529cc3130f34d1530b142d33e08bce",
"details":"7 Years",
"state":"Lukas Graham", …
```
=> Support for parsing more presences

build.gradle, src/main/java/net/dv8tion/jda/bot/utils/cache/impl/ShardCacheViewImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/JDAClientImpl.java, src/main/java/net/dv8tion/jda/core/Permission.java, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/audio/Decoder.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java, src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/handle/MessageBulkDeleteHandler.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/RoleAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/order/OrderAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/core/utils/cache/CacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/AbstractCacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/MemberCacheViewImpl.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/SnowflakeCacheViewImpl.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/SortedSnowflakeCacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/UnifiedCacheViewImpl.java, src/main/java/net/dv8tion/jda/webhook/WebhookClient.java
Small improvements for cache view implementations.
Better iterators, less duplicate code
=> Enhancements for Permissions/CacheView/ErrorResponseException

src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
This allows to use continuations after the iteration completed
=> Return RequestFuture for PaginationAction async iterations

src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/requests/restaction/PermOverrideData.java
With this you can now update multiple permission overrides at once.
=> Added support for bulk updating permission overrides

src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
We now use the same buffer for decompression in order to use less heap and produce less garbage on event handling, additionally I replaced the rate-limit counter with an `AtomicInt`
=> WebSocketClient optimization/enhancements

src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java
Fixes a typo in audit log query params, allowing fetching by user
=> Fixed typo in query param

src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java
This PR adds the functionality to synchronize PermissionOverrides between Channels similar to the synchronization of category -> child which is built into the Discord client.
=> Added possibility to sync Permissions between channels

src/main/java/net/dv8tion/jda/core/entities/ActivityFlag.java, src/main/java/net/dv8tion/jda/core/entities/RichPresence.java
Added an enum for the flags in RichPresence.
=> Added enum to represent the flags set on a RichPresence

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/restaction/MemberAction.java
This will allow bots to add members to guilds, assuming they acquired authentication via OAuth2 `guilds.join` scope.
I have tested this with [implicit grant](https://discordapp.com/developers/docs/topics/oauth2#implicit-grant).
=> Ability to add members to guilds

src/main/java/net/dv8tion/jda/core/requests/RateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
Now if we don't get some headers we still update the bucket with information we do get.
=> Cleaned up BotRateLimiter for better handling of partial/missing headers

src/main/java/net/dv8tion/jda/core/exceptions/ContextException.java, src/main/java/net/dv8tion/jda/core/managers/impl/ManagerBase.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
Now RestAction follows the **PECS** (Producer-extends, Consumer-super)  ideal.
This now allows the following:
```java
Consumer<Object> log = (v) -> System.out.println("Success: " + v);
channel.sendMessage(content).queue(log);
channel.getManager().setTopic(topic).queue(log);
```
=> Add proper boundaries to methods

src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/core/utils/Checks.java, src/main/java/net/dv8tion/jda/core/utils/Helpers.java
Now we consistently check string snowflakes to be numeric.
=> Improve snowflake checks for rest requests

src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java
This pull request fixes small typo in MessageChannel#sendFile exception message ("file is to big" replaced with "file is too big").
=> Fix of typo - MessageChannel.java

README.md
* Fixed the link to the library topic in the Discord Developer Documentation.
=> Fixed link to discord docs on README.md

src/main/java/net/dv8tion/jda/core/events/guild/GuildLeaveEvent.java
`Cane bse used to detect when you leave a Guild.` -> `Can be used to detect when you leave a Guild.`
Closes https://github.com/DV8FromTheWorld/JDA/issues/707
=> Fix Typo in GuildLeaveEvent

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Invite.java, src/main/java/net/dv8tion/jda/core/entities/impl/InviteImpl.java
This PR adds a method to get the features of a guild on an invite.
=> Added Guild Features on Invite

src/main/java/net/dv8tion/jda/core/requests/Requester.java
When the requester gives up on status 500 retries it didn't complete the RestAction callbacks, this change should fix that.
=> Complete rest action on internal server errors

src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
Added getGuildsByName to the ShardManager interface because I was missing the method.
=> Add getGuildsByName to ShardManager

src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
The documentation for `addPermissionOverride` had some major flaws.
=> Improve documentation for ChannelAction

src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java
=> Fix issue with DefaultAudioSendSystem not sending

src/main/java/net/dv8tion/jda/core/Permission.java
=> Add Permission.PRIORITY_SPEAKER

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
Added functionality to retrieve a webhook by id.
Resolves #661.
=> Add support for getting webhooks by id

README.md, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioSendHandler.java, src/main/java/net/dv8tion/jda/core/audio/SpeakingMode.java, src/main/java/net/dv8tion/jda/core/managers/AudioManager.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
Adds support for new speaking modes such as priority speaker
=> Add support for new sending modes

src/main/java/net/dv8tion/jda/core/entities/Category.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
This PR changes the minimum channel name length from 2 to 1.
Fixes #736
=> Change minimum channel name length to 1

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/core/requests/Route.java
I added the ability to request single ban objects. The issue #733 inspired me.
I already tested my changes with valid and invalid ids of banned and not banned users.
=> Support getting ban by user id

src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/utils/cache/UpstreamReference.java
Fixed a few wrong equals() calls comparing wrong types (using the UpstreamReference objects instead of the value they contain).
=> Patch upstream reference

README.md, build.gradle, src/main/java/net/dv8tion/jda/annotations/DeprecatedSince.java, src/main/java/net/dv8tion/jda/annotations/ForRemoval.java, src/main/java/net/dv8tion/jda/annotations/Incubating.java, src/main/java/net/dv8tion/jda/annotations/ReplaceWith.java, src/main/java/net/dv8tion/jda/annotations/Since.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/Decoder.java, src/main/java/net/dv8tion/jda/core/audio/SpeakingMode.java, src/main/java/net/dv8tion/jda/core/entities/Game.java, src/main/java/net/dv8tion/jda/core/entities/RichPresence.java, src/main/java/net/dv8tion/jda/core/managers/AudioManager.java, src/main/java/net/dv8tion/jda/core/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/webhook/WebhookClient.java, src/main/java/net/dv8tion/jda/webhook/WebhookMessage.java, src/main/java/net/dv8tion/jda/webhook/WebhookMessageBuilder.java
The updated README explains my intentions, questions and opinions welcome.
=> Add new annotations for common documentation concerns

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/impl/AbstractMessage.java, src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java
Adds Message#getJumpUrl() for Messages received from Discord. This is the same link that can be copied from the message menu item Copy Link.
=> Add jump-to URL for Messages

src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java
This adds a cause for ErrorResponseException when an exception was added to the response instance by the requester.
=> Add request exceptions to cause of ErrorResponseException

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java
=> Allow titles without TLD

src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java
Fixes a NullPointerException in EmoteImpl#getGuild() for fake emotes.
=> Fix NullPointerException in EmoteImpl#getGuild()

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildSetupNode.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Since you shouldn't be able to somehow put dangling audio managers into cache.
=> Prevent creation of audio managers for uncached guilds

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
I made some of the comments in the templates invisible in the rendered documents and added a few more things.
=> Update github templates

src/main/java/net/dv8tion/jda/core/audit/ThreadLocalReason.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
This allows setting a thread-local audit reason. Useful for repeated use of the same reason (for instance in a moderation bot)
```java
try (var __ = new ThreadLocalReason.Closable("raid cleanup")) {
TextChannel channel = event.getChannel();
channel.getIterableHistory()
.takeAsync(1000)
.thenAccept(channel::purgeMessages);
List<Member> mentions = event.getMessage().getMentionedMembers();
GuildController controller = event.getGuild().getController(); …
```
=> Add ThreadLocalReason

src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
Now shard manager properly returns shardsTotal and properly gets guilds (again).
=> Fix ShardManager#getGuildById

src/main/java/net/dv8tion/jda/core/audio/AudioPacket.java, src/main/java/net/dv8tion/jda/core/audio/Decoder.java
Now we handle CC and fixed the handling for extensions.
Fixes #763
=> Cleanup RTP handling

src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java
The issue:
1: canProvide = false -> packet = null
2: lastFrameSent = System.currentTimeMillis()
--- next iteration ---
3: changeTalking = (System.currentTimeMillis() - System.currentTimeMillis()) > 20; // obviously false here
goto 1
So now the audio connection is stuck speaking while not actually sending anything?
Fixed by only updating lastFrameSent when we send a frame.
=> Only update lastFrameSent when actually sending something

README.md
The phrase `however that is risking account termination.` feels a little strange to read. I took a shot at making it more understandable that selfbotting gets you banned from Discord.
=> Small grammatical change, get to the point

src/main/java/net/dv8tion/jda/core/handle/GuildSetupNode.java
Apparently this event exists and wasn't used.
=> Fire UnavailableGuildJoinedEvent again

src/main/java/net/dv8tion/jda/core/handle/EventCache.java
Closes Issue: #772 
Replace handling of NPEs with checks.
=> Replace ignored NPEs with null checks

src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/GuildSetupController.java
Now the controller will attempt to request chunks again if 10 seconds have passed since the last request. This should eliminate issues with resumes where its unclear if the requests were actually received.
=> Add timeout mechanic for chunk requests

src/main/java/net/dv8tion/jda/core/audio/factory/DefaultSendSystem.java
When idle the thread did not sleep causing CPU spikes, instead
we will check the sentPacket only for changeTalking
=> Fix idle issues for DefaultSendSystem

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
I moved some code to rectify a race-condition on region change.
=> Fix issue with audio region change

src/main/java/net/dv8tion/jda/core/audio/hooks/ConnectionStatus.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
Fixes a race-condition during shutdown.
=> Cleanup shutdown() and fix race-condition

src/main/java/net/dv8tion/jda/core/events/guild/GuildJoinEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageBulkDeleteEvent.java
=> Fixed typo in Javadocs for GuildJoin event

src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java
Added a constructor to `DefaultShardManager` to mirror `JDABuilder(String)`.
=> Add DefaultShardManagerBuilder(String) constructor

src/main/java/net/dv8tion/jda/core/entities/Channel.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
Added the slowmode to the the channel when creating a copy
=> Added copying of the slowmode when cloning a channel

README.md, build.gradle
Closes Issue: #841 
Update OkHTTP to fix issue with incorrect handling of null proxySelector on some JVMs.
=> Update OkHTTP to 3.12.0

src/main/java/net/dv8tion/jda/core/entities/Invite.java
All other methods are called `getUrl`, since this is the only consistency breaker I renamed it.
=> Rename getURL to getUrl

src/main/java/net/dv8tion/jda/api/JDABuilder.java
I think its reasonable to remove these in v4 but keep them in v3.
=> Remove buildAsync and buildBlocking

src/main/java/net/dv8tion/jda/core/entities/User.java, src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java
Created the method User#getAsTag because it makes code look cleaner than using String#format.
=> [Feature] Create User#getAsTag

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageActivity.java, src/main/java/net/dv8tion/jda/core/entities/impl/DataMessage.java, src/main/java/net/dv8tion/jda/core/entities/impl/ReceivedMessage.java, src/main/java/net/dv8tion/jda/core/entities/impl/SystemMessage.java
This Pull Request adds the possibility to access sent MessageActivity of messages.
=> Read-only MessageActivity support.

src/main/java/net/dv8tion/jda/api/managers/AudioManager.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java, src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
This only improves the naming consistency.
=> Rename getter to be consistent with setter

src/main/java/net/dv8tion/jda/api/OnlineStatus.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogEntry.java, src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/api/entities/ChannelType.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/entities/package-info.java, src/main/java/net/dv8tion/jda/api/events/message/MessageReceivedEvent.java, src/main/java/net/dv8tion/jda/api/events/user/UserActivityEndEvent.java, src/main/java/net/dv8tion/jda/api/events/user/UserActivityStartEvent.java, src/main/java/net/dv8tion/jda/api/exceptions/VerificationLevelException.java, src/main/java/net/dv8tion/jda/api/managers/GuildController.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/api/utils/ClosableIterator.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Fix any issues with javadoc and bring back VerificationLevelException, which was removed with the client package but should still be thrown for client accounts.
=> Fix javadoc errors and bring back VerificationLevelException

src/main/java/net/dv8tion/jda/core/Permission.java
Closes Issue: #886 
You can only use this permissions on text channels
=> Add MESSAGE_ADD_REACTION to text only permissions

src/main/java/net/dv8tion/jda/api/Permission.java
Make text/voice only property depend on the bitmask for the specific type.
I also cleaned up the class a tiny bit.
=> Invert dependencies of text/voice only property

src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java, src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
Now we properly implement the equality contract in all entities.
=> Improve equality contracts of JDA entities

src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java
Closes Issue: #893
see title and #893
=> Ignore alpha when comparing colors in MessageEmbed

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Closes Issue: #906 
Message#getContentStripped should now strip spoiler tags
=> Added spoilers to Message#getContentStripped

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Since we no longer have to go through `asBot()` before accessing these methods we have to check it right there.
=> Throw AccountTypeException when attempting to get application of client

src/main/java/net/dv8tion/jda/api/events/Event.java, src/main/java/net/dv8tion/jda/api/events/GenericEvent.java, src/main/java/net/dv8tion/jda/api/events/UpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/GenericUserPresenceEvent.java, src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java, src/main/java/net/dv8tion/jda/api/hooks/EventListener.java, src/main/java/net/dv8tion/jda/api/hooks/IEventManager.java, src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
Improves hierarchy while also allowing to create events that do not extend the abstract `Event` class.
=> Introduce GenericEvent interface for better abstraction

src/main/java/net/dv8tion/jda/api/utils/cache/MemberCacheView.java, src/main/java/net/dv8tion/jda/internal/utils/cache/MemberCacheViewImpl.java
Since member now implements `ISnowflake` we can make `MemberCacheView` do the same.
This should not be a breaking change.
=> Make MemberCacheView extend SnowflakeCacheView

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/audit/package-info.java, src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/Invite.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/managers/GuildController.java, src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
I believe this to be a more intuitive naming conventions.
=> Rename methods used to retrieve entities

build.gradle.kts
Without this the search redirects to a path with `/undefined/` since we don't have a module.
[Stackoverflow Question](https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url)
=> Add flag to fix javadoc

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
Reduces duplicate code and simplifies the API.
```java
public void muteMember(Member m, GuildChannel c) {
PermissionOverride override = c.getPermissionOverride(m);
if (override != null) {
override.getManager().deny(Permission.MESSAGE_WRITE).queue();
}
else {
c.createPermissionOverride(m).deny(Permission.MESSAGE_WRITE).queue();
}
}
```
> With current API
```java
/**
* Mutes the specified member in the target channel by updating the existing override or creating a new one.
*/
public void muteMember(Member m, GuildChannel c) {
c.upsertPermissionOverride(m).deny(Permission.MESSAGE_WRITE).queue();
}
```
> With new API
=> Replace PermOverrideManager with PermissionOverrideAction

src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Blank strings are also invalid values, we should treat them like empty strings.
=> Trim field value and name

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
It doesn't make sense to attempt to read gzip if the content isn't even long enough to fit the header.
=> Check whether content-length is long enough for gzip data

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Adds shorthand to get user by tag.
=> Add getUserByTag

src/main/java/net/dv8tion/jda/core/entities/ChannelType.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/handle/ChannelCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageReactionBulkRemoveHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageUpdateHandler.java
Discord made a breaking change that causes text channels to switch types causing issues for guild creates. For now we should just act like its a text channel.
=> Add news channel type, just handle like text for now

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/test/java/MarkdownTest.java
Closes Issue: #961 
Handle regions like `~~~~` which are invalid.
=> Handle immediately closed regions and properly supply afterIndex

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/MessageActivity.java
This fixes a JSONException which occurs when no cover_image is present on an application.
=> Make cover_image nullable in MessageApplication

src/main/java/net/dv8tion/jda/api/managers/RoleManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/RoleAction.java, src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/RoleActionImpl.java
Role names can be 100 characters long now.
=> Change limit for role names to 100

src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
This was available in the `PermOverrideManager` but was overlooked in the transition.
=> Add PermissionOverrideAction#clear 

src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberNicknameUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateNicknameEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
This PR renames `GuildMemberNickChangeEvent` to `GuildMemberUpdateNicknameEvent` and some related methods. I [discussed this change](https://discordapp.com/channels/125227483518861312/541288051243089920/543471466361126922) in the JDA discord about a two months ago and forgot to create a PR.
=> Rename GuildMemberNickChangeEvent to GuildMemberUpdateNicknameEvent

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java, src/main/java/net/dv8tion/jda/internal/entities/DataMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
This is a backport of a JDA v3 feature.
=> Add message activity/application

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
Adds convenience overload for `EmbedBuilder#setFooter`.
=> Added EmbedBuilder#setFooter for convenience

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
Closes Issue: #986 
Since the previous iteration step already appended the escape
we only need to add the rest of the escapee.
=> Change delta for escaped sequences

src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
Allows slowmode to be set to new maximum slowmode of 6 hours
=> Slowmode update

src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
[Discord API Documentation Update](https://github.com/discordapp/discord-api-docs/pull/918)
=> Update slowmode limit to 6 hours

src/main/java/net/dv8tion/jda/api/events/guild/member/update/GenericGuildMemberUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateNicknameEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
Closes Issue: #973 
This adds a new update event for guild members, and refactors the nickname update event to extend it.
=> Create GuildMemberUpdateEvent hierarchy

src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java
This allows adding/removing listeners in the event loop.
=> Use concurrent collections in AnnotatedEventManager

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/Compression.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java, src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
Discord might add other algorithms to choose from like [zstd](https://github.com/luben/zstd-jni) in the future.
=> Use enum for compression algorithm

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
=> Update embed album links

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Add more diverse issue templates

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/events/DisconnectEvent.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This is now considered an internal field and should thus not be used. See discordapp/discord-api-docs#967
=> Remove usages of _trace

src/main/java/net/dv8tion/jda/api/entities/MessageType.java
These are the new message types for server boosting.
=> Add new message types

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/events/RawGatewayEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/flags/ConfigFlag.java, src/main/java/net/dv8tion/jda/internal/utils/config/flags/ShardingConfigFlag.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
This would allow direct access to gateway dispatch events regardless of JDA handling.
Another use-case is handling events that JDA ignores due to missing cache for e.g. channels.
```java
public class Forwarding extends ListenerAdapter {
private final ThirdParty service;
public Forwarding(ThirdParty service) {
this.service = service;
}
@Override
public void onRawGateway(RawGatewayEvent event) {
service.forward(event);
}
}
```
=> Add RawGatewayEvent

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java
Adds a few common shortcuts for members:
- ban/kick
- mute/deafen
- modifyNickname
```diff
- guild.ban(member, 7).queue();
+ member.ban(7).queue();
```
=> Add shortcuts for common actions on Members

src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
I believe this was an issue when guilds became unavailable after requesting chunks.
=> Restructure handling of unavailable events during setup

build.gradle.kts, src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/entities/Category.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/exceptions/InsufficientPermissionException.java, src/main/java/net/dv8tion/jda/api/hooks/VoiceDispatchInterceptor.java, src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/ClosableIterator.java, src/main/java/net/dv8tion/jda/api/utils/LockIterator.java, src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java, src/main/java/net/dv8tion/jda/api/utils/cache/SnowflakeCacheView.java, src/main/java/net/dv8tion/jda/api/utils/cache/SortedSnowflakeCacheView.java, src/main/java/net/dv8tion/jda/api/utils/concurrent/DelayedCompletableFuture.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/EmptyRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/AuditableRestActionImpl.java
I'm collecting changes to the documentation in this branch that should be done in one update before beta is released. Comment anything that I might have missed and I'll either argument against it or apply suggestions.
=> Javadoc Updates

build.gradle.kts
=> Bump version to 4.BETA.0

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Bags are used to get item cardinality instead of collections with duplicates.
```java
List<Emote> emotes = message.getEmotes();
Bag<Emote> cardinalities = message.getEmotesBag();
for (Emote e : emotes) {
System.out.printf("%s was used %d time(s)%n", e.getName(), cardinalities.getCount(e));
}
```
=> Add bag accessors for mentions

src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/handle/EventCache.java
This map is optimized for enums and can provide a better memory footprint and faster lookup.
=> Use EnumMap where applicable

src/main/java/net/dv8tion/jda/api/entities/Invite.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Somehow this slipped through in the rename.
=> Deprecate ShardManager#setGame

src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
We should just ignore unknown message types when they appear.
=> Ignore unknown message types

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/MessagePaginationAction.java
I have imported a few fixes from v4 that could be useful.
=> Backport bug fixes from v4

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
I never experienced an issue with SNI personally but this method directly sets the SNI parameters on the socket factory. Let's hope it helps.
=> Synchronize WebSocketFactory and use setServerName

src/main/java/net/dv8tion/jda/internal/utils/Helpers.java, src/test/java/HelpersTest.java
I've removed all the unused methods and cleaned up deepEquals to be more readable.
=> Cleanup Helpers utility

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/utils/IOBiConsumer.java, src/main/java/net/dv8tion/jda/internal/requests/FunctionalCallback.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Apparently `canWrite()` returns false when the file doesn't exist. I've added some trace logs to the requester for easier tracking of outgoing requests.
=> Fix check for downloadToFile and add trace logging for requests

src/main/java/net/dv8tion/jda/api/AccountType.java, src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/DisconnectEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildAvailableEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildReadyEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildUnavailableEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateActivityOrderEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java, src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Improvements for documentation.
=> Improve some documentation

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/main/java/net/dv8tion/jda/api/utils/MarkdownUtil.java, src/test/java/MarkdownTest.java, src/test/java/MarkdownUtilTest.java
I've added a utility class to apply formatting and added handling for quote markdown in the sanitizer.
=> Add quote handling and MarkdownUtil

build.gradle.kts
This adds another jar with a minimized classpath and excluded opus as the smallest jar possible for JDA to be usable. The resulting jar is 2 MB smaller than the `no-opus` jar.
=> Add a minimized jar

README.md
The legacy job will be moved to `JDA3-Legacy` on jenkins.
=> Change job references

src/main/java/net/dv8tion/jda/api/Permission.java
Add the new `STREAM` permission. This allows users to use guild streaming (not available to bots).
=> Add VOICE_STREAM permission

README.md
Adds Lavalink (and Lavalink-Client) as recommendations in the readme, as per Minn's request.
=> Add Lavalink to recommendations

src/main/java/net/dv8tion/jda/api/entities/Guild.java
Due to what Joakim said here: https://github.com/DV8FromTheWorld/JDA/pull/1076#discussion_r312695975, I have improved the handling of Guild#getMaxEmotes, I know it's undocumented (At least I haven't found any documentation on it) but I thought I'd make the pr regardless as it follows quite similarly to Guild#getMaxBitrate
=> Improve handling of Guild#getMaxEmotes

src/examples/java/MessageListenerExample.java, src/main/java/net/dv8tion/jda/api/entities/MessageType.java, src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
Corrects some spelling mistakes found in the documentation.
=> Fix JavaDoc typos

README.md
=> Fix onEvent in README

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Clear the store channel cache on invalidate.
=> Fix store channel cache invalidation

build.gradle.kts
Closes Issue: #1120
Promotes the commons-collections4 dependency to API scope to properly provide bags in the message interface.
=> Promote commons-collections4 to an API dependency (#1120)

src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
This pull request adds a field for the maximum slowmode that a text channel can have.
I also added an extra check to the channel action class making it throw if the slowmode was not set on a text channel.
=> Create constant for max slowmode

src/main/java/net/dv8tion/jda/api/Region.java
Adds Europe and India as regions and removes all VIP regions due to discord replacing them with a 384 kbps max bitrate for the server
=> Add India and Europe regions

src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java
We were suggesting to use blocking code here, this has been fixed now. The example seems more common too.
=> Improve documentation for reaction pagination

src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
This adds the method `Member#getActiveClients() : Set<ClientType>` which returns all ClientTypes the Member is not Offline or with Unknown status with
=> Add Member#getActiveClients()

src/main/java/net/dv8tion/jda/api/events/ExceptionEvent.java
Fixes single typo in ExceptionEvent docs
=> Fix single typo

src/main/java/net/dv8tion/jda/api/entities/Webhook.java, src/main/java/net/dv8tion/jda/api/entities/WebhookType.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
General api coverage.
Related PR: discordapp/discord-api-docs#1033
=> Add support for webhook types

src/main/java/net/dv8tion/jda/api/audit/ActionType.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogEntry.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogOption.java, src/main/java/net/dv8tion/jda/api/audit/TargetType.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
This adds support for new audit log information
=> Add new audit log options

README.md
There are some minor documentation problems on the base README.md. This resolves some of them. This is a follow up to [PR#1132](https://github.com/DV8FromTheWorld/JDA/pull/1132). This PR contains the grammatical fixes without the wording changes.
=> Update some grammatical errors in README.md

src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
Closes Issue: #1094 
This is not provided for reaction events and we should at least document it. Throwing an exception seems like a bad idea.
=> Add notice about isSelf in events

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
The old format (only SSRC) is deprecated and will be removed in the future.
=> Move to new UDP discovery format

src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Discord does not check the name for this anymore so we shouldn't be either.
=> Fix TextChannel#isNSFW

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Closes Issue: #1173 
The `addQueryParameter` method returns a new route instance that we should be using. I also removed some duplicate code.
=> Correctly apply reason to query

src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
The PrivateChannel needs a strong reference because users might not be in cache anywhere else. These channels are of temporary nature and will be deleted soon after creation anyway.
=> Hold strong reference to user from private channel

src/main/java/net/dv8tion/jda/api/entities/TextChannel.java
Closes Issue: #1179
Removed the info, that JDA would check for if the TextChannel starts with "nsfw-" or equals "nsfw"
=> Remove invalid NSFW info

src/main/java/net/dv8tion/jda/api/exceptions/ErrorHandler.java, src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
This class makes error handling for RestActions a little easier.
```java
user.openPrivateChannel()
.flatMap(channel -> channel.sendMessage("Hello Friend"))
.delay(Duration.ofSeconds(30))
.flatMap(Message::delete)
.queue(null, new ErrorHandler()
.ignore(UNKNOWN_MESSAGE)
.handle((error) -> ctx.reply("Cannot send message!"), CANNOT_SEND_TO_USER));
```
=> Add ErrorHandler utility class

src/main/java/net/dv8tion/jda/api/entities/Message.java
This PR documents another possible `null` return case of `Message#getMember` if the Message was sent by a Webhook.
=> Document another possible null return case of Message#getMember

src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/RateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Closes Issue: #1212 
This will allow queued actions to finish gracefully. Additionally, I adjusted the documentation to mention the exception thrown in case of shutdown.
=> Allow queued requests to finish

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/Message.java
This PR fixes and improves EmbedBuilder constructor javadocs.
=> Fix EmbedBuilder constructor javadocs

src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Fixes an NPE for `createCopy` where the member is not cached.
=> Fix GuildChannel#createCopy for uncached members

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
=> Added getGuildChannelById methods to ShardManager

README.md, src/examples/java/AudioEchoExample.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GenericGuildMemberEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberJoinEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberLeaveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberRoleAddEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberRoleRemoveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GenericGuildMemberUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateBoostTimeEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateNicknameEvent.java, src/main/java/net/dv8tion/jda/api/events/user/UserActivityEndEvent.java, src/main/java/net/dv8tion/jda/api/events/user/UserActivityStartEvent.java, src/main/java/net/dv8tion/jda/api/events/user/UserTypingEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/GenericUserUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateActivityOrderEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateAvatarEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateDiscriminatorEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateNameEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
This allows disabling flags without needing to specify an entire config.
This is very useful with the new factory methods.
~~We should also consider adding `enableIntents` and `disableIntents` for the same reason. I've seen users do `GatewayIntent.getIntents(DEFAULT & ~intents)` which would be a lot cleaner using `disableIntents(intents)`.~~ I decided to include this in the PR.
=> Add better configuration methods to the builders

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java
This will initialize the SelfUser before firing any event for the specific shard.
=> Initialize SelfUser for all shards before logging them in

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This can be very useful to determine if a bot is eligible for large bot sharding or if discord is having other issues.
=> Add the close code to the disconnect warn

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Closes Issue: #1243
This PR adds Guild#getMaxFileSize and Guild.BoostTier#getMaxFileSize. Comments and suggestions are very welcome.
=> Add Guild#getMaxFileSize and Guild.BoostTier#getMaxFileSize

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/concurrent/AsyncHandle.java, src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java, src/main/java/net/dv8tion/jda/internal/hooks/EventManagerProxy.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java, src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java, src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
This implements the new get by prefix chunking features. This can be useful for bots that need to fetch members by names for various reasons.
```java
guild.retrieveMembersByPrefix("Minn", 100).onSuccess(list -> {
list.stream()
.filter(it -> it.getUser().getAsTag().equals("Minn#6688"))
.findFirst()
.ifPresent(member -> {
System.out.println("Minn#6688 is a member of this server");
});
});
```
=> Add retrieveMembersByPrefix

src/main/java/net/dv8tion/jda/api/entities/Message.java
This seems to be common trouble so we should just create files automatically if necessary.
=> Create file if it doesn't exist in downloadToFile

src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
This improves our handling of missing join time information.
=> Improve handling of join times for members

src/main/java/net/dv8tion/jda/api/entities/Message.java
Adds a useful pattern for jump urls. I also improved the invite pattern a bit.
=> Add Message.JUMP_URL_PATTERN

src/main/java/net/dv8tion/jda/api/audio/hooks/ListenerProxy.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/Role.java, src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java, src/main/java/net/dv8tion/jda/api/hooks/InterfacedEventManager.java, src/main/java/net/dv8tion/jda/api/requests/Request.java, src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Replace usages of `AssertionError` with `IllegalStateException` to avoid killing the thread.
=> Improvements to handling of Error

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
We are supposed to use the body for sending parameters in POST requests.
Reference: https://github.com/discord/discord-api-docs/issues/1720#issuecomment-640948326
=> Use FormBody for prune post request

src/main/java/net/dv8tion/jda/api/MessageBuilder.java
This method adds no valuable feature and only contains duplicate code which is awful for maintainability. It also doesn't handle allowed_mentions correctly, due to me forgetting it existed.
=> Deprecate MessageBuilder#sendTo

src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermOverrideData.java
This causes overrides to be duplicated in the set which resulted in inconsistent override sets. I replaced the set with a map to account for this problem.
=> Fix issues with duplicate overrides in ChannelAction

src/main/java/net/dv8tion/jda/api/MessageBuilder.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/exceptions/InsufficientPermissionException.java, src/main/java/net/dv8tion/jda/api/exceptions/MissingAccessException.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/WebhookManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Closes Issue: #1272 
Adds new implicit permission rules for voice channel connect.
=> Add check for voice connect permission

build.gradle.kts, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
This added a new copy constructor so we can cleanup some code.
=> Update WebSocket library to 2.10

src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
Reference: https://github.com/discord/discord-api-docs/pull/1843
=> Switch to new permission key

src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java, src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java
This pull request makes StoreChannels mentionable through JDA.
=> Make StoreChannel implement IMentionable

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateLocaleEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Adds support for guild locale. This can be configured in community guilds and public guilds.
=> Add support for guild locale

src/main/java/net/dv8tion/jda/api/events/guild/GuildJoinEvent.java
This PR fixes a typo in GuildJoinEvent docs.
=> Fix typo in GuildJoinEvent docs

src/main/java/net/dv8tion/jda/api/events/message/guild/react/GenericGuildMessageReactionEvent.java, src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java, src/main/java/net/dv8tion/jda/api/events/message/priv/react/PrivateMessageReactionAddEvent.java, src/main/java/net/dv8tion/jda/api/events/message/priv/react/PrivateMessageReactionRemoveEvent.java, src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
I forgot about these in the previous PR.
=> Add some convenience methods to GenericGuildMessageReactionEvent

src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/api/utils/Result.java, src/main/java/net/dv8tion/jda/internal/requests/DeferredRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/CombineRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Closes Issue: #1257 
This adds some operators to allow combining multiple RestActions into one.
```java
RestAction<List<Message>> sendMessages(Collection<MessageChannel> channels, String content) {
List<RestAction<Message>> actions = channels.stream()
.map(channel -> channel.sendMessage(content))
.collect(toList());
return RestAction.allOf(actions);
}
void ban(Member member, TextChannel modLog, TextChannel context) {
String content = member.getAsMention() + " has been banned!";
RestAction<Void> both = modLog.sendMessage(content).and(context.sendMessage(content));
member.ban(0)
.flatMap((v) -> both)
.queue();
}
```
=> Implement RestAction#and operator

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Closes Issue: #1386
Discord allows users to manage channels in specific categories. This is a detail which is not mentioned in the official api docs but can be verified.
=> Apply MANAGE_CHANNEL context to categories

src/main/java/net/dv8tion/jda/api/MessageBuilder.java
=> fix 'weather' typos

src/main/java/net/dv8tion/jda/api/entities/User.java
this pr adds a dot to getEffectiveAvatarUrl docs so it doesn't look weird as there's only a space:
#ocd
=> add a dot to getEffectiveAvatarUrl docs

src/main/java/net/dv8tion/jda/api/requests/CloseCode.java
Currently the message is "sent sent", but it should be "seq sent".
=> Fix 4007 Close Code typo

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
this pr fixes "a activity" typos across builders
=> fix "a activity" typos

src/main/java/net/dv8tion/jda/api/entities/User.java
for reference: discord/discord-api-docs#2011
maybe add "freezer" label to this pr until my pr in discord-api-docs repo gets merged/closed
=> rename some userflags to match their new name

src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
this PR adds onGuildMemberUpdate method to ListenerAdapter so it's possible to override it
=> add onGuildMemberUpdate method to ListenerAdapter

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
This resolves a few issues with race-conditions and improper exceptions being thrown. An HTTPException should not throw a LoginException, but instead throw an ErrorResponseException like we do everywhere else.
=> Improve handling of exceptions during login process

src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
This intent allows to handle [`WEBHOOKS_UPDATE`](https://discord.com/developers/docs/topics/gateway#webhooks-update) events. They are mostly useless as stated at #1330 but still could be used in some cases e.g. to invalidating local webhooks cache instantly if something changed.
=> Uncomment GUILD_WEBHOOKS intent

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/Role.java, src/main/java/net/dv8tion/jda/api/package-info.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java
this PR fixes some typos in the docs
=> fix some typos

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Role.java, src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMemberRemoveHandler.java, src/main/java/net/dv8tion/jda/internal/hooks/EventManagerProxy.java
This introduces the new tags for roles which can be used to identify which role is used for boosters or the bot.
=> Implement Role#getTags and add CacheFlag#ROLE_TAGS

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Reason is explained here: https://github.com/discord/discord-api-docs/issues/2257
=> Improve reconnect logic for voice sessions after invalidate

src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
Closes #1466 
just a fix for #1466
=> fix generic reaction event for GatewayIntent.fromEvents

src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Closes #1461
this PR adds ChannelManager#setNews and ChannelAction#setNews. i'm open for suggestions as i'm not really sure about using ternary when setting the type.
=> add ChannelManager#setNews and ChannelAction#setNews

src/main/java/net/dv8tion/jda/api/entities/Category.java, src/main/java/net/dv8tion/jda/api/entities/IPermissionHolder.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/internal/entities/CategoryImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Closes Issue: #1499 
This is a fix for the breaking change introduced last night by night. See https://github.com/discord/discord-api-docs/issues/2522
=> Fix permission sync with manage roles/permissions

src/main/java/net/dv8tion/jda/api/entities/Activity.java
Adds a `@see` link for the competing type to the Activity class description
=> Add competing to See also links

src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
this PR fixes copypasted documentation for GuildVoiceState#isMuted
=> fix docs for GuildVoiceState#isMuted

src/main/java/net/dv8tion/jda/api/utils/SessionController.java
this PR removes builders instantiations and fixes removed buildAsync method in SessionController class level docs
=> update docs for SessionController

src/main/java/net/dv8tion/jda/api/entities/Message.java
Adds a new MAX_REACTIONS constant which details the maximum number of reactions any message can have.
=> Add maximum reactions constant

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Adds a check for the max length of the author name field as we discovered that it is not checked
=> Add a length check for the author name

src/main/java/net/dv8tion/jda/api/Permission.java
This adds the new **Use Slash Commands** permission that can be used on channels.
=> Add Permission.USE_SLASH_COMMANDS

src/main/java/net/dv8tion/jda/api/entities/Guild.java
this should hopefully clarify what this method returns if the guild doesn't have the community feature as i think it's not clear at all from current docs
=> clarify Guild#getLocale for guilds without the COMMUNITY feature

src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateOwnerEvent.java
fixes mismatched docs for GuildUpdateOwnerEvent getters
=> fix mismatched docs for GuildUpdateOwnerEvent getters

src/main/java/net/dv8tion/jda/api/entities/Guild.java
Updates the docs for `Guild#getFeatures()` with the latest set from the Discord docs.
=> Update Features list for Guild#getFeatures()

src/main/java/net/dv8tion/jda/api/entities/Member.java
Added the word "Member" to the description of the kick() method so it follows the same wording as the other one
(now with the right branch)
=> Minor improvement in the Member#kick() docs

src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
This pull request syncs the documentation of MessageAction#reference and MessagesAction#referenceById
=> Fixed Documentation for MessageAction#reference

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/VanityInvite.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
This allows bots to view how many times the vanity invite has been used. I don't really have a place where I can test this, unfortunately.
=> Add Guild#retrieveVanityInvite

src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateActivitiesEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java
This new event can be used to handle the updated activities after all start/end events are fired.
=> Add UserUpdateActivitiesEvent

src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
Closes Issue: #1513
This adds error logging for exceptions/errors thrown by onSuccess/onFailure callbacks.
=> Add error logging for callbacks in GatewayTask

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
Adds a replacement for `getMembersWithRoles` which performs chunking.
=> Add findMembersWithRoles

src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java, src/main/java/net/dv8tion/jda/api/entities/Role.java, src/main/java/net/dv8tion/jda/api/entities/SelfUser.java, src/main/java/net/dv8tion/jda/api/entities/Webhook.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java, src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java
This should improve the memory footprint.
We don't need thread-safe acquisition for unsafe managers.
=> Remove thread-safe acquisition of managers

src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/entities/Webhook.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java
This allows bots to follow announcement channels.
See: https://github.com/discord/discord-api-docs/pull/1837
=> Implement TextChannel#follow and add source references

README.md, build.gradle.kts
Referenced Discussion: https://github.com/DV8FromTheWorld/JDA/discussions/1538
JCenter is being sunset as a Maven artifact repository. As such, we are moving away from it.
Details on the sunsetting [are available here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).
=> Changed maven publish repository to AWS S3 backed repository

src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java
Closes Issue: #1550
This slightly improves performance by caching the method handles over time. This trades memory for CPU usage.
=> Use MethodHandle for ListenerAdapter

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/StoreChannel.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/StoreChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Allows all guild channels to be mentioned.
=> Allow all guild channels to be mentioned

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Closes #1473 
this PR adds support for stickers. the api docs say the assets url for stickers is private, so i'm not sure whether or not to remove `getStickerUrl()`
=> add support for stickers

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
See https://github.com/discord/discord-api-docs/pull/2762
=> Add Message.Attachment#getContentType

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
this PR adds checks for kick and ban reason length and also removes invalid mentions of passing null member in Member interface
=> add checks for the reason length in Guild#kick and Guild#ban and remove some invalid docs

src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
This PR rewrites some parts of the docs which will make it a bit easier for the readers to read.
=> Fix typo in ShardManager

src/main/java/net/dv8tion/jda/api/exceptions/ErrorHandler.java
Fix a spelling mistake in ErrorHandler (flapMap -> flatMap)
=> Fix spelling mistake in ErrorHandler

src/main/java/net/dv8tion/jda/api/entities/Activity.java
Adds a line to the `CUSTOM_STATUS` entry mentioning, that it is read-only for bots, to prevent any possible confusion.
=> Mention that CUSTOM_STATUS is read only

README.md
This adds a comment to use `implementation` over the outdated `compile` function.
=> Add implementation comment

src/main/java/net/dv8tion/jda/api/Region.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java, src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateRegionEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRegionEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/managers/GuildManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
Closes Issue: #1570 
This pull request adds support for VoiceChannel region overrides
=> Add support for VoiceChannel region overrides

src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
this PR fixes parsing of stickers because discord likes to do breaking changes in prod. there are more changes but this PR is just to stop receiving errors
=> fix parsing stickers

src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
This pull request fixes ChannelAction#setTopic not doing anything,
You can reproduce this by running
```java
guild.createTextChannel("test").setTopic("topic").queue(); // Topic won't get set
```
=> Fix ChannelAction#setTopic not doing anything

README.md
The name apparently changed and some Troll took the user and repo name.
For more info see: https://github.com/Frederikam/Lavalink/pull/3#issuecomment-862751709
Im not sure about the maintainer part so I just changed it to the owner of the new repo.
=> Update Lavlink Links in README.md

src/main/java/net/dv8tion/jda/api/Region.java
Just removed a false @Nonnull annotation in the getEmoji() method of the Region Enum.
=> Removed false @Nonnull

src/main/java/net/dv8tion/jda/api/Permission.java
This adds the new permissions for threads. Necessary for moderation purposes.
=> Add thread permissions

src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceVideoEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
This pull request adds a GuildVoiceVideoEvent that fires, when a member starts/stops sending video
=> Add GuildVoiceVideoEvent

src/main/java/net/dv8tion/jda/api/events/message/priv/react/GenericPrivateMessageReactionEvent.java
This PR implements some helper retrieve methods for private reaction events.
=> Implement retrieve helpers for private reaction events

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateNSFWLevelEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
Original PR [HERE](https://github.com/DV8FromTheWorld/JDA/pull/1626#issuecomment-908048119)
Adds the enum NSFWLevel to the Guild object and an event for when the level changes.
=> Add NSFWLevel

src/main/java/net/dv8tion/jda/api/entities/Invite.java
Fix a typo in Invite#isTemporary().
=> Fix a typo in Invite

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
This PR adds Command#getVersion. ~(Not yet documented by Discord)~ **UPDATE**: [PR Merged](https://github.com/discord/discord-api-docs/pull/3524)
=> Add Command#getVersion

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
Added id as fallback on version field on command object
=> Add id as fallback on Command version

src/main/java/net/dv8tion/jda/api/entities/Guild.java
this PR fixes the boost amounts required for each tier in the docs.
=> fix boost amounts in the docs

src/main/java/net/dv8tion/jda/api/Permission.java
Added the `START_EMBEDDED_ACTIVITIES` Permission (`VOICE_START_ACTIVITIES` in JDA) and added it to the Voice Channel Permission Overrides. See [Discord Docs](https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags).
=> Added START_EMBEDDED_ACTIVITIES Permission

src/main/java/net/dv8tion/jda/internal/requests/Route.java
Added the new thread relating routes
Original PR: #1767
=> Added all thread relating routes

src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
This replaces the JavaDoc link that links to the no longer existing response-codes page (404)
=> Replaced outdated link to Discord Error Codes

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Invite.java, src/main/java/net/dv8tion/jda/api/entities/MessageSticker.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberLeaveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRegionEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/managers/AudioManager.java, src/main/java/net/dv8tion/jda/api/managers/GuildManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
In preparation for the v4 LTS, this PR marks each deprecated location for removal at the latest in 5.0.0.
=> Mark every deprecation for removal at the latest in 5.0.0

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
this PR adds OptionData#setChannelTypes. see https://github.com/discord/discord-api-docs/pull/3825
=> Add OptionData#setChannelTypes

src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
Fixed a typo, "mention the used" => "mention the user"
=> Fixed a typo

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
this PR fixes the name of reaction remove emoji event to the correct name.
=> fix reaction remove emoji event name

src/main/java/net/dv8tion/jda/internal/requests/Route.java
Unfortunately, I missed 3 routes being incorrect.
So `ADD_THREAD_MEMBER`, `LIST_PRIVATE_ARCHIVED_THREADS` and `LIST_JOINED_PRIVATE_ARCHIVED_THREADS` have been fixed.
And `GET_THREAD_MEMBER` has been added
(unsure whenever I missed them or they weren't in the documentation yet)
Unsure whenever I've to PR this to `v5` or `v5-threads`
=> Added new thread relating routes and fixed old ones

src/examples/java/MessageListenerExample.java
… display name, nickname and user mention to the text channel
I added another example command to the MessageListenerExample.java file. It's a simple whoami command.
It sends a text message to the text channel wich contains ID, EffectiveName, Nickname and User Mention from the User.
=> Added whoami as command to the MessageListenerExample which sends id,… 

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
this PR adds support for min/max option value. see https://github.com/discord/discord-api-docs/pull/3967/
=> add support for min/max option value

src/main/java/net/dv8tion/jda/api/events/role/update/RoleUpdateIconEvent.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildRoleUpdateHandler.java
this PR fixes an NPE introduced by #1823.
=> Fix NPE in GuildRoleUpdateHandler

README.md
This updates the readme for the new maven-central and jitpack setup.
=> Update readme for new publishing logic

src/main/java/net/dv8tion/jda/api/entities/Guild.java
- [] Library interface (affecting end-user code) 
Backport of deprecation removal from #1909 (https://github.com/DV8FromTheWorld/JDA/pull/1909/commits/a0d59ac3084fa3f861a4691e7d443d259659ea53)
=> Backport of deprecation removal on Guild#retrieveRegions

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Closes Issue: #1917 
this PR makes Guild#moveVoiceMember support AudioChannel instead of only VoiceChannels. the method name is questionable after these changes, so I'm open for renaming it.
=> Make Guild#moveVoiceMember support AudioChannel instead

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
this PR adds ability to get the attachment description using Message.Attachment#getDescription.
=> add Message.Attachment#getDescription

src/main/java/net/dv8tion/jda/api/events/channel/GenericChannelEvent.java
this PR adds `GenericChannelEvent#isFromGuild` and `GenericChannelEvent#getGuild`.
=> Add GenericChannelEvent#isFromGuild and GenericChannelEvent#getGuild

src/main/java/net/dv8tion/jda/api/entities/IThreadContainer.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ThreadChannelAction.java, src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IThreadContainerMixin.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ThreadChannelActionImpl.java
Closes Issue: #1918
this PR renames `ThreadAction` and `ThreadActionImpl` to `ThreadChannelAction` and `ThreadChannelActionImpl`.
=> Rename ThreadAction to ThreadChannelAction

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java
this PR transforms magic values in `SelectionMenu` and `SelectionMenu.Builder` into constants.
=> transform SelectionMenu magic values into constants

src/main/java/net/dv8tion/jda/api/managers/AccountManager.java, src/main/java/net/dv8tion/jda/api/managers/EmoteManager.java, src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java, src/main/java/net/dv8tion/jda/api/managers/RoleManager.java, src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java, src/main/java/net/dv8tion/jda/api/managers/TemplateManager.java, src/main/java/net/dv8tion/jda/api/managers/WebhookManager.java
this PR replaces hex codes in managers with bitshifts. see the [v5 board card](https://github.com/DV8FromTheWorld/JDA/projects/5#card-72644880).
=> Use bitshifts instead of hexcodes in managers

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java
this PR adds support for animated guild banners.
=> Add support for animated guild banners

src/examples/java/MessageListenerExample.java
Closes Issue: #1968
this PR removes a mention of the `AccountType.CLIENT` from `MessageListenerExample`.
=> remove AccountType#CLIENT mention from MessageListenerExample

src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java
This PR makes it so the message count in a thread never exceeds 50, as Discord won't send more than 50
=> Limit new thread message count to 50

src/main/java/net/dv8tion/jda/api/entities/ICategorizableChannel.java
Optional minor PR as requested in #1838
=> Nullable parent string ID nullable for categorizable channels

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
Closes #2002 
Fixes logic in the `setAutoComplete` method.
=> Fix OptionData#setAutoComplete logic.

src/main/java/net/dv8tion/jda/api/interactions/commands/OptionMapping.java, src/main/java/net/dv8tion/jda/api/interactions/commands/OptionType.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionPayloadImpl.java
This adds support for file attachments in slash command options. Opening as draft since this isn't released yet.
=> Add support for attachment options

src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
Fixes misspelled enum value in ErrorResponse
=> Fix misspelled ErrorResponse enum value

build.gradle.kts, src/main/java/net/dv8tion/jda/api/managers/channel/middleman/AudioChannelManager.java
Replace this sentence with general description of what your Pull Request does.
=> Make javadocs fail on error

src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionBulkRemoveHandler.java
Fixes #2004
Closes Issue: #2004
This adds proper guild lock handling for some event handlers.
=> Fix issues with event cache

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/entities/MessageReference.java, src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/InteractionHookImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ComponentInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java
Closes #2041 
Discord sends ephemeral messages as if they were direct messages, this even goes as far as receiving them when you only enable DIRECT_MESSAGES intent.
=> Drop message create for ephemeral messages

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Supersedes #1227
Adds destructor for guilds, which detaches all the cache of the guild from cache.
=> Add GuildImpl#invalidate

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/entities/UserReference.java, src/main/java/net/dv8tion/jda/api/entities/UserSnowflake.java, src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MemberAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserById.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserSnowflakeImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java
Solves problem of having 3 overloads for every method that accepts a user id. I'm intentionally keeping `getMemberById` because it is used everywhere by everyone and removing it isn't worth breaking all bots.
=> Add UserSnowflake and improve User#fromId

src/main/java/net/dv8tion/jda/api/entities/StageInstance.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/StageInstanceImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
We intentionally suppress okhttp warnings for compatibility
Fixes some deprecation warnings and removes StageInstance#isDiscoverable
=> Handle deprecations

src/main/java/net/dv8tion/jda/api/entities/EmbedType.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageType.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Discord just started rolling out auto-moderation filters for content. These can send warning messages like this:
The information of these messages is contained in embeds.
Full JSON:
```json
{
"mention_everyone" : false,
"components" : [ ],
"pinned" : false,
"attachments" : [ ],
"author" : {
"avatar" : "d3df0c6c50b5a85854cd67843d7554cb",
"id" : 222046562543468545,
"public_flags" : 0,
"avatar_decoration" : null,
"discriminator" : "6440",
"username" : "freya02"
},
"flags" : 0,
"mention_roles" : [ ],
"type" : 24,
"content" : "",
"edited_timestamp" : null,
"tts" : false,
"mentions" : [ ],
"id" : 969899048796561438,
"channel_id" : 969898020013473792,
"embeds" : [ {
"description" : "~~not free discord …
```
=> Add new message types for automod

src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
=> FileProxy: Fix parent folder exists check

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
Added a return value documentation in MessageChannel.java
=> Add missing return value description

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
Closes Issue: #2132
As stated in issue #2132 the Nullable has been changed to Nonnull to avoid confusion.
=> Changed addField String name and String Value to Nonnull

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
this PR tweaks some aspects of identify payloads as [proposed in the Discord server](https://canary.discord.com/channels/125227483518861312/979391918461050950/979393219555102750).
=> Make some tweaks to identify payloads

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
This exposes the new `CacheRestAction` interface for all deferrable RestActions in jda.
=> Make more use of CacheRestAction

src/main/java/net/dv8tion/jda/api/entities/Activity.java, src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/api/entities/emoji/Emoji.java, src/main/java/net/dv8tion/jda/api/entities/emoji/EmojiUnion.java, src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/api/events/message/react/MessageReactionRemoveEmojiEvent.java, src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectOption.java, src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/RichPresenceImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/UnicodeEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmojiHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
Oversight from the emoji rework, this adds a way to easily convert the emoji types in events like reaction events.
=> Add EmojiUnion

src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Fixes the `MessageType#deletable` getter.
=> fix: Make MessageType#deletable return an accurate value.

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectOption.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmojiHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java
This handles empty emoji names in some situations. The current code throws an exception instead.
=> Fix handling of empty emoji names

src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
`SlashCommandData` is for context commands too, so check the `Command.Type` instead
=> Fix LocalizationMapper for context commands

src/main/java/net/dv8tion/jda/api/events/interaction/ModalInteractionEvent.java, src/main/java/net/dv8tion/jda/api/events/interaction/command/CommandAutoCompleteInteractionEvent.java, src/main/java/net/dv8tion/jda/api/interactions/ModalInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/commands/CommandAutoCompleteInteraction.java, src/main/java/net/dv8tion/jda/internal/interactions/ModalInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandAutoCompleteInteractionImpl.java
This adds `ModalInteraction#getMessage` and makes `CommandAutoCompleteInteraction` return unions for channels.
=> Add some missing interaction features

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
=> Fix typo in MarkdownSanitizer

build.gradle.kts, src/main/java/net/dv8tion/jda/api/audit/ActionType.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/api/audit/TargetType.java
Closes Issue: #2196
This PR should add support for the Sticker Audit Actiontyp.
=> Add sticker features for audit logs

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
This PR adds a `getJumpUrl` method to the `GuildChannel` interface.
=> Implement `GuildChannel#getJumpUrl`

src/main/java/net/dv8tion/jda/internal/utils/SimpleLogger.java
Quick Typo correction in net.dv8tion.jda.utils.SimpleLogger - Lines #39, #64 and #144
Was: "Loggerger" - Is: "Logger"
=> Typo correction

src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Closes #2215
Converting types shouldn't be allowed since it also affects the generic parameter.
=> Remove ChannelAction#setType

src/main/java/net/dv8tion/jda/api/JDAInfo.java
Use WS API 10 to disable MESSAGE_CONTENT when not enabled.
(Breaking change)
=> Update to gateway version 10

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/WebhookClient.java, src/main/java/net/dv8tion/jda/api/interactions/callbacks/IReplyCallback.java, src/main/java/net/dv8tion/jda/api/utils/messages/AbstractMessageBuilder.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractWebhookClient.java
You can now send messages which contain nothing but components.
=> Add support for component-only messages

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Handles possible future query parameters added to gateway URLs by discord.
=> Change handling of query parameters for websocket connections

src/main/java/net/dv8tion/jda/api/audio/factory/IPacketProvider.java, src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java, src/main/java/net/dv8tion/jda/api/entities/channel/middleman/AudioChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/middleman/StandardGuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/unions/AudioChannelUnion.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GenericGuildVoiceUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceJoinEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceLeaveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceMoveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceUpdateEvent.java, src/main/java/net/dv8tion/jda/api/managers/AudioManager.java, src/main/java/net/dv8tion/jda/api/managers/channel/middleman/AudioChannelManager.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/AudioChannelMixin.java, src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
1. Adds an `AudioChannelUnion` to simplify some code paths.
2. Make `AudioChannel` a `StandardGuildChannel` which adds:
- Invites
- Category getter
- Permissions
- Positions
- Copying
=> Improve usability of AudioChannel

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
This corrects the exception thrown for owner checks in a few places. This was unintentionally changed to throw `IllegalArgumentException`, however it should throw `HieararchyException`.
There also was a wrong annotation in `Member#timeoutUntil`.
=> Fix some checks not throwing the intended exception

src/main/java/net/dv8tion/jda/api/events/thread/ThreadRevealedEvent.java, src/main/java/net/dv8tion/jda/internal/handle/ThreadCreateHandler.java
Adds handling for `newly_created` on THREAD_CREATE.
=> Handle newly_created gracefully

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
Since discord also shows these tags in sort order, we should do the same here.
=> Retain sort order for ThreadChannel#getAppliedTags

src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java, src/main/java/net/dv8tion/jda/api/utils/FileProxy.java, src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Checks if an existing path is a "regular file" and if it is writable
=> FileProxy: additional checks on existing files

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java, src/main/java/net/dv8tion/jda/api/interactions/callbacks/IReplyCallback.java, src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageCreateAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/ReplyCallbackAction.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Added ability to delete ephemeral messages
=> Update docs regarding deletion of ephemeral messages

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java
Fixes documentation for SelectMenu
=> Fixes the documentation for SelectMenu

src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageCreateAction.java
The limitations were a bit outdated and I also added some more information regarding deferred replies.
=> Update the docs for setEphemeral

src/main/java/net/dv8tion/jda/api/entities/channel/ChannelType.java, src/main/java/net/dv8tion/jda/api/events/interaction/component/EntitySelectInteractionEvent.java, src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericSelectMenuInteractionEvent.java, src/main/java/net/dv8tion/jda/api/events/interaction/component/StringSelectInteractionEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/interactions/components/ActionRow.java, src/main/java/net/dv8tion/jda/api/interactions/components/Component.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenuInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectMenu.java, src/main/java/net/dv8tion/jda/internal/entities/SelectMenuMentions.java, src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectMenuImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/SelectMenuImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/SelectMenuInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/StringSelectInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/StringSelectMenuImpl.java
Closes #2280
Adds support for the 4 new select menu components. This comes with breaking changes:
| Old | New |
|-----|------|
| SelectMenu | StringSelectMenu |
| SelectMenuInteraction | StringSelectInteraction |
Supersedes #2281
=> Implement new select menus

src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Closes Issue: #2313
This fixes a `NullPointerException` when adding or removing features to a guild.
=> Fix NullPointerException in GuildManagerImpl#addFeatures and GuildManagerImpl#removeFeatures

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventGatewayEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/GenericScheduledEventUserEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventCreateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventDeleteEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserAddEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/ScheduledEventUserRemoveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/GenericScheduledEventUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateDescriptionEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateEndTimeEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateImageEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateLocationEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateNameEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStartTimeEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/ScheduledEventUpdateStatusEvent.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java
This should help troubleshoot issues regarding some cache situations.
=> Add some missing documentation to clarify cache

src/main/java/net/dv8tion/jda/api/entities/User.java
This PR adds the new `ACTIVE_DEVELOPER` UserFlag (1 << 22)
=> Implement "ACTIVE_DEVELOPER" UserFlag

src/main/java/net/dv8tion/jda/internal/entities/MessageMentionsImpl.java
Closes #2333 
This caused stackoverflow exceptions when trying to print/serialize the json object.
=> Fix recursive json object created in mention parsing

src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
This fixes some edge cases where locks are not released properly, causing deadlocks.
=> Fix some lock issues

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadMemberPaginationActionImpl.java
This will be renamed in the API to `member` most likely. When that happens, we can just merge this.
=> Remove code to rename guild_member to member

.gitignore
=> Add vscode and fleet files to gitignore

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Yes.
This fixes an exception when no emoji is used on the welcome channel.
=> Fix welcome channel parsing when no emoji is used

src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/CombineRestAction.java
Using an atomic int is more efficient.
=> Replace lock code with atomic int

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/sticker/Sticker.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Supposedly this will be supported in the future, not yet though.
Reference: discord/discord-api-docs#5833
=> Add support for gif stickers

README.md, build.gradle.kts
Closes #2381 
This updates okhttp to address vulnerabilities in transitive dependencies.
=> Update okhttp to 4.10.0

README.md
- adding ")" to README.md
fixing a typo in README.md
=> ")" was missing in README.md

src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java, src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalImpl.java
This is more consistent with the message rework. We expect new layout components to exist in the future and thus make our interface prepared to deal with it.
**This is semi-breaking**: `Modal.Builder#getActionRows` used to return a mutable list to allow removing existing rows, instead it now returns an immutable list and you should use `Modal.Builder#getComponents` instead.
=> Add Modal.Builder#addComponents

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Closes Issue: #2305 
This adds the `position` property from the message object.
=> Add thread message positions

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/ScheduledEventUpdateHandler.java
Fixes #2394
This can cause the guild to not be loaded properly.
=> Catch parsing exception for scheduled events

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
This was changed a while ago and we incorrectly send/receive 70 instead of 74.
=> Use 74 byte handshake

src/main/java/net/dv8tion/jda/api/entities/Mentions.java, src/main/java/net/dv8tion/jda/internal/entities/MessageMentionsImpl.java, src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java
Closes Issue: #2408
This now also adds reply mentions to the bag getters. I've also changed the internals to use Collectors for cleaner code.
=> Count reply mentions in bag getters

src/examples/java/SlashBotExample.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java, src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ForumChannel.java, src/main/java/net/dv8tion/jda/api/events/channel/update/ChannelUpdateDefaultLayoutEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/managers/channel/ChannelManager.java, src/main/java/net/dv8tion/jda/api/managers/channel/concrete/ForumChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ForumChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
https://discord.com/developers/docs/change-log#add-default-layout-setting-for-forum-channels
=> Add default_forum_layout for Forum Channel

src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java
This PR replaces the references to GuildAction inner classes so they point to GuildAction instead of GuildActionImpl
Same goal as #2419
=> Replace implementation references in GuildAction

src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectMenu.java
=> Fixing a typo

src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
It was sending the enum name instead.
=> Fix channel manager not using right type

src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
Handles new channel field. This will be important for future API changes.
Reference: https://github.com/discord/discord-api-docs/pull/6051
=> Handle new channel field on interactions

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Fixes #2441 
Properly initialize requester in shard manager.
=> Fix NPE in shardmanager

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java, src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
Sometimes the member chunk requests seem to be a lot slower than expected. This will allow people to set a higher timeout than the default 10 seconds.
=> Support custom timeout on tasks

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
This caused tasks to be retried when an I/O error occurred.
=> Fix task not being marked as done on errors

src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
=> Fixing in EntitySelectMenu

src/main/java/net/dv8tion/jda/api/entities/Message.java
Changes the file upload limit from 8 MiB to 25 MiB
Docs commit: https://github.com/discord/discord-api-docs/commit/cfc4dcb835b2268274efe1ae5619ef7a769fb919
=> Update max file size to 25 MiB

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This improves the shutdown logic to gracefully handle shutdowns mid-reconnect attempts.
=> Fix slow shutdown during reconnects

src/main/java/net/dv8tion/jda/internal/entities/UserSnowflakeImpl.java
=> Update modulo for default avatars by id

README.md, build.gradle.kts, src/examples/java/MessageLoggerExample.java, src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/JDAInfo.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java, src/main/java/net/dv8tion/jda/api/interactions/commands/localization/LocalizationFunction.java, src/main/java/net/dv8tion/jda/api/interactions/commands/localization/ResourceBundleLocalizationFunction.java, src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java, src/main/java/net/dv8tion/jda/api/interactions/components/buttons/ButtonStyle.java, src/main/java/net/dv8tion/jda/api/managers/AccountManager.java, src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
This updates a lot of outdated links to the new recommended places.
=> Update outdated links

src/main/java/net/dv8tion/jda/api/events/automod/AutoModExecutionEvent.java, src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleCreateEvent.java, src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleDeleteEvent.java, src/main/java/net/dv8tion/jda/api/events/automod/AutoModRuleUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/automod/GenericAutoModRuleEvent.java
This is a required permission to receive automod events.
=> Add required permissions to automod events

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
This PR fixes the description of the EmbedBuilder#addField methods
=> Fix EmbedBuilder#addField docs typo

src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IGuildChannelContainer.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.java, src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/forums/ForumPost.java
Hopefully improves discovery of this discord naming alias.
=> Add details about posts being threads in some more places

src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
Fix documentation for GenericMessageEvent#getGuild.
=> Fix docs for GenericMessageEvent#getGuild

src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java
Closes Issue: #2512 
`MessageCreateRequest#applyData` should also suppress embeds if `data.isSuppressEmbeds()` is `true`
=> Fix MessageCreateRequest#applyData not suppressing embeds

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/interactions/modals/Modal.java
Fixes the docs in Modal (as setActionRows is now deprecated, though it may link to the same method it's marked for removal)
Fixes the docs in setAuthor where there would be a double "the" and next line
=> Fix some docs 

src/main/java/net/dv8tion/jda/api/interactions/DiscordLocale.java
Adds a shortcut for `Locale.forLanguageTag(DiscordLocale#getLocale())`
=> Add DiscordLocale#toLocale

src/main/java/net/dv8tion/jda/api/entities/Activity.java, src/main/java/net/dv8tion/jda/api/entities/RichPresence.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/RichPresenceImpl.java, src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java, src/test/java/net/dv8tion/jda/entities/ActivityTest.java
Allows adding state to activities. Also makes activities with only a state and name not appear as rich.
=> Add Activity#withState

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Adds a missing check for timeouts.
=> Add position check to timeouts

.github/ISSUE_TEMPLATE/bug_report.yml
It is better for future readers to know the version related to an issue.
=> Require specifying exact version in bug reports

src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java, src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Discord URLs now have query parameters by default.
=> Improve handling of query parameters in image proxy

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
This method causes an exception otherwise, if methods like ban are used without a member instance.
=> Add null check in checkPosition

src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceUpdateEvent.java
=> Add docs to GuildVoiceUpdateEvent

src/main/java/net/dv8tion/jda/api/events/message/MessageReceivedEvent.java
https://github.com/discord-jda/JDA/pull/2527#issuecomment-1740703029
=> Remove todo related to MessageReceivedEvent rename

src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
`channel.getFlags()` contains enums, not bit flags.
=> Fix ChannelManagerImpl#reset

src/main/java/net/dv8tion/jda/api/requests/Request.java, src/main/java/net/dv8tion/jda/api/requests/Response.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java
This adds a few more trace logs to further improve debugging capabilities.
=> Add more logging to request handling

src/main/java/net/dv8tion/jda/api/entities/MessageType.java
This is a new message type sent by automod when a temporary security measure is activated.
=> Add missing message types

src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java
The target message is not guaranteed to be by the bot.
=> Fix incorrect hook injection for message context commands

build.gradle.kts
Updated `okhttp` from 4.10.0 to 4.12.0
Updated `jackson-core` from 2.14.1 to 2.16.0
Updated `jackson-databind` from 2.14.1 to 2.16.0
Updated `junit-jupiter` from 5.8.2 to 5.10.1
Addressed CVEs:
CVE-2023-35116
CVE-2022-24329
CVE-2023-3635
=> Updating Dependencies

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java
Closes #2600
It seems like this has to be an empty string instead.
=> Fix clearing of voice status

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
Closes #2602
Adds handling for private threads in interactions, specifically the right check for canTalk.
=> Handle canTalk for private threads in interactions

src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Adds relevant, missing application info:
- Redirect URIs
- Interactions endpoint URL
- Role connections verification URL
=> Added missing properties to ApplicationInfo

src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java
Closes Issue: #2641
Discord now sends maps with int keys.
=> Handle numeric keys for ETF maps

build.gradle.kts
This publishing logic was very outdated.
=> Refactor nexus publishing logic

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Fix ClassCastException in EntityBuilder#updateMemberCache
=> Fix ClassCastException in EntityBuilder#updateMemberCache

src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessagePollBuilder.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessagePollData.java, src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
Fixes a small bug with poll creation through the MessageCreateBuilder.
=> Properly copy poll data in MessageCreateRequest#applyData

build.gradle.kts, settings.gradle.kts, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Logs the value of `_trace` for debugging websocket issues
=> Improve logging for gateway connection

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
=> Allow `UserSnowflake` subtypes in bulk ban methods

src/main/java/net/dv8tion/jda/api/Permission.java
Adds permissions that weren't included in the text/voice channel permission group
=> Add missing permissions in `ALL_[TEXT/VOICE]_PERMISSIONS`

src/main/java/net/dv8tion/jda/api/entities/MessageType.java
=> Update MessageType enum

src/main/java/net/dv8tion/jda/api/Permission.java
Add missing `USE_EXTERNAL_APPLICATIONS` permission.
=> Add missing permissions

.github/ISSUE_TEMPLATE/bug_report.yml
Closes Issue: N/A
1. Removed a suggestion to leave a required field empty
2. Removed a request to put error information in a code block, when it is already formatted as such (and later contradicted)
I deliberately targeted the default branch due to the nature of the change.
=> Fix inconsistent bug template descriptions

README.md
=> Link maven central badge to installation header

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Retries can happen on more error codes.
See [Cloudflare Troubleshooting](https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/) for reference.
=> Expand list of retried http error codes

settings.gradle.kts
Removes ByteBuddy from transitive dependencies
=> Update to Jackson 2.17.2

src/main/java/net/dv8tion/jda/api/entities/automod/build/AutoModRuleData.java
Adds support for creating profile automod rules.
Reference: https://github.com/discord/discord-api-docs/pull/6040
=> Add support for profile automod

src/main/java/net/dv8tion/jda/api/entities/EmbedType.java, src/main/java/net/dv8tion/jda/api/entities/MessageType.java
These enum constants were missing for message and enum types.
=> Add new message and embed types

README.md
addEventListener is invalid, addEventListeners is the correct version. Updates the .md
=> Change addEventListener to addEventListeners

.github/workflows/artifacts.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/validate.yml, build.gradle.kts
This adds a new github action we can use to publish releases manually through github instead of jenkins.
=> Add github action for publishing

src/main/java/net/dv8tion/jda/internal/entities/ScheduledEventImpl.java, src/test/java/net/dv8tion/jda/test/entities/scheduledevent/ScheduledEventTest.java
=> Cleanup ScheduledEvent#getJumpUrl

src/test/java/net/dv8tion/jda/test/compliance/ArchUnitComplianceTest.java, src/test/java/net/dv8tion/jda/test/compliance/RestActionComplianceTest.java
More compliance tests:
- Naming patterns for rest actions and managers
- Primitive return type annotations
- No impl classes in api package
=> Add more compliance tests

src/main/java/net/dv8tion/jda/api/managers/AudioManager.java
Moved from `sedmelluq` to `lavalink-devs`
=> Fix links to LavaPlayer in AudioManager

src/main/java/net/dv8tion/jda/api/managers/RoleManager.java
=> Fix typo in RoleManager

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/test/java/net/dv8tion/jda/test/JDABuilderTest.java, src/test/java/net/dv8tion/jda/test/TestHelper.java
Adds some tests to validate behavior for intents and cache flags in JDABuilder.
=> Add some tests for JDABuilder intents and cache flags

src/main/java/net/dv8tion/jda/api/Permission.java, src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/StageInstanceAction.java, src/main/java/net/dv8tion/jda/internal/managers/StageInstanceManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
This removes all the currently deprecated symbols that should have been gone since **5.1.0**.
=> Remove deprecated symbols with deadline 5.1.0

src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java, src/test/java/net/dv8tion/jda/test/util/PermissionUtilTest.java
Adds some tests for PermissionUtil functionality.
=> Add tests for PermissionUtil

src/examples/java/LocalizationExample.java, src/main/java/net/dv8tion/jda/api/entities/emoji/ApplicationEmoji.java, src/main/java/net/dv8tion/jda/api/events/guild/scheduledevent/update/GenericScheduledEventUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSafetyAlertsChannelEvent.java, src/main/java/net/dv8tion/jda/api/managers/ApplicationEmojiManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/EntitlementPaginationAction.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/ApplicationEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/managers/ApplicationEmojiManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/GuildStickerManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadChannelPaginationActionImpl.java, src/test/java/net/dv8tion/jda/test/interactions/ButtonTests.java
Some of these had the incorrect date or were missing entirely.
=> Fix missing or incorrect copyright headers

src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java, src/test/java/net/dv8tion/jda/test/IntegrationTest.java, src/test/java/net/dv8tion/jda/test/managers/GuildManagerTest.java
Fixes the implementation to actually send the channel id in the update.
=> Fix GuildManager#setSafetyAlertsChannel

src/main/java/net/dv8tion/jda/api/utils/messages/MessageRequest.java
Changes:
"Whether to mention the used, when replying to a message." to
"Whether to mention the user, when replying to a message."
"True, to mention the author if the referenced message" to
"True, to mention the author in the referenced message"
=> Fix javadoc typos in MessageRequest

src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java, src/test/java/net/dv8tion/jda/test/interactions/ButtonTests.java
Doing this in the constructor instead, ensures that it will never be null by accident.
=> Ensure label cannot be null in ButtonImpl

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
Continuation of ee7b6b986b31ce5ae1e4fe1f02bb8154eadaeaf7
=> Fix `DefaultShardManagerBuilder#setDisabledIntents`

src/main/java/net/dv8tion/jda/api/entities/Message.java
Small typo in the `getButtonById` javadoc.
=> Fix typo in `getButtonById` javadoc.

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
Timestamp, color and non-empty-but-blank descriptions doesn't make embeds non-empty, so I removed them from the checks
=> Fix checking empty embeds

src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericCommandInteractionEvent.java, src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericComponentInteractionCreateEvent.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java, src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java
Manually inherit (copy) deprecation docs, as Javadoc won't.
=> Manually inherit (copy) deprecation docs

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Closes Issue: #2700
Implements `Guild#retrieveScheduledEvents` and `Guild#retrieveScheduledEvents(boolean)` to retrieve a list of scheduled events
=> Add Guild#retrieveScheduledEvents

README.md
Closes Issue: #2811 
Documents the optional tink dependency relation.
=> Document exclusion of tink

src/main/java/net/dv8tion/jda/api/entities/Message.java
This allows JDA to match both of the below instead of just the first. This brings it in line with the discord client.
```
discord.com/invite/AAAAAAAA
discord.com/invite\AAAAAAAA
```
=> Allow \ in invite links

src/test/java/net/dv8tion/jda/test/entities/message/MessageRegexTest.java
Add some basic regex tests for invite links.
=> Add basic test for link regex

build.gradle.kts, src/main/java/net/dv8tion/jda/api/requests/restaction/AbstractThreadCreateAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ThreadChannelActionImpl.java, src/test/java/net/dv8tion/jda/test/IntegrationTest.java, src/test/java/net/dv8tion/jda/test/assertions/restaction/RestActionAssertions.java, src/test/java/net/dv8tion/jda/test/restaction/CommandEditActionTest.java, src/test/java/net/dv8tion/jda/test/restaction/ThreadCreateActionTest.java, src/test/java/net/dv8tion/jda/test/util/SnapshotHandler.java, src/test/resources/net/dv8tion/jda/test/restaction/ThreadCreateActionTest_testFullForumPost.json, src/test/resources/net/dv8tion/jda/test/restaction/ThreadCreateActionTest_testFullStartThread.json, src/test/resources/net/dv8tion/jda/test/restaction/ThreadCreateActionTest_testMinimalForumPost.json, src/test/resources/net/dv8tion/jda/test/restaction/ThreadCreateActionTest_testMinimalStartThread.json
Just some basic snapshot tests for creating threads.
=> Add ThreadCreateActionTest

src/test/java/net/dv8tion/jda/test/AbstractSnapshotTest.java, src/test/java/net/dv8tion/jda/test/IntegrationTest.java, src/test/java/net/dv8tion/jda/test/JDABuilderTest.java, src/test/java/net/dv8tion/jda/test/assertions/logging/LoggingAssertions.java, src/test/java/net/dv8tion/jda/test/util/SnapshotHandler.java, src/test/resources/net/dv8tion/jda/test/JDABuilderTest/testChunkingWithMissingIntent.txt, src/test/resources/net/dv8tion/jda/test/JDABuilderTest/testCreateWithMinimalIntents.txt, src/test/resources/net/dv8tion/jda/test/JDABuilderTest/testDefaultMinimal.txt
Move logging tests to declarative assertions
=> Improve assertions for logging with snapshot files

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageEditActionImpl.java
Fixes editing/deleting messages from threads using `Message`
=> Set thread ID when manipulating message objects made by webhooks

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/audio/VoiceCode.java
Closes Issue: #2853
See https://github.com/discord/discord-api-docs/pull/7582
=> Handle new voice websocket close codes

src/main/java/net/dv8tion/jda/internal/handle/VoiceServerUpdateHandler.java
=> Remove port stripping in VoiceServerUpdateHandler

build.gradle.kts, src/main/java/net/dv8tion/jda/api/exceptions/DataArrayParsingException.java, src/main/java/net/dv8tion/jda/api/exceptions/DataObjectParsingException.java, src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractEntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/utils/SerializationUtil.java, src/test/java/net/dv8tion/jda/test/data/DataArrayTest.java, src/test/java/net/dv8tion/jda/test/data/DataObjectTest.java, src/test/java/net/dv8tion/jda/test/data/DataPathTest.java, src/test/resources/net/dv8tion/jda/test/data/DataArrayTest/testUnexpectedNullException.txt, src/test/resources/net/dv8tion/jda/test/data/DataObjectTest/testMissingKeyException.txt, src/test/resources/net/dv8tion/jda/test/data/DataObjectTest/testUnexpectedNullException.txt
Closes Issue: #2900
Apparently this field can now be missing on some forum channels.
=> Handle forum channels with missing available_tags field

jitpack.yml
Tells Jitpack to use JDK 17 to build, as required by Gradle 9 ([proof of success](https://jitpack.io/io/github/freya022/JDA/7f071d279e/build.log))
=> Add `jitpack.yml` with JDK 17

src/main/java/net/dv8tion/jda/api/components/textinput/TextInput.java, src/test/java/net/dv8tion/jda/test/components/ComponentTestData.java, src/test/java/net/dv8tion/jda/test/components/LabelTest.java
Adds a shortcut to avoid unnecessary builders for TextInput.
=> Add TextInput#of shortcut

src/main/java/net/dv8tion/jda/api/components/selections/StringSelectMenu.java
Adds a missing getter in the builder
=> Add `StringSelectMenu.Builder#isRequired()`

.github/workflows/validate.yml
This allows us to use merge queues.
=> Enable merge groups

src/main/java/net/dv8tion/jda/api/components/utils/ComponentSerializer.java, src/test/java/net/dv8tion/jda/test/components/ComponentSerializerTest.java
This simplifies the serialization of a single component.
=> Add ComponentSerializer#serialize for convenience

src/main/java/net/dv8tion/jda/api/components/selections/SelectMenu.java, src/main/java/net/dv8tion/jda/api/components/textinput/TextInput.java
Optional components still follow length requirements unless empty
=> Document required components in modals are separate from range requirements

src/main/java/net/dv8tion/jda/api/components/ActionComponent.java
No components that can be inserted in modals can currently be disabled, document that.
=> Document that components in modals can't be disabled
