discord-jda/JDA

src/main/java/net/dv8tion/jda/handle/ChannelCreateHandler.java, src/main/java/net/dv8tion/jda/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/EntityBuilder.java, src/main/java/net/dv8tion/jda/handle/EventCache.java, src/main/java/net/dv8tion/jda/handle/GuildJoinHandler.java, src/main/java/net/dv8tion/jda/handle/GuildMemberAddHandler.java, src/main/java/net/dv8tion/jda/handle/GuildMemberUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/GuildMembersChunkHandler.java, src/main/java/net/dv8tion/jda/handle/GuildRoleCreateHandler.java, src/main/java/net/dv8tion/jda/handle/GuildRoleDeleteHandler.java, src/main/java/net/dv8tion/jda/handle/GuildRoleUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/MessageEmbedHandler.java, src/main/java/net/dv8tion/jda/handle/MessageReceivedHandler.java, src/main/java/net/dv8tion/jda/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/handle/ReadyHandler.java, src/main/java/net/dv8tion/jda/handle/SocketHandler.java, src/main/java/net/dv8tion/jda/handle/VoiceChangeHandler.java, src/main/java/net/dv8tion/jda/requests/WebSocketClient.java
EventCache works as a way to reorder events given to JDA from Discord. Discord will often send events out of order due to their distributed systems and "eventually consistent" mentality. JDA expects things to be in order. 
An example of this would be JDA receiving a PrivateMessage before receiving the  CreateChannel event that the private message was sent in. The Discord client doesn't create a new private channel until a message is sent, thus the message will often be received before the private channel create event is sent.
This re-orders all out of order events and handles them when JDA believes it has enough information to properly deal with the event.
=> Implemented EventCache.

src/main/java/net/dv8tion/jda/utils/InviteUtil.java
When receiving an invite (with old InviteUtil) expecting a "code" value back only if the invite is valid, and we expect the code to be the same one we sent. However, Discord replies with {"code": 10006, "message": "Unknown Invite"} on unknown invites. The old InviteUtil just looks for a "code" field as verification of an invite, whereas it should actually check that the code is not an error-code (or in the case here, that it has an associated guild).
I did some testing, and the api never returns a guild on invalid invites, including: expired invites, invites where the channel no longer exists, invites where the guild no longer exists, and invites that are not valid. Note that we _shouldn't_ check that the code we receive is the same one we send, because we get a different one in return …
=> InviteUtil Failing when trying to get Guild

build.gradle, src/examples/java/AudioExample.java, src/main/java/net/dv8tion/jda/JDA.java, src/main/java/net/dv8tion/jda/JDABuilder.java, src/main/java/net/dv8tion/jda/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/audio/AudioSendHandler.java, src/main/java/net/dv8tion/jda/entities/User.java, src/main/java/net/dv8tion/jda/managers/AccountManager.java, src/main/java/net/dv8tion/jda/managers/GuildManager.java, src/main/java/net/dv8tion/jda/requests/WebSocketClient.java
**+** Added support for muting and deafening User as an administrator using GuildManager
**+** Added support for providing pre-encoded opus audio using a AudioSendHandler
*Fixed issue where audio connections weren't closed internally when the main websocket lost connection, causing an error in JDA because JDA thought it was trying to open a second connection when it attempt to reconnect audio connections after successfully reconnecting the main websocket.
=> Release of v2.1.1

src/main/java/net/dv8tion/jda/hooks/InterfacedEventManager.java
Eliminates the need to copy the list on every event, which is an unneeded performance hit.
=> Changed the LinkedList to CopyOnWriteArrayList in InterfacedEventManager

src/main/java/net/dv8tion/jda/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/entities/impl/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/events/DisconnectEvent.java, src/main/java/net/dv8tion/jda/events/ShutdownEvent.java, src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberRoleAddEvent.java, src/main/java/net/dv8tion/jda/events/guild/member/GuildMemberRoleRemoveEvent.java, src/main/java/net/dv8tion/jda/hooks/InterfacedEventManager.java
Added list copies where necessary to prevent ConcurrentModificationExceptions and unexpected behavior due to the underlying list being modified. This should fix #75.
=> Added copies to fix ConcurrentModificationExceptions

build.gradle, src/main/java/net/dv8tion/jda/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/handle/ChannelCreateHandler.java
**Fixed issue when JDA received a CHANNEL_CREATE event for a Private channel. Due to old code that depended on now invalid return methodology, our detection of whether or not the create event was for a private channel broke. This has been fixed by using the `is_private` variable that was introduced :+1:
*Fixed possible NPE when closing an audio connection before it was done connecting.
*Fixed NPE explosion when receiving a CHANNEL_CREATE for a private channel for an unknown user. This has to do with the Relationship (friends) system, which is not yet supported. Now prints a log message instead.
=> Release of v2.1.3

src/main/java/net/dv8tion/jda/Region.java
Updated the regions according the following:
```
{"region": ["Value must be one of ('vip-us-west', 'vip-brazil', 'vip-sydney', 'singapore', 'eu-central', 'vip-us-central', 'us-central', 'vip-eu-west', 'london', 'amsterdam', 'eu-west', 'brazil', 'vip-us-south', 'us-west', 'vip-singapore', 'vip-amsterdam', 'us-south', 'vip-london', 'vip-us-east', 'vip-eu-central', 'us-east', 'sydney', 'vip-frankfurt', 'frankfurt')."]}
```
(And now to the right branch because I forgot the laws >.>)
=> Updated Regions (And to the right branch)

src/main/java/net/dv8tion/jda/core/requests/Route.java
This will fix the reported 405 response on **TextChannel#deleteMessagesById**.
If this was already fixed in your local workspace, feel free to close this pull request.
=> Switched Method for DELETE_MESSAGES to POST

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageUpdateHandler.java
One of our users received an `MESSAGE_UPDATE` dispatch with this object:
```json
{
"author": {
"bot": true,
"id": "236892566870687745",
"avatar": "27ae7496b3b30cddab2feaaed06d862a",
"username": "GitHub",
"discriminator": "0000"
},
"id": "241237427157467137",
"embeds": [...],
"channel_id": "236881236876984320"
}
```
The embeds array did contain one object which I removed for readability.
This fix should also be done in 2.x
=> Fixed bugs for rich message parsing and partial data

src/main/java/net/dv8tion/jda/client/JDAClient.java, src/main/java/net/dv8tion/jda/client/entities/UserSettings.java, src/main/java/net/dv8tion/jda/client/entities/impl/JDAClientImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/UserSettingsImpl.java, src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/OnlineStatus.java, src/main/java/net/dv8tion/jda/core/entities/Game.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/ReadyHandler.java, src/main/java/net/dv8tion/jda/core/managers/Presence.java, src/main/java/net/dv8tion/jda/core/managers/impl/PresenceImpl.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Presence is not called PresenceController because it is also holding the session presence information.
It is also not stored in `entities` because it allows setting presence fields directly.
I added UsersSettings(Impl) for the default status information saved in UserSettings.
This might well be changed in the future once we pass a proper UserSettings system.
=> First pass on Presence controller/holder

src/main/java/net/dv8tion/jda/core/Permission.java
Java doesn't really like when you cast a Permission collection to an array..
```
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.dv8tion.jda.core.Permission;
at net.dv8tion.jda.core.Permission.getRaw(Permission.java:174)
```
=> Fixed an Exception caused by casting an Array to Permission[]

src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java, src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
more options for setting timestamp (temporal, instant)
can add a blank field (and setting empty, non-null values automatically converts to a ZWSP)
sendMessage(MessageEmbed)
Please comment on this PR with any additional improvements
=> EmbedBuilder Improvements

src/main/java/net/dv8tion/jda/core/MessageHistory.java
Messages wouldn't be added if the cached history is not empty
=> Fixed bug in MessageHistory#retrievePast 

src/main/java/net/dv8tion/jda/core/requests/Route.java
This endpoint has been deprecated. Use `/channels/{channel.id}/messages/bulk-delete` instead.
https://discordapp.com/developers/docs/resources/channel#bulk-delete-messages
=> `/channels/{channel.id}/messages/bulk_delete` is deprecated

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/entities/User.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java
Adds a utility method User#getMutualGuilds() which returns a collection of guilds that are common for the User and its JDA instance.
=> Adds User#getMutualGuilds()

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
This merges #259 and #260
> __jagrosh__
> can use more temporal accessors
> edit message with embed only
> send embeds with a file
> permissions check for editing a message
> clear embeds from embedbuilder
> __Kaaz__
> A method to append to the description of an embed. 
In addition I made `description` use a `StringBuilder`
=> Embed-Related Changes / Embedbuilder; Append to description

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
I was playing around with making a Discord bot, and I got a crash when trying to grab the invite URL. I boiled it down to the fact that in the `ApplicationInfo` JSON, `icon` may be present, but still `null`. I coded up a quick fix.
=> Compensate for null icon in ApplicationInfo JSON

src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/core/handle/MessageDeleteHandler.java
Includes:
* MessageChannel#getLatestMessageId() : `String`
* MessageChannel#hasLatestMessage() : `boolean`
* ~~MessageChannel#getLatestMessage() : `RestAction<Message>`~~
It is not possible to keep track of the latest message when it is deleted as we do not provide cached messages in JDA and thus
are unable to go back in history to look for the next most recent message.
As a substitute it is always possible to simply use a `MessageHistory` instance
=> Added MessageChannel#getLatestMessageId and associated methods

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/events/ExceptionEvent.java, src/main/java/net/dv8tion/jda/core/handle/EventCache.java, src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/core/requests/GuildLock.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/Requester.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/ClientRateLimiter.java
This experiment will improve the JDA Requester system by adding a new Requester pool that will be used to execute request callbacks in an additional thread to counter possible deadlocks.
In addition I added new RestAction operations and documentation:
- `completeAfter(long, TimeUnit)`
- `submitAfter(long, TimeUnit [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit, Consumer<T> [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit, Consumer<T>, Consumer<Throwable> [, ScheduledExecutorService])`
More information on how these work can be found in the documentation.
> Note: This can still be changed.
=> Added new RestAction operations for planned execution and async Request callback execution

src/main/java/net/dv8tion/jda/bot/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/client/entities/impl/AuthorizedApplicationImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/CallImpl.java, src/main/java/net/dv8tion/jda/client/entities/impl/JDAClientImpl.java, src/main/java/net/dv8tion/jda/client/handle/CallCreateHandler.java, src/main/java/net/dv8tion/jda/client/handle/CallUpdateHandler.java, src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/ISnowflake.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/core/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/events/guild/UnavailableGuildJoinedEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageDeleteEvent.java, src/main/java/net/dv8tion/jda/core/events/message/MessageEmbedEvent.java, src/main/java/net/dv8tion/jda/core/handle/MessageBulkDeleteHandler.java, src/main/java/net/dv8tion/jda/core/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/core/utils/WidgetUtil.java
- Use `Long.toUnsignedString` to ensure we only return Strings without a leading `'-' `
- Add `MiscUtil.parseSnwoflake` to have a custom `NumberFormatException` to specify we are talking about a snowflake value
Should we add documentation for this exception, too?
=> Consider Snowflake IDs as unsigned

src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java
If the member has a nickname the raw id should be <@!{id}>, since this is what will be returned by the raw content of a message.
=> Updated getAsMention() for members.

src/main/java/net/dv8tion/jda/core/Permission.java, src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/utils/MiscUtil.java
Flipped the if/else in `parseSnowflake` to fix an IllegalStateException trying to use `parseUnsignedLong` on a string starting with `-`
=> Fixed an error in parseSnowflake and improved ErrorResponseException message

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
also added TextChannel#clearReactionsById(long messageId) as a default method
copied over the docs and changed relevant parts
also removed a `@throws IllegalArgumentException` from Message#clearReactions since it doesn't take any arguments
=> Added TextChannel#clearReactionsById

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Fixed bug where packets sent by the WS ratelimit system were sent before IDENTIFY due to racecondition.
=> Fix WS Sending race condition.

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java
Before users that did `sendMessage("Hello")` would essentially use the format method which was unintentional
Note: This will cause issues for people that were using the format methods but those cannot be avoided.
=> Renamed formatting send/edit message methods to avoid conflicting calls.

src/main/java/net/dv8tion/jda/core/entities/Emote.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Bots are now able to use non-managed emotes outside of the emote's guild
=> Fixed Emote#canInteract logic for bot accounts

src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
Makes AudioConnection#ready() once again be called after the AudioWS is actually connected.
=> Fixes audio speedup as shown by issue #357

src/main/java/net/dv8tion/jda/bot/entities/impl/ShardManagerImpl.java
While looking at the additions, I realized that the ShardManager#getGuildById method can be more efficient.
Rather than finding the snowflake in a combined collection, you could calculate the shard id of the Guild, get the shard and obtain the guild from there instead. This upgrades the method from O(n) to O(1).
=> Upgrade efficiency of ShardManager#getGuildById

src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/AuditableRestAction.java
Note that I made TextChannel#deleteMessages only return RestAction according to hammerandchisel/discord-api-docs#265
And I did the same for TextChannel#clearReactionsById due to there not being an action type I suspect there not to be one in the near future
=> Update of audit log reasons / allow utf-8

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
Fixes #380 
The issue of the rogue memory leak is this line:
```java
keepAlivePool.remove(keepAliveRunnable);
```
Because the specific executor service adapts the `Runnable` to a different class, it's never contained in the internal queue datastructure, (as in `Collection.indexOf()`).
Lot of sad times, since it's never removed.
=> Fix cleaning up of the keepAliveRunnable

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/entities/IFakeable.java, src/main/java/net/dv8tion/jda/core/entities/User.java, src/main/java/net/dv8tion/jda/core/entities/impl/MessageImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/UserImpl.java, src/main/java/net/dv8tion/jda/core/managers/GuildController.java, src/main/java/net/dv8tion/jda/core/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Cleanup for some documentation and removal of deprecated methods.
JDABuilder will no longer throw an exception for `useSharding(0, 1)` as it is a valid configuration. (tested)
The exceptions thrown by JDABuilder are now documented and no longer simple RuntimeExceptions!
=> Release for JDA 3.2 / finalization

src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/requests/Response.java
New format would look like `[ErrorResponseException] -1: java.net.SocketTimeoutException`
=> Use exception name as response message on requester exceptions

src/main/java/net/dv8tion/jda/core/MessageBuilder.java
You can `/nick everyone`, and the default `stripMentions` will "strip" a mention of yourself to become an unfiltered `@everyone`.
This PR is to fix that. I've locally tested that it works, and written a note to future editors of those functions so that people think twice before rewriting it.
=> Reorder stripping of mentions

src/main/java/net/dv8tion/jda/core/managers/WebhookManagerUpdatable.java
Looks like bug in WebhookManagerUpdatable, which trying to compare channels instead of their guilds
=> WebhookManagerUpdatable Guild check fix

README.md, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/requests/SessionReconnectQueue.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
This can be used to stop sessions from reconnecting simultaneously.
It will prevent them from sending IDENTIFY payloads on reconnect until they come up in the queue.
=> Adding SessionReconnectQueue

src/main/java/net/dv8tion/jda/client/handle/RelationshipRemoveHandler.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/EventCache.java, src/main/java/net/dv8tion/jda/core/handle/GuildBanHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildMemberRemoveHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildRoleDeleteHandler.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
- Clear event cache for removed entities
- Do not remove self from members to ensure safety of permission checks
=> Fixed handling of GuildMemberRemove and added cleanup to event cache

src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java
_DIsclaimer_ not yet tested.
Is there a reason we don't `clear()` this one, but other maps are cleared? (e.g. `opusDecoders`)
=> Do not retain the audio managers after shutdown

src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/ShardedRateLimiter.java, src/main/java/net/dv8tion/jda/core/entities/Category.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/requests/Requester.java, src/main/java/net/dv8tion/jda/core/requests/ratelimit/BotRateLimiter.java
This change will not require users to add a ShardedRateLimiter to their JDABuilder if they have already been using the same builder for all shards.
=> Adding ShardedRateLimiter to keep track of global REST rate limit

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java
These are triggered when a message contains something like <#111111111111111111111111111111111>
```
java.lang.NumberFormatException: For input string: "111111111111111111111111111111111"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Long.parseLong(Long.java:592)
at java.lang.Long.parseLong(Long.java:631)
at net.dv8tion.jda.core.entities.EntityBuilder.createMessage(EntityBuilder.java:921)
at net.dv8tion.jda.core.entities.EntityBuilder.createMessage(EntityBuilder.java:749)
at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:61)
at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37) …
```
=> Handle NumberFormatException when parsing channel mentions

src/main/java/net/dv8tion/jda/core/events/message/MessageReceivedEvent.java, src/main/java/net/dv8tion/jda/core/events/message/guild/GuildMessageReceivedEvent.java
Need opinion on Docs:
- Should I keep the `@see` stuff?
- Should I say "received Message" or "sent Message" throughout the docs?
- Should I link other classes more frequently? (currently only when needed and not in return statement)
- Should I horizontally align the `@return` and `@see` statements?
=> Added isWebhookMessage() and docs to (Guild)MessageReceivedEvent

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/requests/Requester.java
Ever since we switched to okhttp we got reports for SocketTimeoutException.
This should retry once on every timeout. 
For users that dislike this it is possible to disable the retry logic using JDABuilder#setRequestTimeoutRetry(boolean) and the respective version in JDA.
=> Allow requester to retry once on SocketTimeoutException

src/main/java/net/dv8tion/jda/webhook/WebhookClientBuilder.java
This adds a constructor to `WebhookClientBuilder` which takes the URL for the webhook (as opposed to the id and token separately.)
Tested for the following URLs:
```
https://discordapp.com/api/webhooks/370264727500095498/token
http://discordapp.com/api/webhooks/370264727500095498/token
https://discordapp.com/api/6/webhooks/370264727500095498/token
https://canary.discordapp.com/api/webhooks/370264727500095498/token
https://discordapp.com/api/webhooks/370264727500095498/token/slack
```
=> Added WebhookClientBuilder(String) constructor

src/main/java/net/dv8tion/jda/core/JDA.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/VoiceStateUpdateHandler.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/core/utils/cache/CacheView.java
This will allow for better performance on checking how many active audio connections are present in a JDA instance:
```java
JDA api; // = ....
MessageChannel channel; // = ....
CacheView<AudioManager> cache = api.getAudioManagerCache();
channel.sendMessageFormat("Currently connected to **%d** channels!", cache.stream().filter(m -> m.isConnected()).count()).queue();
```
=> Made audio manager cache accessible from JDA instances

src/main/java/net/dv8tion/jda/core/utils/cache/MemberCacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/SnowflakeCacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/AbstractCacheView.java, src/main/java/net/dv8tion/jda/core/utils/cache/impl/SortedSnowflakeCacheView.java
This should fix occasional `ConcurrentModificationException` appearances when using a stream
=> Fixed issues with cache view iterators not being thread-safe

src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java
GuildUpdateExplicitContentLevelEvent was missing from the ListenerAdapter and this PR adds it.
=> added GuildUpdateExplicitContentLevelEvent to ListenerAdapter

.gitattributes, src/main/java/net/dv8tion/jda/core/events/guild/voice/GuildVoiceLeaveEvent.java, src/main/java/net/dv8tion/jda/core/events/guild/voice/GuildVoiceMoveEvent.java, src/main/java/net/dv8tion/jda/core/events/guild/voice/GuildVoiceUpdateEvent.java, src/main/java/net/dv8tion/jda/core/hooks/ListenerAdapter.java
Allows to do:
```java
public class MyListener extends ListenerAdapter {
@Override
public void onGuildVoiceUpdate(GuildVoiceUpdateEvent event) {
// do stuff when user leaves channel
}
}
```
instead of:
```java
public class MyListener extends ListenerAdapter {
@Override
public void onGuildVoiceLeave(GuildVoiceLeaveEvent event) {
onGuildVoiceUpdate(event.getChannelLeft());
}
@Override
public void onGuildVoiceMove(GuildVoiceMoveEvent event) { …
```
=> Added GuildVoiceUpdateEvent to combine leave and move

src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java
There's a bug here where the DefaultShardManager is erroneously passing the `enableBulkDeleteSplitting` field as a parameter for enabling shutdown hooks. Instead the value should always be false, since the DefaultShardManager manages the shutdown hook itself.
=> Use proper value for shutdown hooks of managed shards

src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java
This is a rare race-condition that could cause deadlocks.
1. AudioConnection ReadyThread calls AudioWebSocket#close
2. AudioManager#closeAudioConnection calls AudioConnection#close
3. AudioWebSocket waits to acquire AudioManager.CONNECTION_LOCK (held by AudioManager)
4. AudioManager waits to acquire AudioWebSocket method lock (held by AudioConnection ReadyThread)
5. Deadlock due to 2 locks waiting to acquire each other
By removing the AudioWebSocket method …
=> Hotfix deadlock in audio connections

src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Fixes #414 
This doesn't really fix anything imo but discord really doesn't want to change this for some reason.
I expected this to change when a dev actually told me it will change but that was half a year ago so I have to take things in my own hands and go with this.
=> "Fixed" permissions

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
I feel like this lock fits better than a semaphore.
=> Replaced Semaphore with (superior) ReentrantLock

src/main/java/net/dv8tion/jda/core/entities/Channel.java, src/main/java/net/dv8tion/jda/core/entities/impl/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/core/events/http/HttpRequestEvent.java, src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/Response.java, src/main/java/net/dv8tion/jda/core/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/core/utils/IOFunction.java
Allow fallback for error response with non-json content again.
This fixes a small regression from 3.5.1 where the response is not parsed for error responses that aren't json. Additionally this removes an unused JSONObject in PermissionOverrideAction which isn't present for this endpoint and causes issues.
=> Fallback body parsing for http response

src/main/java/net/dv8tion/jda/core/EmbedBuilder.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Member.java, src/main/java/net/dv8tion/jda/core/entities/MessageEmbed.java, src/main/java/net/dv8tion/jda/core/entities/Role.java, src/main/java/net/dv8tion/jda/core/entities/impl/MemberImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java, src/main/java/net/dv8tion/jda/core/events/role/update/RoleUpdateColorEvent.java, src/main/java/net/dv8tion/jda/core/handle/GuildRoleUpdateHandler.java, src/main/java/net/dv8tion/jda/core/requests/restaction/GuildAction.java
This replaces all use of `java.awt.Color` with raw int primitives.
You may still use the old front-facing api for the color class, we just extended it to also allow access to the raw value. The new default is defined as constant in `Role.DEFAULT_COLOR_RAW` to keep consistency between role colors and embed colors.
The default is specified as `0x1FFFFFFF` due to the `Color(int)` constructors behaviour.
If we used `-1` then `new Color(0xFFFFFF)` would yield `-1` …
=> Store color with raw RGB value

src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/bot/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/bot/sharding/ShardManager.java
This PR adds a feature to the DefaultShardManager.
This will allow the ShardManager and ShardManagerBuilder to be provided with a function which provides listeners based on shard id.
This is helpful when the user wishes for an approach where each shard gets it's own listener object of a certain kind, instead of having a single central listener object of a certain kind for all shards.
Input is welcome on how to write a convenience method on how to handle …
=> Add sharded listener provider

src/main/java/net/dv8tion/jda/core/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildMembersChunkHandler.java
When the bot leaves a guild it probably won't get any other chunks.
Once the bot joins we shouldn't still have the old expected count.
=> Clear expected member chunks on guild delete

src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java
I noticed that my bot would sometimes not join a voice channel nor would it throw an exception and after investigating and testing I found out that the Move Members permission was causing this and that is what led me to this line of code.
As stated in the title the Move Members permission does not grant a user access to a channel only the Connect permission does.
**Note:** I have not tested this yet.
=> Permission#VOICE_MOVE_OTHERS does not grant access to a voice channel

src/main/java/net/dv8tion/jda/core/managers/RoleManager.java
Now we properly initialize already present permissions and do better checks.
=> Fixed issues with permission management in RoleManager

src/main/java/net/dv8tion/jda/core/entities/IMentionable.java, src/main/java/net/dv8tion/jda/core/entities/impl/RoleImpl.java
This PR changes/fixes the behavior of `Role#getAsMention()` when called on the public role (`@everyone`).
Previously, it used the default Role mention pattern (`<@&ID>`) even for the public role. Now it returns the literal String `"@everyone"` in that special case instead.
=> Fixing Role#getAsMention() for public Role

src/main/java/net/dv8tion/jda/core/audit/AuditLogEntry.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Webhook.java, src/main/java/net/dv8tion/jda/core/entities/impl/WebhookImpl.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java
This PR fixes an issue where JDA required the user_id field in audit log entries to be non-null, despite Discord allowing null values for items such as webhook self-deletion. This PR also adds a getWebhook() method to AuditLogEntry to get a partial Webhook object that are the target of some Audit Log Entries. This fulfills #662.
=> Allow null user_id and provide partial Webhooks

src/main/java/net/dv8tion/jda/core/Region.java
This PR adds the flag unicode for each Region, as well as a Region#getEmoji() method to retrieve said flag. Every voice region is represented by a flag within Discord's client:
(Some flags are from past versions of the client, as available voice regions change occasionally). Similar to how JDA offers the in-client name for Region (and other enums, like Permission), this would allow JDA to also offer the in-client 'graphic' for regions. The use case is similar …
=> Add unicode flag emoji for each Region

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
Default behaviour is still retrieving deprecated regions, must pass
false to retrieveRegions(boolean) in order to exclude them.
=> Add option to exclude deprecated voice regions

src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Since the `%s` format specifier already does toString conversion, it's only wasteful to call toString before handing it over to String.format.
Let me know what you think.
=> Don't call toString() eagerly on arguments to format()

src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Invite.java, src/main/java/net/dv8tion/jda/core/entities/impl/InviteImpl.java
This PR fulfills #666 by adding an additional Invite.resolve method to allow getting counts and verification level from invites.
Still needed at this time: docs, possibly exceptions if the resolved invite is not one that contains counts.
=> Additional invite info

README.md
The jcenter link to the dependency was wrong, as it is for okhttp (2) and JDA uses okhttp 3.8.1 which is okhttp3.
=> Change jcenter link for okhttp3 dependency

src/main/java/net/dv8tion/jda/client/managers/EmoteManager.java, src/main/java/net/dv8tion/jda/core/entities/Emote.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/ListedEmote.java, src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java, src/main/java/net/dv8tion/jda/core/requests/Route.java
Discord actually also lists the emote creator this way and its required
when disabling emote cache manually (see experimental/guild-setup)
=> Add support to retrieve emotes via RestAction access

src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java
Since the `guild` field is now an `UpstreamReference`, directly comparing it to a Guild object results in an error:
```java
java.lang.IllegalArgumentException: Provided Member is not from the Guild that this TextChannel is part of.
at net.dv8tion.jda.core.entities.impl.TextChannelImpl.canTalk(TextChannelImpl.java:182)
at net.dv8tion.jda.core.entities.impl.TextChannelImpl.canTalk(TextChannelImpl.java:175)
```
=> Fix IllegalArgumentException on TextChannel#canTalk()

build.gradle, src/main/java/net/dv8tion/jda/client/entities/impl/GroupImpl.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/core/entities/TextChannel.java, src/main/java/net/dv8tion/jda/core/entities/impl/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/core/entities/impl/TextChannelImpl.java, src/main/java/net/dv8tion/jda/core/requests/Route.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java
This makes deleting messages a lot easier than it was before.
Example:
```java
List<Message> messages = new LinkedList<>();
AtomicInteger count = new AtomicInteger(0);
event.getChannel().getIterableHistory().forEachAsync((msg) -> {
messages.add(msg);
return count.incrementAndGet() < 1000;
}).thenRunAsync(() -> {
for (RequestFuture<Void> future : event.getChannel().purgeMessages(messages))
{
future.exceptionally((t) -> {
t.printStackTrace();
return null;
});
}
});
```
=> Add purgeMessages methods for convenient message deletions

src/main/java/net/dv8tion/jda/core/entities/Emote.java, src/main/java/net/dv8tion/jda/core/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/core/entities/impl/EmoteImpl.java, src/main/java/net/dv8tion/jda/core/handle/GuildEmojisUpdateHandler.java, src/main/java/net/dv8tion/jda/core/handle/GuildRoleDeleteHandler.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
Although I am not a fan of having a release that adds a deprecated
method, this is probably for the better
Now it should be abundantly clear that this has nothing to do with the size of the list.
=> Replace Emote#hasRoles to avoid ambiguity

README.md, build.gradle, src/examples/java/MessageListenerExample.java, src/main/java/net/dv8tion/jda/annotations/Incubating.java, src/main/java/net/dv8tion/jda/core/JDABuilder.java
The documentation for retrieving a token on `AccountType.CLIENT` is no longer accurate and will not work. Since discord only officially allows `AccountType.BOT` and we recommend not using anything else I've added new default overloads to the constructor and marked the old version as incubating in the case discord actually comes along and asks us to remove it.
=> Update documentation of JDABuilder and add new constructor overloads

src/main/java/net/dv8tion/jda/core/JDAInfo.java, src/main/java/net/dv8tion/jda/core/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/core/audio/AudioPacket.java, src/main/java/net/dv8tion/jda/core/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/core/audio/KeepAliveThreadFactory.java, src/main/java/net/dv8tion/jda/core/audio/hooks/ConnectionStatus.java, src/main/java/net/dv8tion/jda/core/entities/impl/JDAImpl.java, src/main/java/net/dv8tion/jda/core/handle/VoiceServerUpdateHandler.java, src/main/java/net/dv8tion/jda/core/managers/impl/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
Now AudioWebSocket is a subclass of AudioConnection and they can freely share fields.
=> Make AudioWebSocket a subordinate class

src/main/java/net/dv8tion/jda/core/managers/PermOverrideManager.java
Resolves #767, please see that issue for details.
=> Fix granting / denying permissions

src/main/java/net/dv8tion/jda/core/requests/CallbackContext.java, src/main/java/net/dv8tion/jda/core/requests/Request.java, src/main/java/net/dv8tion/jda/core/requests/RestAction.java
```java
channel.sendMessage("hello there").queue( msg -> {
msg.editMessage("general kenobi").queue(); // ok
msg.delete().complete(); // throws
});
```
This way we prevent any deadlocks from occurring in a fixed-pool causing everything to halt for a shard (or all shards if one shared pool is used)
=> Prevent using complete() in callbacks

src/main/java/net/dv8tion/jda/core/entities/Guild.java, src/main/java/net/dv8tion/jda/core/entities/impl/GuildImpl.java
Convenience method to retrieve list of channels in a guild. The returned list is ordered the same way the client orders channels.
=> Add Guild#getChannels for convenience

src/main/java/net/dv8tion/jda/core/handle/VoiceStateUpdateHandler.java
Closes Issue: #805
Fixes issue where we were firing VoiceChannel Join/Move/Leave events before updating VoiceState (mute, deaf, guildMute, guildDeaf, etc).
=> Reordered VoiceState changes. Fixes #805

src/main/java/net/dv8tion/jda/core/requests/WebSocketClient.java
As per Minn's recommendation.
Closes the websocket when receiving malformed data from Discord, allowing JDA to potentially resume.
Not tested in the wild yet.
=> Close socket on malformed zip data

src/main/java/net/dv8tion/jda/core/requests/restaction/ChannelAction.java
Closes Issue: #818 
This PR will allow users to set the raw position value used when creating a new (Guild-)Channel.
While the actual change was not yet made on Discords end, this PR is on hold.
It will probably also need the doc addition about what happens when a position is set that already exists on another Channel with same Parent (including null parent). But since that depends on testing, it also has to wait until this feature is allowed on Discords end.
=> Add ChannelAction#setPosition(Integer)

src/main/java/net/dv8tion/jda/core/MessageBuilder.java
Adds `MessageBuilder#appendCodeLine`. Useful when a user discovers `appendCodeBlock`
=> Added appendCodeLine(CharSequence text)

src/main/java/net/dv8tion/jda/core/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/core/utils/PermissionUtil.java
This fixes a small issue with some permission overrides. If a permission override has ADMINISTRATOR set we would act as if it means all permissions are granted, however ADMINISTRATOR makes no difference on channel overrides.
=> Don't check admin on permission overrides

src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/MessagePaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/core/requests/restaction/pagination/ReactionPaginationAction.java
This allows skipping pages when using a `PaginationAction`
```java
public MessagePaginationAction getOlderThan(MessageChannel channel, long time) {
final long timestamp = TimeUtil.getDiscordTimestamp(time);
final MessagePaginationAction paginator = channel.getIterableHistory();
return paginator.skipTo(timestamp);
}
getOlderThan(channel, System.currentTimeMillis() - TimeUnit.DAYS.toMillis(14))
.forEachAsync((message) -> {
boolean empty = message.getContentRaw().isEmpty();
if (!empty)
System.out.printf("%#s%n", message); // means: print display content
return !empty; // means: continue if not empty
});
```
=> Add skipTo option for PaginationAction

src/main/java/net/dv8tion/jda/core/entities/ISnowflake.java, src/main/java/net/dv8tion/jda/core/entities/Member.java, src/main/java/net/dv8tion/jda/core/entities/Message.java, src/main/java/net/dv8tion/jda/core/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/core/events/DisconnectEvent.java, src/main/java/net/dv8tion/jda/core/events/ShutdownEvent.java, src/main/java/net/dv8tion/jda/core/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/core/utils/TimeUtil.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
More consistent names for getters to increase usability. This also makes auto-complete a little better since `getTime` will now display all timestamp getters.
=> Make names consistent for timestamp getters

src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
Add some more details to the warning message to allow better diagnosis of issues.
```
GuildSetupContr WARN   Accumulating suspicious amounts of cached events during guild setup, something might be wrong. Cached: 2000 Members: 0/44666 Status: CHUNKING GuildId: 81384788765712384
GuildSetupContr WARN   Accumulating suspicious amounts of cached events during guild setup, something might be wrong. Cached: 3000 Members: 0/44666 Status: CHUNKING GuildId: 81384788765712384
GuildSetupContr WARN   Accumulating suspicious amounts of cached events during guild setup, something might be wrong. Cached: 4000 Members: 0/44666 Status: CHUNKING GuildId: 81384788765712384
GuildSetupContr WARN   Accumulating …
```
=> Improve warning message for unloaded guilds

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
This will allow adding reactions with code-point representations like `U+1F44D`.
The conversion is quite simple, we first parse each code-point and then split them into
the respective characters. This is possible because custom emote names cannot contain `U+` making this a valid conversion without breaking existing code.
=> Allow adding reactions with code-point representation

src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
This prevents users from adding to the send queue while waiting for a reconnect.
It doesn't make sense to send 100 presence updates right on startup once the queue reaches the shard.
=> Don't send presence update when reconnect is queued

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Since these can be configured through the JDABuilder anyway
we should allow users to access them from the JDA instances
as well. This opens up a few possibilities for abstractions
within JDA as well.
=> Provide access to JDA pools

src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java
Adds 2 methods to consume and convert streams on a CacheView without exposing the possibility to deadlock.
```java
CacheView<User> view = jda.getUserCache(); 
long shortNames = view.applyStream(
stream -> stream.filter(it -> 
it.getName().length() < 4).count()); 
System.out.println(shortNames + " users with less than 4 characters in their name"); 
```
=> Add methods to use stream in secured environment

src/main/java/net/dv8tion/jda/core/entities/Channel.java
[Channel#getPositionRaw()](/DV8FromTheWorld/JDA/blob/development/src/main/java/net/dv8tion/jda/core/entities/Channel.java#L86-L96) mentions Roles in its description, while it actually is in the Channels-class, which (obviously) is about the channels.
This PR replaces the mentions of roles/role with channels/channel
=> Fixing missspelling of "Channel" as "Role"

src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Fixed a typo in `net.dv8tion.jda.bot.sharding.ShardManager`'s documentation by replacing the word "my" to "may" in the interface javadoc.
=> Fixed a javadoc typo in ShardManager

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Make names of ping getters more representative of their meaning and create new method to retrieve
RestAction ping more easily.
Waiting for #852 to be completed.
```java
MessageChannel channel = event.getChannel();
RestAction<Long> action = event.getJDA().getRestPing();
action.queue( (time) -> channel.sendMessageFormat("Ping %d ms", time).queue() );
```
=> Add getRestPing and rename getPing to getGatewayPing

src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java
Commit 1ba4536faa1fe4f22c1540f68a1089b2130f4a47 broke `PermissionOverrideAction` by accidentally making it a non-auditable `RestAction`.
This PR reverts that.
=> Fixed a refactoring issue with PermissionOverride not being Auditable.

build.gradle
This makes the name for the JDA dependency a little more consistent and makes it not depend on the jar name.
```java
module com.example.bot {
requires net.dv8tion.jda;
requires slf4j.api;
}
```
=> Add Automatic-Module-Name for jigsaw

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java
Apparently discord uses the same rate-limit bucket here but not for getting the self user. Just another inconsistency in the API.
=> Use the same route for removing own reaction

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
This wasn't handled in the same way, an embed created with the builder should be valid for sending.
=> Consistent handling of isEmpty logic in embeds

src/main/java/net/dv8tion/jda/api/utils/cache/CacheView.java, src/main/java/net/dv8tion/jda/internal/utils/cache/ShardCacheViewImpl.java, src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Adds proper boundaries to methods where producers/consumers are desired.
For anyone unfamiliar with the rule on how to apply these properly:
**PECS**: **P**roducer **E**xtends, **C**onsumer **S**uper
```java
Procedure<Object> contravariant = (x) -> {
System.out.println(x);
return true;
};
view.forEachAsync(contravariant);
```
=> Add correct boundaries to api methods in CacheView

src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java
Greatly simplifies retrieving a bunch of elements until a certain condition is met.
```java
private static CompletableFuture<List<Message>> getMessagesBetween(long startId, long endId, MessageChannel channel) {
return channel.getIterableHistory()
.cache(false).skipTo(endId)
.takeUntilAsync(it -> Long.compareUnsigned(it.getIdLong(), startId) < 0);
}
```
=> Add takeUntilAsync

README.md, build.gradle
It seems like OkHTTP 3.13.0 is not coming any closer to being released, this is a solution that would work for us if we decide to just give up on waiting.
=> Use OkHTTP3 snapshot

build.gradle.kts, javadoc-options.txt
With these options the javadoc will properly link to external references such as JDK or OkHTTP docs.
=> Add links to external references in javadoc

README.md
FredBoat has moved to use JDA by proxy. It doesn't actually contain JDA in its classpath, making it a misleading example.
Also moved a notice closer to the text it actually refers to.
=> Remove FredBoat as an example

build.gradle.kts
It is recommended to use the `-release` flag in javac 9+ for specifying the target compatibility.
=> Add release flag to compiler arguments when available

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
We should not swallow rejected executions of the startup worker in DefaultShardManager.
=> Don't catch rejection of worker schedule

src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/api/entities/IMentionable.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/entities/Role.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java
If you can mention it, it has an id.
Makes mentionable entities snowflake entities. All of them implement both anyway.
=> Make IMentionable extend ISnowflake

src/main/java/net/dv8tion/jda/internal/utils/ChainedClosableIterator.java, src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Lists produced by this iterator had duplicates due to the fact it did not check for elements appearing again. This is problematic when using something like `ShardManager#getUsers()`.
This has been resolved by adding a `HashSet` to de-duplicate the iterated elements, adding more complexity to the iterator but allowing the resulting iteration to be duplicate-free. Luckily we can re-use the internal `Set` used for de-duplication again in `CacheView#asSet`.
This only affected `UnifiedCacheView` implementations and is a regression from an earlier change in v4. Since v3 did not receive the same change it is still unaffected.
=> Ensure the ChainedClosableIterator does not produce duplicates

src/examples/java/AudioEchoExample.java, src/main/java/net/dv8tion/jda/api/audio/AudioSendHandler.java, src/main/java/net/dv8tion/jda/api/audio/factory/IPacketProvider.java, src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java, src/main/java/net/dv8tion/jda/internal/audio/Decoder.java
This change allows send handlers to re-use a single buffer for all packets.
```java
public class AudioSender implements AudioSendHandler {
private AudioPlayer player;
private AudioFrame frame;
private ByteBuffer buffer = ByteBuffer.allocate(1024);
public AudioSender(AudioPlayer player) {
this.player = player;
}
@Override
public boolean canProvide() {
frame = player.provide();
return frame != null;
}
@Override
public ByteBuffer provide20MsAudio() {
frame.getData(buffer.array(), frame.getDataLength()); // lavaplayer still had the old broken behavior where it used offset as length in arraycopy
buffer.position(0);
buffer.limit(frame.getDataLength());
return buffer;
}
@Override
public boolean …
```
=> Use ByteBuffer for sending audio

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
It makes no sense to receive an attachment that has a null url.
=> Enforce non-null attachment urls

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Removes old overloads of `sendFile` that allow adding a message instance. This is no longer needed since you can do the same by using `MessageAction` instead.
This is breaking in the sense that people who still use it will have to change to this "new" (this has been around since like 3.4.0) code.
```java
channel.sendFile(file, name, message).queue();
```
> Legacy code
```java
channel.sendMessage(message).addFile(file, name).queue();
```
> Current approach
=> Remove old sendFile overloads in favor of better maintainability

build.gradle.kts, src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/test/java/MarkdownTest.java
Closes Issue: #838 
Add dedicated class for markdown sanitizing. This improves handling of `getContentStripped()` while also externalizing its logic, something I wanted to do for v4.
```java
MarkdownSanitizer m = new MarkdownSanitizer();
m.withIgnored(MarkdownSanitizer.MONO | MarkdownSanitizer.UNDERLINE);
m.withStrategy(MarkdownSanitizer.SanitizationStrategy.ESCAPE);
String result = m.compute("Hello **world**!");
System.out.println(result);
```
```
Hello \**world\**!
```
=> Add MarkdownSanitizer 

src/main/java/net/dv8tion/jda/api/managers/AudioManager.java, src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
This can be helpful for song transitions that take longer than 200ms, or buffered systems.
The delay can be specified in ms but will be aligned with the frame length (20ms) through integer division (no rest). It is set to a minimum of 10 frames = 200ms.
=> Add ability to set speaking delay in audio manager

src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java
If we know that the guild is waiting for member chunks we should just try asking for them again.
=> Forcibly request chunks again when caching too many events

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
This removes all blocking methods from `Message.Attachment` in favor of async variants. Downloading files should not happen on the event thread at any point in time.
- `download()` -> `downloadToFile()`
- `getAsIcon()` -> `retrieveAsIcon()`
=> Improve attachment retrieval by only offering async variants

src/main/java/net/dv8tion/jda/api/entities/ChannelType.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Now we don't throw on unknown channel types and we handle the new "news" type. By handle I mean we literally just alias it to text type since there is basically no difference to speak of.
For more info go to discordapp/discord-api-docs#881
=> Handle news channels

src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/AuditLogPaginationAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/MessagePaginationAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/PaginationAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/MessagePaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Previously it was possible that entities of the current chunk
would be lost when the iteration of forEachAsync ends.
This means repeated uses of forEachRemainingAsync could
result in skipping significant sections of the data set.
I have also removed silly attempts of trying to make the class thread-safe that didn't actually make the class thread-safe to begin with. Instead I have added a note about thread-safety to the class documentation.
=> Avoid losing entities skipped by forEachAsync iteration

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Closes Issue: #965 
EntityBuilder#createInvite now parses the username JSON instead of passing the list of JSON strings to the constructor of Invite.Group.
=> Invite.Group#getUsers now returns usernames

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
Closes Issue: #968
Adds a new method `getHistoryFromBeginning(int limit)` to the MessageChannel Interface that simply returns `getHistoryAfter(0L, limit)`. As @DV8FromTheWorld explained in the Issue mentioned above, most people don't know that this is the way to get the beginning history of a MessageChannel so I added it to make it easier for Users.
As I did that, I also made some minor fixes to the JavaDoc of some other functions in the Interface when I was at it (I spoke to @MinnDevelopment before doing so).
(It's my first real PR ever, I hope it's fine. I was spending more time in reading your guidelines and setting up this PR than writing the Code and the Documentation for it. If there is anything wrong, just tell me, I'll try to fix it asap.)
=> Add method to easily get the beginning history of a MessageChannel

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Without this the zip decompression will read the first few bytes and could potentially break the context of the content. This way we make sure to keep the actual content.
=> Use mark to get correct content of http response in getBody

src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/BufferedRequestBody.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Closes Issue: #959 
When a request is retried we already have the stream exhausted and upload an empty file is sent
on retries instead. This is fixed by temporarily storing the data in a buffer.
=> Use buffer for file uploads to fix duplicated requests

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/api/utils/AttachmentOption.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Adds options to `addFile` overloads allowing to specify how the attachments should be used.
Currently the only option is `SPOILER` which marks the attachment as a spoiler. This is best for maintainability in the future, compared to simply adding a boolean flag.
```java
channel.sendMessage("SPOILER FOR XYZ:")
.addFile(image, AttachmentOption.SPOILER)
.queue();
```
=> Add attachment options to apply to files

src/main/java/net/dv8tion/jda/api/audio/AudioReceiveHandler.java, src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java
Closes Issue: #967
Adds support for filtering what users are included in in the packet created for `handleCombinedAudio(CombinedAudio)`
Example: Only include audio from users that are not bots.
```
public MyHandler implements AudioReceiveHandler {
canReceiveCombined() {
return true;
}
handleCombinedAudio(CombinedAudio audio) {
//Handle audio
}
includeUserInCombinedAudio(User user) {
return !user.isBot();
}
}
```
=> AudioReceiveHandler#includeUserInCombinedAudio

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
SocketException is thrown when opening or accessing a socket fails. This can be caused by a broken connection or bad firewall. We should retry once when this happens.
=> Retry requests on SocketException

src/main/java/net/dv8tion/jda/internal/utils/JDALogger.java
Closes Issue: #580 
This pull request replaces the detection system in `JDALogger`, which currently is only able to detect an SLF4J provider via the SLF4J `1.7.x` `StaticLoggerBinder` mechanism with one which is able to detect both providers with the current mechanism as well as new `ServiceLoader`-based providers from SLF4J `1.8.x`.
This enables JDA to function correctly with any newer SLF4J API and provider version which may be present at runtime, even if the version it is compiled against is `1.7.x`. (`slf4j-api` has [always been binary compatible](https://www.slf4j.org/faq.html#compatibility) to previous versions, also see [this issue](https://github.com/DV8FromTheWorld/JDA/issues/580#issuecomment-479213460) …
=> Modified JDALogger SLF4J detection to be able to detect both pre-1.8.x and 1.8.x+ providers

src/main/java/net/dv8tion/jda/api/audio/hooks/ConnectionStatus.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
Since voice kick was not a thing before, we were not aware that we can be removed from a channel by a moderator. Due to the auto-reconnect logic we then simply reconnect right away. This is changed by this PR which will not attempt to reconnect if we were kicked from the channel.
=> Add voice kick handling that stops JDA from reconnecting

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java
This adds a consistent way to retrieve a guild-channel by its ID. Otherwise we have to always update multiple switches for this behavior when a new type is introduced.
**Before**
```java
@Nullable
public GuildChannel getChannel(@Nonnull JDA api)
{
Checks.notNull(api, "JDA");
GuildChannel channel;
switch (getChannelType())
{
case TEXT:
return api.getTextChannelById(channelId);
case CATEGORY:
return api.getCategoryById(channelId);
case VOICE:
return api.getVoiceChannelById(channelId);
case STORE:
return api.getStoreChannelById(channelId);
}
return null;
}
```
**After**
```java
@Nullable
public GuildChannel getChannel(@Nonnull JDA api)
{
Checks.notNull(api, "JDA");
return …
```
=> Add getGuildChannelById methods

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java, src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java, src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java
This handles the Z_SYNC_FLUSH suffix. I don't believe this will ever be used but its part of the protocol so we should support it. Currently discord doesn't use this but they might use it in the future.
=> Handle split zlib messages with Z_SYNC_FLUSH suffix

src/main/java/net/dv8tion/jda/api/entities/Emote.java
I updated some descriptions in the Emotes.java
- `Emote#getGuild()` also returns null in the case that the Guild is in fact one the bot shares, but is on a different shard than where this method was called.
- https://discordapp.com/developers/docs/resources/guild#emoji-object is no longer a valid link (no longer exists) so it was removed. When the link changed, let me know so that I can update it.
This PR is from the feature/v4/new-guild-properties and should be pulled into this branch if it gets accepted.
=> Update link to emoji documentation

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java
Fixes rate-limits on reaction endpoints. All these endpoints seem to use the same bucket for rate-limiting. I've tested this before and after this change and it seems to resolve the issue.
=> Fix rate-limits for reactions (undocumented behavior)

src/main/java/net/dv8tion/jda/api/entities/Invite.java, src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java
Invite was overlooked when refactoring time methods.
=> Deprecate Invite#getCreationTime in favor of Invite#getTimeCreated

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
When #995 was merged, animated icon support for guilds was added as a default interface method on the `Guild` object.
However the original method implementation wasn't removed from `GuildImpl`, causing `getIconUrl()` to always use the overriden implementation that does not support animated icons.
=> Remove the overriden "GuildImpl#getIconUrl()" implementation

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/api/utils/SessionController.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
The shard info indicates which shard id and shard total the current JDA session uses. If sharding is disabled this is equivalent to [0 / 1]. The identification string used for thread names is unchanged and will not report shard details unless explicitly set through `useSharding` or the shard manager.
- This is not a breaking change in java because it only changes an annotation.
- This is not a breaking change in kotlin because you can also store nonnull types in nullable typed variables. Safe-call operators should just emit a warning similar to unnecessary null checks.
=> Mark getShardInfo() nonnull

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/events/GatewayPingEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Introduces a new event to track updates to the gateway ping. This can be very useful for metrics or detecting connection issues.
```java
public class ConnectionListener extends ListenerAdapter {
@Override
public void onGatewayPing(GatewayPingEvent event) {
int prev = event.getOldValue(), next = event.getNewValue();
if (next >= prev + 100 && prev != -1) {
System.err.println("Gateway ping has increased by " + (next - prev) + "ms!");
}
}
}
```
=> Add GatewayPingEvent

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
Fixes the missing @CheckReturnValue annotation in MessageChannel#sendMessage(CharSequence)
I think it was forgotten as all other sendMessage methods got this annotation
=> Fix missing CheckReturnValue annotation

src/main/java/net/dv8tion/jda/internal/requests/FunctionalCallback.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java
This removes the blocking execute() calls in favor of the async enqueue+callback system provided by OkHTTP. This should allow the requester to be more concurrent on lighter thread configuration.
=> Use enqueue instead of execute for HTTP requests

src/main/java/net/dv8tion/jda/api/OnlineStatus.java
It is now specified that INVISIBLE is only used when the currently logged in account is INVISIBLE and that all other members will be shown as offline.
-  I have read the [contributing guidelines][contributing].
- Documentation
Adds a JavaDoc description for the INVISIBLE value of the OnlineStatus enum.
It is now specified that INVISIBLE can only be used for the currently logged in account.
And that all other members are shown as OFFLINE, even if they really are INVISIBLE.
=> Add javadoc desc for the INVISIBLE const of the OnlineStatus enum

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Close previously opened UDP client when the NAT hole punch is retried. I also moved the logic for retrieving the short endian port to the IOUtil where all the other related methods are located, this also removes  pointless allocation.
=> Cleanup udp discovery code

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Removed two redundant checks of the channel type from `net.dv8tion.jda.internal.entities.ReceivedMessage` (one from `getPrivateChannel()` and one from `getTextChannel()`).
=> Remove two redundant checks

src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
This PR adds methods to access the `StoreChannel` cache to the `ShardManager`.
=> Adding StoreChannel cache access methods to ShardManager

src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
This fixes the handling of nonces passed by the packet provider. The nonce array is never null but the length might be 0 which indicates that we use the legacy encryption. This shouldn't really matter since that encryption is never used.
=> Fix xsalsa20_poly1305 encryption

src/main/java/net/dv8tion/jda/api/entities/Webhook.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/internal/entities/WebhookImpl.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Now you can delete webhooks without knowing the token if you have permissions.
=> Improve handling of webhooks without tokens

src/main/java/net/dv8tion/jda/api/entities/Guild.java
Adds BoostTier#getMaxEmotes and Guild#getMaxEmotes so you can check the max amount of emotes a guild can have based on their boost tier
=> Add Guild#getMaxEmotes and BoostTier#getMaxEmotes

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/IBucket.java, src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/flags/ConfigFlag.java
This implements the upcoming `X-RateLimit-Precision` header. Unfortunately discord doesn't echo this header so we have to wait for it to be released.
=> Implement X-RateLimit-Precision handling

build.gradle.kts, src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/test/java/MarkdownTest.java, src/test/java/MarkdownUtilTest.java
Closes Issue: #1086
Fixes the `MarkdownSanitizer`'s `escape` method not properly escaping BOLD | ITALICS_A mixture of text (ie: `***text***`).
~~I did not test the changes, I will look how can I test later today.~~ 
~~I also plan to fix a very similar issue that I think might happen with code blocks, I will look into that later today too, making this PR a WIP one. I will therefore create a new commit, which I could squash them if preferable on any maintainer's request.~~ 
_Also, there might be a need to change the README's Contributing guidelines, as there is no `v4` branch anymore... :_ 
```
If you want to contribute to JDA, make sure to base your branch off of our v4 branch (or a feature-branch) and create …
```
=> Fix BOLD | ITALICS_A not getting escaped properly in MarkdownSanitizer (#1086)

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Closes Issue: #1091
Fixes a bug with the new Nullability handling and `ReceivedMessage` using `getGuild()` in its `getJumpUrl()` implementation
=> Fix getJumpUrl() in ReceivedMessage for DMs

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ReactionPaginationAction.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Closes Issue: #1075 
This PR implements the methods `Message#removeReaction`, `Message#retrieveReactionUsers`,
`Message#getReactionByName` and `Message#getReactionById` as outlined in the corresponding issue.
=> Improve Message reaction API

src/main/java/net/dv8tion/jda/internal/handle/ChannelDeleteHandler.java
When a voice channel is deleted on discord the handler only ever deleted it from the guild cache and not from the JDA cache. This caused an exception being thrown when getting the guild from a voice channel via the JDA cache because the guild was garbage collected.
This pull request fixes that by also deleting the voice channel from the JDA cache.
=> Remove Voice channel from JDA cache on deletion

src/main/java/net/dv8tion/jda/api/entities/Message.java
Closes Issue: #1071 
`Message.Attachment#isImage` has been renamed to `hasImage` and the `isImage`, `isVideo` methods have been added. This change was necessary because the previous `isImage` (now `hasImage`) returns `true` for videos as well (since it is based on the `width` and `height` properties). The new `isImage` and `isVideo` methods also depend on the `width` and `height` properties, but they do an additional check: they check the file extension of the uploaded attachment's name. For this reason as `getFileExtension` method has been added.
`isImage` is used internally once, in the `retrieveAsIcon` method.
Edit: the pointless, new `hasImage` method has been deleted, as per maintainer's request
=> isImage fix, addition of hasImage (fixes #1071)

src/main/java/net/dv8tion/jda/api/entities/Guild.java
The ternary for `getMaxBitrate` was reversed causing incorrect results, additionally vip regions have tier 3 bitrate. Also LURKABLE was deprecated and replaced by PUBLIC.
=> Rename LURKABLE feature and fix usage of VIP_REGIONS

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Adds an upper limit to Guild#prune's and Guild#retrievePrunableMemberCount's `days` according to Discord API's upper limit of thirty days. This prevents illegal amounts causing 400s by checking if the upper limit is met and throwing if it's not before a REST request can be made.
=> Add an upper limit to prune and retrievePrunableMemberCount

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/utils/EncodingUtil.java
This PR adds a missing ("breaking") check on the codepoint variant in `MessageChannel#removeReactionById` which lead to an `ErrorResponseException: 10014: Unknown Emoji` experienced by MarRue#3658 first. It also makes the code more uniform in terms of `addReactionById` and `removeReactionById`.
```JAVA
default RestAction<Void> addReactionById(@Nonnull String messageId, @Nonnull String unicode)
{
Checks.isSnowflake(messageId, "Message ID");
Checks.notNull(unicode, "Provided Unicode");
unicode = unicode.trim();
Checks.notEmpty(unicode, "Provided Unicode");
String encoded;
if (unicode.startsWith("U+"))  // checking for codepoint style
encoded = EncodingUtil.encodeCodepointsUTF8(unicode);
else …
```
=> Fix for removing an emoji reaction in codepoint style

src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
I've forked the `hacktoberfest` branch and tried to build it, but the `javadoc` task failed with message `malformed HTML`. This should fix it.
=> Fix "malformed HTML" javadoc task compilation error

src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
This allows to ignore specific error responses without a complicated piece of code.
```java
public static void selfDestruct(MessageChannel channel, String content) {
channel.sendMessage(content).queue((message) -> 
message.delete().queueAfter(30, SECONDS, null, ignore(UNKNOWN_MESSAGE))
);
}
```
=> Add ErrorResponseException.ignore(...)

src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java
When the `EmoteManager` is reset in `EmoteManagerImpl#finalizeData`, the role list is still referenced by the `DataObject`, clearing it before the rest action serializes it. This means that an empty list is always sent to Discord no matter the contents provided in `EmoteManager#setRoles(Set<Role>)`.
State before `reset()` is called:
State after `reset()` is called:
=> EmoteManagerImpl#finalizeData resets the role list before serializing

src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Fixes an npe that gets thrown when checking if a member can interact with another member in a server without an owner (owner banned)
=> Fixed nullpointer exceptions for when doing owner checks

src/main/java/net/dv8tion/jda/api/entities/Message.java
The JavaDoc of `net.dv8tion.jda.api.entities.Message#delete()`, referres to `net.dv8tion.jda.api.entities.MessageChannel#purgeMessages`.
While the link is correct, the text says `Collection` and not `List`.
This PR fixes this.
=> List instead of Collection in Javadoc of Message#delete

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
This changes the port to big endian which fixes the issue for voice receive. This means you can use voice receive without first having to send something (updating the port).
=> Improve audio receive handling

src/main/java/net/dv8tion/jda/api/entities/Message.java
- Corrects a typo where the Javadoc says `The pin was attempted after the Message had been deleted.` for the method `Message#delete();` which should be about the message being already deleted, when the request was performed.
- Added additional mention of `Attachment#getWidth()` and `Attachment#getHeight()` returning -1 if Attachment is neither an image nor video.
- Smaller grammar correction about the description of what Reactions are.
=> Correcting wrong information for Message#delete();

src/main/java/net/dv8tion/jda/api/utils/SessionController.java
The `SessionConnectNode` implementation (`StartingNode`) does not wait if `isLast` is true, but the interface documentation says that it waits if it is true.
=> Fix SessionConnectNode#run typo

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
The owner cache will be outdated when guild subscriptions are disabled thus we need to disable it as well.
=> Disable owner caching when guild subs are off

src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateOnlineStatusEvent.java, src/main/java/net/dv8tion/jda/internal/handle/PresenceUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Both of these handlers should only be executed if guild subscriptions are enabled.
=> Disable presence and typing handlers when guild subs are off

src/main/java/net/dv8tion/jda/internal/JDAImpl.java
This allows us to initialize the `SelfUser` before the ready event is received. Some events are fired before this gateway dispatch happens and they might find it useful to access the self user.
=> Initialize SelfUser from token verification

src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
Closes Issue: #1169 
We should only load members if they are connected to a voice channel when handling a voice state.
=> Only load member from voice state when connected

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java, src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
This also changes the default behavior to re-allocate the decompression buffer when it exceeds 2048 bytes. That seems to be a reasonable default. To get the previous behavior you can do `setMaxBufferSize(Integer.MAX_VALUE)`.
=> Allow setting a maximum decompression buffer size

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This should prevent high frequencies of OP 9 INVALIDATE hits during discord outages. This means the reconnect will exponentially backoff until a READY/RESUME is received.
=> Reset reconnect delay on session start

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildJoinEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildLeaveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/UnavailableGuildLeaveEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This will now ignore events for unavailable guilds. We do expect discord to not send any events for unavailable guilds but if they do we should ignore them. Handling events for unavailable guilds could lead to unforseen consequences.
=> Improve handling of events for unavailable guilds

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
This is a bug since the override shouldn't be in the interface
if the member is not actually in the cache. With the current
implementation we have a cache inconsistency that could NPE.
=> Let ChannelUpdateHandler add overrides to cache

src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java
Closes Issue: #1188 
This should fix a possible deadlock in `GuildDeleteHandler` which occurs because we are holding the write-lock while also trying to lock the audio connection. Holding a write-lock for this entire process is unnecessary so I rewrote it.
=> Change handling of GuildDeleteHandler to avoid deadlock

src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java
Adds a function `PermissionOverride#getPermissionHolder` to get the `IPermissionHolder`. It can be used to e. g. get the general permissions of that PermissionHolder no matter if it is a Member or a Role.
Also adds missing `@Nullable` annotations in the `PermissionOverrideImpl` class for consistency.
Check if a GuildChannel has a an override for a Member / Role which itself has a high permission (like Administrator, Manage Messages, etc.).
```java
for (Permission perm : HIGH_PERMISSIONS)
{
// Any member with an override has a high permission?
boolean highMemberOverride = permissionOverrides.stream()
.filter(PermissionOverride::isMemberOverride)
.anyMatch(po -> …
```
=> Add getPermissionHolder method to PermissionOverride

src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionRemoveEmoteEvent.java, src/main/java/net/dv8tion/jda/api/events/message/react/MessageReactionRemoveEmoteEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmoteHandler.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
This can be used to remove the entire reaction from a message. Previously you could only remove reactions from individual users or remove all reactions on the message, now you can delete all reactions with a specific emoji. We also need to add the related event **MESSAGE_REACTION_REMOVE_EMOJI**.
Reference: discordapp/discord-api-docs#1309
=> Add clearReactions(String)

src/main/java/net/dv8tion/jda/api/events/guild/invite/GenericGuildInviteEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/invite/GuildInviteCreateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/invite/GuildInviteDeleteEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/InviteImpl.java, src/main/java/net/dv8tion/jda/internal/handle/InviteCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/InviteDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Adds the new invite events:
- Invite Create
- Invite Delete
Both of these events can only happen in guilds for now so I called them `GuildInvite{X}Event` for better backwards compatibility in case discord decides to also open this up to groups(?) or similar.
These events can be useful to track invites of guilds which are not cached by JDA. I don't think its reasonable to implement invite caching into JDA as its not possible to initialize from the gateway alone (no invites in GUILD_CREATE).
=> Add (Guild) Invite Events

src/main/java/net/dv8tion/jda/api/entities/Invite.java
Previously, the docs of [Invite#isExpanded](https://javadoc.io/static/net.dv8tion/JDA/4.1.1_109/net/dv8tion/jda/api/entities/Invite.html#isExpanded()) stated that `Channel#retrieveInvites` would require the `MANAGE_SERVER` Permission and that `Guild#retrieveInvites` would require the `MANAGE_CHANNEL` permission.
It should be swapped as described in the official discord developer docs [here](https://discordapp.com/developers/docs/resources/channel#get-channel-invites) and [here](https://discordapp.com/developers/docs/resources/guild#get-guild-invites)
Thanks to @byNoobiYT for finding this out.
As suggested by @DManstrator in the comments, this PR does also fix a typo (`can only be obtained be` …
=> Swapped manage server and manage channel in Invite#isExpanded docs

src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberLeaveEvent.java
Added the missing `@deprecated` note about this method being deprecated in favour of the `GuildMemberRemoveEvent`
=> Add deprecated comment to GuildMemberLeaveEvent

src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateBannerEvent.java
The method `GuildUpdateBannerEvent#getNewBannerIdUrl` is a typo for `getNewBannerUrl` and it is corrected in this PR.
=> Deprecate GuildUpdateBannerEvent#getNewBannerIdUrl

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
This enables users to open a private channel directly using the user id instead of first retrieving the user. Additionally, we now always keep the channel id in the user object once it has been resolved.
=> Allow to open private channel with user id

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/RateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/ClientRateLimiter.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java, src/main/java/net/dv8tion/jda/internal/utils/concurrent/CountingThreadFactory.java, src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingSessionConfig.java
Now the rate limit pool will keep doing requests until all requests are exhausted. I also decided to add an info log about this behavior so people know why the process doesn't stop immediately when calling `JDA#shutdown`.
=> Change defaults for requester to be non-daemon and have a shorter timeout

src/main/java/net/dv8tion/jda/api/Permission.java
Since some months now, Discord has introduced a new feature called [Server Insights](https://support.discordapp.com/hc/en-us/articles/360032807371-Server-Insights-FAQ). For now, this feature - reserved to Verified or Partnered Discord - allows us to track members activities and more. Those statistics who were previously hide are used to determine if a server can be introduced in the server discovery.
Currently, this feature is experimental, but, since a little number of days, the *View Server Insights* permission has popped out on the developer portal, meaning Discord want's to *open* this feature (at least to developers).
The goal of this PR is therefore to implement the missing *View Server Insights* present …
=> Added Server Insights permission

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
Include voice server endpoint in connection failure logs for easier debugging
Includes the voice server endpoint in connection failure logs to make debugging voice server issues easier. 
The spacing was a bit weird -- wasn't entirely sure what level to put it at. It was weirdly spaced before.
=> Include voice server endpoint in connection failure logs for easier debugging

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
This PR adds a check in removing / clearing reaction methods, checking if the message was sent in a TextChannel and else tells the user that he is unable to remove reactions of others or clear them if the message is not from a TextChannel.
Before, `getTextChannel()` was called without a check throwing `This message was not sent in a text channel` if the message was from a PrivateChannel (or group) which could be misleading ([and actually was](https://discordapp.com/channels/81384788765712384/381889648827301889/684520138367827971) which is why I make that PR) in that context.
This also fixes a **bug** where if the SelfUser was passed to the function, it would still have thrown that exception …
=> Adding a check in reaction methods before calling getTextChannel()

.github/ISSUE_TEMPLATE/bug_report.md
This adds a new section to the bug report template. With the new changes to 4.2.0 we will need to always know how the user started the JDA session because of how things rely on intents and cache configuration.
=> Add section to bug report template

src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java, src/main/java/net/dv8tion/jda/api/events/guild/voice/GuildVoiceStreamEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java
Adds the missing `self_stream` property on voice states. ~~I haven't tested it yet.~~ Works as expected.
=> Add GuildVoiceStreamEvent

src/main/java/net/dv8tion/jda/api/requests/CloseCode.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
The reconnect close codes we use shouldn't overlap with the disconnect close codes that discord uses. This will make it a lot easier to identify an issue with the connection. If we close with 4000 it can be confusing because discord also uses this code for various other reasons, such as gateway timeout for large bots.
I chose code 4900 for reconnects since it should be way out of the normal code range that discord uses but is still RFC compliant. The fallback code has been changed to 1005 which is the correct code to indicate a missing close code.
=> Change reconnect code to 4900 to avoid confusion

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java
Fixes an issue where the `byte[]` overload of `MessageChannel#sendFile` 
does not check permissions and ignores guild boosts in the max allowed size check.
=> Fix incorrect size check for MessageChannel#sendFile

src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/compress/Decompressor.java, src/main/java/net/dv8tion/jda/internal/utils/compress/ZlibDecompressor.java
I finally had some time to deep dive into some performance optimizations. The wins are not huge here, but still around a solid 5 % on a bot that has most intents turned off. I can imagine that number to look better the more events are received, as well as bot that have high REST requests (I did not do any).
This PR has 3 areas of improvement:
A. Uses the binary representation of websocket text messages
B. Avoid intermediate string representation of JSON payloads received on the websocket
C. Avoid intermediate string representation of JSON request bodies for rest actions
These are based on the official recommendations from Jackson, see https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performanc …
=> Json Parsing Optimizations

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This removes the initial reconnect delay when we can resume.
=> Remove initial reconnect delay for resumes

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Add prune overload which allows to disable the `compute_member_count` parameter. This can be useful for prunes on large guilds where this computation may timeout the response.
=> Add prune overload to disable wait parameter

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This should detect zombie connections when the websocket library fails.
=> Add check for heartbeats in WebSocketClient

src/main/java/net/dv8tion/jda/api/Permission.java
Removes a link in the `Permission` enum, which is no longer valid.
If there is a replacement for this information, let me know and I implement it.
=> Fix invalid link in Permission enum

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/question.md
Closes Issue: #1252 
This PR implements a `config.yml` within the `.github/ISSUE_TEMPLATE` directory.
Having this file allows for the addition of external links to sources like the wiki, javadoc, or releases.
It also allows disabling of the option to skip choosing a template.
Current Settings are as follows:
- Creating of blank issues is __disabled__
- Following Links where added:
- Discord: https://discord.gg/0hMr4ce0tIk3pSjp
- Javadoc: https://ci.dv8tion.net/job/JDA/javadoc/
- Jenkins: https://ci.dv8tion.net/job/JDA/
- Wiki: https://github.com/DV8FromTheWorld/JDA/wiki
- Releases: https://github.com/DV8FromTheWorld/JDA/releases
=> Implement config.yml for Template chooser

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
The `disconnect` method will work regardless of the `WriteThread`. However, it interrupts the thread so we have to create a new thread to handle the sleeping. There isn't a good thread-pool we could use for this and I don't wanna add another one just for this small code. This should in theory have marginal performance cost.
=> Replace disconnect handling to recover from strange thread states

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Closing the gateway connection will interrupt the read thread. So, we should try doing that last.
=> Shutdown the WebSocket connection after everything else

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/utils/concurrent/Task.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java, src/main/java/net/dv8tion/jda/internal/utils/concurrent/task/GatewayTask.java
This adds a method to retrieve a list of members, filtered by user IDs.
Note: We can't add a `retrieveMembersByIds(Collection<String>)` due to java type erasure.
```java
guild.retrieveMembersByIds(86699011792191488L, 107562988810027008L)
.onSuccess((list) -> System.out.println("Found members: " + list));
```
=> Add methods to bulk retrieve members

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/OnlineStatus.java, src/main/java/net/dv8tion/jda/api/entities/Activity.java, src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageActivity.java, src/main/java/net/dv8tion/jda/api/entities/RichPresence.java, src/main/java/net/dv8tion/jda/api/entities/Webhook.java, src/main/java/net/dv8tion/jda/api/events/RawGatewayEvent.java, src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/api/hooks/VoiceDispatchInterceptor.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/requests/CloseCode.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MemberAction.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/MiscUtil.java, src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java
Change to the new domain which will be required by 7th November 2020.
=> Change domain to discord.com

src/main/java/net/dv8tion/jda/api/Permission.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/events/user/update/UserUpdateFlagsEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
This implements the `public_flags` value for the User object, which essentially contains all [user flags](https://discord.com/developers/docs/resources/user#user-object-user-flags) with some exceptions like what type of nitro (or if they even have nitro) the user has and some other hidden flags.
=> Add User#getFlags

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
This seems to be a common segfault for users so we
should adjust the settings automatically instead.
=> Automatically adjust settings based on intents

src/main/java/net/dv8tion/jda/api/managers/AudioManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/audio/AudioConnection.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceServerUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/managers/AudioManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
This adjusts the internals to properly handle disconnect -> voice region change. Discord seems to sometimes first disconnect our socket and then send the new voice region. This change now means that we will always establish a new connection when we get a VOICE_SERVER_UPDATE. According to testing, these are only sent to the session that requested the connection so that additional check is no longer present.
=> Improve handling of VOICE_SERVER_UPDATE

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
The disconnect() method interrupts the read thread.
This can become problematic for various reasons.
However, if we are in a zombie state we need to use this method because it will kill the read thread appropriately.
=> Only use interrupts when we recover zombie connections

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/utils/ConcurrentSessionController.java, src/main/java/net/dv8tion/jda/api/utils/SessionController.java, src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java, src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
This implements the `max_concurrency` buckets in a new `ConcurrentSessionController` class (new default). The concurrency means that multiple shards can connect simultaneously, without hitting the identify rate limit. This is very important for larger bots which can connect 16 or 64 shards at once to reduce startup time.
The buckets work by using a modulo over the `shard_id`:
```
bucket = shard_id % concurrency
```
=> Implement max_concurrency in SessionController

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java
This adds a few convenience methods to reaction events. You can now retrieve the target message and reaction issuer directly from the event.
```java
@Override
public void onMessageReactionRemove(MessageReactionRemoveEvent event) {
event.retrieveMessage()
.map(Message::getContentDisplay)
.queue(System.out::println);
}
```
=> Add some convenience methods to reaction events

src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
Adds a `getAsReactionCode()` method to `MessageReaction.ReactionEmote` which would either return the UTF-8 code of the emoji, or the name and id of the Emote in the format `name:id` depending on what type it is.
=> Add ReactionEmote#getAsReactionCode method

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Closes Issue: #1313
This avoids Discord returning "{roles:[2]}" if your list contains duplicate roles... which isn't a very helpful thing when you are trying to debug why that is happening.
=> Remove duplicate roles when using "Guild.modifyMemberRoles(...)"

src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/config/SessionConfig.java
We can use timeouts that are 10s longer than the heartbeat_interval. This should hopefully make the "missed 2 heartbeats" warning less frequent and improve stability.
=> Properly apply socket timeouts where appropriate

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupNode.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java
This introduces better methods for loading members on a guild.
**Current:**
```java
guild.retrieveMembers().thenRun(() -> {
List<Member> members = guild.getMembers();
members.forEach(System.out::println);
guild.pruneMemberCache(); // manually clear the cache again
});
guild.retrieveMembers().thenRun(() -> {
List<Member> members = guild.getMembers();
System.out.println(members.size());
guild.pruneMemberCache(); // manually clear the cache again
});
```
**New:**
```java
guild.loadMembers(System.out::println); // only adds members to cache which the policy accepts
guild.loadMembers().onSuccess((members) -> {
System.out.println(members.size());
});
```
=> Introduce better methods to load members

src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java
Remove wrong @throws JavaDoc from MessageAction#allowedMentions
The docs/development branch doesn't have this feature yet so the PR is targeting the development branch.
=> Remove wrong @throws JavaDoc from MessageAction#allowedMentions

src/main/java/net/dv8tion/jda/api/GatewayEncoding.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java, src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermEncoder.java, src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermTag.java, src/main/java/net/dv8tion/jda/api/utils/data/etf/package-info.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/handle/MessageBulkDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ShardingMetaConfig.java
This adds a custom implementation to parse and serialize ETF payloads for the discord gateway connection.
You can enable this by using `JDABuilder#setGatewayEncoding(GatewayEncoding.ETF)`, this will be an opt-in.
=> Add ETF support

src/main/java/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionRemoveEmoteEvent.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmoteHandler.java
Make GuildMessageReactionRemoveEmoteEvent extend GenericGuildMessageEvent like the other Reaction remove events
=> Make GuildMessageReactionRemoveEmoteEvent extend GenericGuildMessageEvent

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
This PR adds a mention of the default value of `setMaxReconnectDelay` for both `JDABuilder` and `DefaultShardManagerBuilder` to the docs.
=> Mention the default value of setMaxReconnectDelay in the docs

src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Adds `Emote#isAvailable()` method which tells if the emote is available or not.
The [Emoji structure](https://discord.com/developers/docs/resources/emoji#emoji-object-emoji-structure) has a `available` field that indicates if the emote is available for the users, depending on the current boost tier of the Guild.
=> Add Emote#isAvailable() method

src/main/java/net/dv8tion/jda/api/Permission.java
Found one place where the old discord domain is still present in the docs.
Powered by 
```
rg '(?<!cdn.)discordapp.com' --pcre2 --files-with-matches | xargs gsed -i 's/discordapp\.com/discord\.com/g'
```
in case you want to fix more projects that you have checked out locally.
=> Fix Discord domain in docs

src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/internal/entities/UserById.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
This implements a wrapper object which only contains a user's ID. Useful to avoid tons of overloads that do the same thing. This requires a bit of testing before merging.
```java
User user = User.fromId(86699011792191488L);
channel.removeReaction(unicode, user).queue();
```
=> Add UserById wrapper

src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
When we get rate-limited by cloudflare the retry-after is in seconds. We can detect cloudflare rate-limits by checking whether the [via header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Via) is present.
=> Handle cloudflare rate limits

src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/PermissionOverrideImpl.java, src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/PermOverrideManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/RoleManagerImpl.java, src/main/java/net/dv8tion/jda/internal/utils/cache/SnowflakeReference.java
This removes the usage of `SnowflakeReference` which was used to avoid memory leaks from continuously storing JDA entities such as members. Memory leaks are now solved in a different way, by replacing the upstream reference when the cache has updated. This does not handle cases where the entire JDA session is replaced, however that is a specific use-case that we shouldn't need to handle explicitly for the users.
The `SnowflakeReference` class adds a severe overhead in both memory usage and GC usage. Some GC implementations seem to struggle a lot with `WeakReference`, which is a crucial part of this system.
=> Replace SnowflakeReference

src/main/java/net/dv8tion/jda/api/requests/restaction/order/OrderAction.java
This PR changes the wording of OrderAction#sortOrder docs to match the docs of other order-changing methods.
=> Change wording of OrderAction#sortOrder to match other methods' docs

src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java
This PR adds dots to the parameters of methods `addPermissionOverride`, `addMemberPermissionOverride` and `addRolePermissionOverride`. The parameters without these dots look a bit strange as there's only a space.
#ocd
=> Add "missing" dots to permission override methods params

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/TextChannel.java, src/main/java/net/dv8tion/jda/api/events/channel/text/update/TextChannelUpdateNewsEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/Route.java
Closes Issue: #1357 
We don't handle news channels by using the NEWS type. We will instead use a boolean which makes the code a lot easier to understand. Using a new channel type only for news channels makes no sense since the only difference to text channels is the possibility to crosspost messages.
You can have news channels in a guild without having the NEWS feature. However, those channels do not support crossposting so it makes sense to simply handle them like they are not news channels.
```java
@Override
public boolean isNews()
{
return news && getGuild().getFeatures().contains("NEWS");
}
```
This also simplifies the checks we need to perform in our code for crossposting.
Gotcha's:
- Trying to crosspost a …
=> Implement support for news channels

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java
A couple of weeks ago, I submitted a pull request that attempted to resolve the issue causing symbols to not be sanitized correctly inside of quotes. Unfortunately, I found that putting a symbol in front of a quote causes my previous fix to not work correctly.
Example: ``> _Hello \n> _World`` ->``\\> \\_Hello \n> \\_World``
This fixes the issue by changing the regex to allow for quotes that contain just spaces. While Discord removes these extra spaces itself, they are still able to generate quotes (a bit of a weird fix).
BEFORE
``> ​``
(As stated before, these are still valid quotes)
AFTER
``\> ​``
If there are any more issues related to this in the future, it might be better just to redo how …
=> Fix inconsistency with MarkdownSanitizer 

src/main/java/net/dv8tion/jda/api/managers/Presence.java
This pull request fixes a typo the javadoc of `net.dv8tion.jda.api.managers.Presence#setActivity`.
It corrects `A Activity` to `An Activity`.
=> fix typo in Presence

src/main/java/net/dv8tion/jda/api/entities/Guild.java
changed throws wording for retrieveMembers to rather mention users instead of ids
=> change throws wording for retrieveMembers

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java, src/main/java/net/dv8tion/jda/internal/utils/config/sharding/ThreadingProviderConfig.java
Allow the users to provide the thread pool used for the audio stuff.
Why? This helps to get rid of 1 mostly idling thread per shard. In my largest use case, thats 300+ threads gone.
=> Make audio thread pool configurable by users

src/main/java/net/dv8tion/jda/api/entities/Activity.java
Add check to Activity#playing and similar methods to test if the provided name is longer than 128 characters.
Why? Discord won't show activities longer than that.
=> Add length check to Activity#playing and similar methods

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Discord allows using reactions to system messages. You still can't pin them though.
=> Allow using reactions on system messages 

src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberRemoveEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/GuildMemberUpdateEvent.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMemberUpdateHandler.java
This event will fire for every GUILD_MEMBER_UPDATE dispatch and can be used for stateless handling. This is necessary because the other update events can only function when the member is already in cache. See https://github.com/discord/discord-api-docs/issues/2137
=> Add watered-down GuildMemberUpdateEvent

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageType.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
https://github.com/discord/discord-api-docs/pull/2118
=> Implement inline replies feature

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java
Adds a `isSynced()` method to the GuildChannel to check whether the Channel is synced with its parent (the category.
I set it to return true when the channel doesn't has a parent.
I'm not sure if the current way of doing this is actually good so I really appreciate if a better method would be provided.
=> Adding isSynced() method

src/main/java/net/dv8tion/jda/api/entities/Activity.java
Adds `ActivityType.COMPETING` (ID 5) and `Activity.competing(String)` to the Activity Interface.
This activity type is usable by bots, as shown below by my personal Bot that I quickly used to test this with my fork:
For safety did I add the `@Incubating` annotation and `@incubating` javadoc-tag to the `competing` method. I didn't add those to the ActivityType tho as the reason they are there for wating seems to be, that it is undocumented, which is (partially) wrong? Docs do contain info on the activity types, just not directly related to bots.
Will add this, if required.
=> Add ActivityType.COMPETING

src/main/java/net/dv8tion/jda/api/hooks/EventListener.java
Changed a example to the static JDA Builder in place of old constructor.
Corrects a mistake in EventListener where an example of builder in the documentation doesn't the static method.
Changed from `JDA jda = new JDABuilder.createDefault("token").addEventListeners(listeners).build();` to 
`JDA jda = JDABuilder.createDefault("token").addEventListeners(listeners).build();`
=> Fixed outdated documentation of an example of builder in EventListener.

src/main/java/net/dv8tion/jda/api/entities/Guild.java
This PR changes a misleading documentation in the Guild interface.
I see that retrieveVanityUrl is deprecated but as it is still in the code the documentation may cause confusion when referring to the ban list while trying to retrieve the vanity url.
=> Fixed documentation at retrieveVanityUrl

src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java
this should fix getting IllegalArgumentException when using retrievePast/retrieveFuture methods for private channels
=> Fix IllegalArgumentException in retrievePast/retrieveFuture

src/main/java/net/dv8tion/jda/api/events/message/guild/react/GuildMessageReactionAddEvent.java
Closes Issue: #1385
As of now, the docs for GuildMessageReactionAddEvent are copied from GenericGuildMessageReactionEvent, which states that getMember and getUser can be null. However, GuildMessageReactionAddEvent is guaranteed to have a user and member, and there are annotations in place to indicate this.
This PR adds 2 javadoc sections to GuildMessageReactionAddEvent, so it doesn't wrongly use those of its superclass.
The topic was already brought up in #1385, and deemed not a bug. I'd argue that more documentation and thus less confusion is always good, but if you disagree, it's your call to close this.
=> Docs: Nullability in GuildMessageReactionAddEvent

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
This adds the new **fail_if_not_exists field** that can be used to suppress errors when the referenced message was deleted. 
See discord/discord-api-docs#2572
=> Add fail_if_not_exists

src/main/java/net/dv8tion/jda/api/audit/ActionType.java, src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateCommunityUpdatesChannelEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateRulesChannelEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/managers/GuildManager.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
this PR adds Guild#getRulesChannel and Guild#getCommunityUpdatesChannel.
i'm not sure about being able to set the rules and community updates channel even without the `COMMUNITY` feature, as it works, and Discord doesn't return any error - i've made an issue discord/discord-api-docs#2282 in the api docs repo, so i'm waiting for response there.
ideas and suggestions are welcome
=> add Guild#getRulesChannel and Guild#getCommunityUpdatesChannel

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java
The methods `createDefault(String, GatewayIntent, GatewayIntent...)`, `createLight(String, GatewayIntent, GatewayIntent...)` as well as their counter-parts with Collection do not mention that using those essentially overrides the `GatewayIntent#DEFAULT` as you basically have to provide your own ones, instead of adding them to the defaults.
This can cause people to believe that those methods are used to define the default intents and also add additional ones you need (i.e. GUILD_MEMBERS),
The only real mention is, when you compare it to `createDefault(String)`/`createLight(String)` where one extra List entry mentions the intents to be set to `GatewayIntent#DEFAULT`
=> [Docs] Mention that createDefault and createLight may override GatewayIntent#DEFAULT

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Closes Issue: https://github.com/DV8FromTheWorld/JDA/issues/1485
This PR fixes, that the isSynced() method in AbstractChannelImpl doesn't check if the permissions of the PermissionOverrides are equal. It just checked, if the category had the PermissionOverrides with the same id.
=> Fixed isSynced() in AbstractChannelImpl

src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/RoleAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/RoleActionImpl.java
These checks mean you get an error every time discord adds a new permission. We should avoid doing that.
We shouldn't check for unknown enum values
And checking the sign for an unsigned int is bad
=> Remove unnecessary checks for permission values

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdatePendingEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/utils/MemberCachePolicy.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
this PR adds Member#isPending and GuildMemberUpdatePendingEvent. i'm not really sure about the event name as it's a pretty much one-way event but.. yeah
=> add Member#isPending

src/main/java/net/dv8tion/jda/api/events/ReadyEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildReadyEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildTimeoutEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/UnavailableGuildJoinedEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/internal/handle/GuildSetupController.java
This timeout handler will automatically mark all guilds unavailable after ~~10~~ 75 seconds when hitting <=60 finished guilds. ~~I'm not entirely sure if 10 seconds is an appropriate timeout here, considering that the websocket rate limit is 60 seconds long. Maybe we should use 70 seconds instead? This would theoretically only be an issue for bots with a lot of guilds that perform chunking for every guild.~~ This is now set to 75 seconds which is the rate limit period plus 15 additional seconds for them to respond.
=> Implement a timeout for unavailable guilds

README.md, build.gradle.kts, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
By default we use a timeout of 10 seconds, just to prevent it from deadlocking. You can configure a lower timeout (min. 1 second) with `WebSocketFactory#setSocketTimeout` and passing that factory to one of the JDA builders.
=> Set socket timeout before connecting websockets

src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
We should always log long rate limits on warn level, unless its also a global rate limit (which is already logged elsewhere).
=> Improve some logging for large rate limits

src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
The `reset()` call that was removed in #1549 was used to initialize the allow/deny fields in the override action. Since we no longer reset it on every call, this is now broken.
This PR addresses this problem by properly initializing the current allow/deny values lazily.
=> Fix deny/grant on override action

src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Closes Issue: #1558
This adds the new [Message Types](https://discord.com/developers/docs/resources/channel#message-object-message-types).
=> Add missing message types

src/main/java/net/dv8tion/jda/api/JDA.java
Closes Issue: #1556
Changes the length check to use `String#codePointCount(int beginIndex, int endIndex)` to give compatibility for usernames to include surrogate pairs.
=> Changed getUserByTag(String username, String discriminator) to use codepoints when checking username length

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Discord sends invalid reset-after headers on 429
Source: https://github.com/discord/discord-api-docs/issues/2761
We should just always cache private channels, even if it's not from a message create.
=> Hotfix some issues introduced by v8

src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/UserById.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Deprecates `UserFlag.SYSTEM` as it is an internal flag now and won't show up on any user (see [discord-api-docs issue 2494](https://github.com/discord/discord-api-docs/issues/2494#issuecomment-816970401)), and adds `User#isSystem` as a replacement.
=> Deprecate UserFlag#SYSTEM and add User#isSystem

src/main/java/net/dv8tion/jda/api/entities/GuildChannel.java
this PR removes a note about nullability in GuildChannel#getName docs, as it's annotated as `@Nonnull` and i can't think of any scenario where the name could indeed be null. if it can indeed be null, then i'll rather change the annotation
=> remove nullability note for GuildChannel#getName

src/main/java/net/dv8tion/jda/api/Permission.java
Closes Issue: #1620 
Fixes Permission.ALL_VOICE_PERMISSIONS not including Permission.PRIORITY_SPEAKER
=> Fix Permission.ALL_VOICE_PERMISSIONS not including Permission.PRIORITY_SPEAKER

src/main/java/net/dv8tion/jda/api/entities/User.java
This pull request implements the Discord Certified Moderator flag:
Nobody to my knowledge has this flag yet so it may be better to hold off until it's "officially" released or at least documented on the api docs ([#2946](https://github.com/discord/discord-api-docs/pull/2946)).
=> Add Discord Certified Moderator flag

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/Activity.java, src/main/java/net/dv8tion/jda/api/entities/RichPresence.java, src/main/java/net/dv8tion/jda/api/exceptions/RateLimitedException.java, src/main/java/net/dv8tion/jda/api/utils/WidgetUtil.java, src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Replaces internal String#format calls in JDA to use a helper method that has the locale set to Locale.ROOT. This fixes issues with JDA not being locale-safe, such as replacing `8` in the API version to the Arabic numeral 8, when the default locale is Arabic.
=> Make String.format usage locale safe

src/main/java/net/dv8tion/jda/internal/requests/WebSocketSendingThread.java
Discord is very slow when the corresponding voice state update event, so a retry that small can lead to JDA spamming Discord with way too may voice state updates. This bumps the retry to 10 seconds.
=> Increase audio request retry from 2 seconds to 10 seconds

src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
Allows a DefaultShardManager to be built without immediately starting it. This is useful in dependency injection situations, where the ShardManager might need to be injected into several places before it's started.
=> Allow building DefaultShardManager without starting it

src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Closes Issue: #1654 
This PR fixes not being able to use `Message#editMessage(Message)` if the passed `Message` is of type `INLINE_REPLY` or `APPLICATION_COMMAND`
=> Fix Message.editMessage(Message) only accepting Message of type DEFAULT

src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java
Even though Discord does not allow combining command options with subcommands or subcommand groups, it is allowed to have subcommands in combination with subcommand groups on a single command. JDA currently does not allow this, as it always throws an error when trying to create such a command.
This commit simply removes setting the `allowGroups` and `allowSubcommands` flags when adding subcommands or subcommand groups.
=> Fix checks in CommandData#addSubcommand and CommandData#addSubcommandGroup

src/main/java/net/dv8tion/jda/internal/entities/DataMessage.java
Closes #1677
this PR adds a check for null `embeds` field in DataMessage#getEmbeds
=> add a check for null embeds field in DataMessage#getEmbeds

src/main/java/net/dv8tion/jda/api/MessageBuilder.java
This fixes the issue that happens when `MessageBuilder#buildAll` is called on a message with 2001+ characters. Once the message is split, the last character of the last message ends up being cut off. The reason this happens is because the endIndex of the substring is set as builder.length()-1, even though a substring's end index is exclusive. As a result, the last char in the StringBuilder of the message ends up being cut off. 
With the following sample code
```java
StringBuilder db = new StringBuilder();
for (int i = 0; i < 4000; i++) {
if (i != 1999 && i != 3999)
db.append('a');
else db.append('b');
}
db.append('c');
new MessageBuilder(db.toString()) …
```
=> Fixed the issue with last character handling for cases when the length of the message is 4001 characters

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
this PR adds missing checks to Message#suppressEmbeds. I'm not sure about throwing `PermissionException` in the private channel case but it's in the docs
=> add missing checks to Message#suppressEmbeds

src/main/java/net/dv8tion/jda/api/interactions/components/Button.java, src/main/java/net/dv8tion/jda/api/utils/TimeFormat.java, src/main/java/net/dv8tion/jda/api/utils/Timestamp.java
This adds utilities to parse and format timestamps in Discord markdown.
```java
channel.sendMessage("The beginning of time: " + TimeFormat.RELATIVE.format(0L)).queue();
```
=> Add TimeFormat and Timestamp

src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
When testing the latest JDA version (`4.3.0_286`), I noticed that when setting `EmbedBuilder#ZERO_WIDTH_SPACE` as the `StageInstanceAction` topic, I would only get an error when sending, not before.
This PR should fix this.
=> Replace isEmpty check with isBlank in StageInstanceActionImpl#setTopic

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Checks.java
Add Checks#notShorter(), and check for the name length when creating/updating emotes.
This PR adds a `Checks#notShorter()` method, and adds checks for the name length when creating/updating emotes.
=> Change checks for emote name length to check minimum length

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Closes Issue: #1702
Increases the `MessageEmbed.TEXT_MAX_LENGTH` to `4096` and also adds new value called `FOOTER_MAX_LENGTH` since the old Javadoc mentions the text value being for description AND footer.
Not sure if a new value shouldn't be added for the description while deprecating the text one for those who are using this int value for both footer and description...
=> Bump embed max description length

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java
This PR changes the visibility of the SelectionMenu.Builder's constructor to be protected, in order to make inheriting this builder possible
=> Change SelectionMenu.Builder#Builder visibility to protected

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Closes Issue: #1731 
Updated `stickers` to `sticker_items` in the EntityBuilder
=> Fix outdated sticker field name

src/main/java/net/dv8tion/jda/api/entities/Message.java
This PR fixes some documentation in the Message interface.
Previously, some of these methods would throw an Exception if the Message was not of Type DEFAULT, this has now changed with INLINE_REPLY and APPLICATION_COMMAND, since all of these methods can be accessed by them.
=> Fix documentation in Message interface

src/main/java/net/dv8tion/jda/api/entities/MessageReference.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java
Discord User `rakosi2#0001` mentioned in the JDA server that `Message#getReferencedMessage` always returned `null` after #1686 was merged. This happend because `AbstractMessage#getReferencedMessage` overrode [the default implementation in the `Message` interface](https://github.com/DV8FromTheWorld/JDA/blob/969f3f399d050d5470ce27f2a78a8597914c39f9/src/main/java/net/dv8tion/jda/api/entities/Message.java#L243-L248). The fix was to remove that useless override.
While fixing this, I stumbled upon another bug in `MessageReference#resolve` where I got a "Missing MESSAGE_READ permission" error. This came due to only having that perm in the used channel as a Permission Override. This was fixed by adding the guild channel …
=> Fixing getReferencedMessage and permissions for resolving a MessageReference

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java
This enables users to replace an EmbedBuilder's content with another embed or another builder. 
This may solve situations such as when you need to fill a given EmbedBuilder but already have an embed ready, and replacing the old EmbedBuilder's variable by the new one is not possible.
Also adds a missing constructor
=> Add copyFrom to EmbedBuilder

src/main/java/net/dv8tion/jda/api/events/message/guild/GuildMessageEmbedEvent.java
- [X ] I have checked the PRs for upcoming features/bug fixes.
- [ X] I have read the [contributing guidelines][contributing].
- [ X] Documentation
Closes Issue: 1712
Makes the docs of the GuildMessageEmbedEvent more clear of when the event actually triggers
=> Clarifies the use-case of GuildMessageEmbedEvent within the docs

src/main/java/net/dv8tion/jda/api/requests/Response.java, src/main/java/net/dv8tion/jda/internal/requests/Requester.java
This prevents bots from crashing when using `complete()` if the internal response parsing fails. The `Response` constructor was trying to re-read the body of the response because we pass in the same (already closed) response when handling exceptions thrown by `RestActionImpl#handleResponse`.
The stacktrace looks like this:
```
[15:46:09] [ERROR] Requester: There was an unexpected error while executing a REST request
java.lang.IllegalArgumentException: UNKNOWN_MESSAGE_TYPE
at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:1234)
at net.dv8tion.jda.api.entities.MessageChannel.lambda$retrieveMessageById$0(MessageChannel.java:896)
at …
```
=> Fix exception handling for parsing errors

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java, src/main/java/net/dv8tion/jda/api/interactions/components/Button.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectOption.java
Introduces public fields in SelectOption that contain the maximum length of Label, Value and Description.
Introduces public fields in Button that contain the maximum length of Label, ID and URL.
Identical to MessageEmbed, these fields can then be used by developers without having to update themselves when changes occur.
=> Bump selection option limits and extract max length values of SelectOption and Button

src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java, src/main/java/net/dv8tion/jda/api/entities/MessageType.java
Adds the new message types for threads of THREAD_CREATED and THREAD_STARTER_MESSAGE, as well as documenting the old types that have been repurposed with the release of Threads.
=> Add new message types for Threads

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Adds the JDA version to the "Got an unexpected error. Please redirect following message to the devs:" message, which may now look like this:
```
[00:00:01 ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
JDA 4.3.0_307
MESSAGE_CREATE -> // JSON stuff
// Exception
```
This is mainly to help people, most importantly maintainers, to easily find out what version is used and if the error is caused by an outdated version of JDA or if the issue persists in newer builds and is therefore something to fix or look into.
=> Add JDA Version to Websocket errors

src/main/java/net/dv8tion/jda/api/events/channel/voice/update/VoiceChannelUpdateUserLimitEvent.java
This PR clarifies some docs for voice update events (VoiceChannelUpdateUserLimitEvent). The docs were previously ambiguous as to what happens when no user limit is set. This has been corrected.
=> Clarified VoiceChannelUpdateUserLimitEvent docs

src/main/java/net/dv8tion/jda/api/events/interaction/SlashCommandEvent.java, src/main/java/net/dv8tion/jda/api/interactions/commands/CommandInteraction.java
(Updated Files from last PR, branch corrupted)
Adds SlashCommandEvent#getCommandString() which will provide the text the user typed in to activate the command:
Ex: 
/say phrase: Hello World! mention: @ Johnny
=> Add SlashCommandEvent.getCommandString

src/main/java/net/dv8tion/jda/api/interactions/Interaction.java, src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
Adds a missing `getJDA()` on Interaction.
=> Add missing getJDA() on Interaction

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java
The example for the `SelectionMenu` had wrong `addOption` setups where the label and value were flipped.
=> Fix SelectionMenu example having label and value switched in addOption

src/main/java/net/dv8tion/jda/api/exceptions/PermissionException.java
A null `Permission` is semantic nonsense: it is `Permission.UNKNOWN` but with extra steps (i.e. null checks). As such, it should not be allowed to propagate through a `PermissionException`. This PR enforces and encodes that.
=> Ensure permission in PermissionException is not null

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
A commit that moved many constants to the MAX_NAME_LENGTH mistakenly also moved a few values that were 100 into a constant with value 32.
This commit will add a new constant, MAX_NAME_OPTION_LENGTH, to fix those values back to their intended values of 100.
The commit title is meant to say Option Choice, not OptionData.
=> Change choice name length check to 100 instead of 32

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Closes Issue: #1781
Discord handles unmuting suppressed users with no talk permissions by sending an API call that would otherwise unmute the member guild-wide. This check inside of the mute action prevents this:
```Java
if (voiceState.isGuildMuted() == mute)
return new CompletedRestAction<>(getJDA(), null);
```
For my thought process debugging this, see: #1781
=> Enable unmuting suppressed users

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
This PR fixes some oversights for embed validation. Discord disallows embeds with no content (a space character or similar) and JDA didn't check this before sending the embed.
=> Fix embed length checks

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/events/interaction/GenericComponentInteractionCreateEvent.java, src/main/java/net/dv8tion/jda/api/interactions/components/ButtonInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/components/ComponentInteraction.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenuInteraction.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/interactions/ComponentInteractionImpl.java
This adds the EPHEMERAL and LOADING message flags, the ephemeral flag is particularly useful as you can't determine if a message is ephemeral by checking if `GenericComponentInteractionEvent#getMessage` is `null`
Also fixes docs for ComponentInteraction#getMessage and enables `editButton` and `editSelectionMenu` methods
=> Add interaction related message flags

src/main/java/net/dv8tion/jda/api/entities/Guild.java
The `Guild#retrieveBanById(long)` method displays some text like this:
> Retrieves a [Ban](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.Ban.html) if the provided ID
If you wish to ban or unban a user, use either [ban(String, int)](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#ban(java.lang.String,int)) ban(id, int)} or [unban(String)](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.html#unban(java.lang.String)) unban(id)}.
while it should be like this:
> Retrieves a [Ban](https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/entities/Guild.Ban.html) if the provided ID
If you wish to ban or unban a user, …
=> Fix minor link typo in retrieveBanById(long)

src/main/java/net/dv8tion/jda/api/Permission.java
Adds the "Use External Stickers" permission.
Adds the "Use external Emojis" permission to the list of text channel overrides
=> Adding external sticker permission and adding external emoji to text channel overrides

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Closes Issue: #1746
This pr implements the message interaction object <https://discord.com/developers/docs/interactions/slash-commands#message-interaction-object>
=> add Interaction Object for Messages

src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/internal/managers/ChannelManagerImpl.java
This provides ID-powered alternatives to `putPermissionOverride`/`removePermissionOverride` on `ChannelManager`. This allows for permissions to be safely modified on a channel without relying on an up-to-date cache.
Conspicuously missing is the ID-string equivalent to all of these methods, which I could add if needed but it doubles the number of new methods so I decided against it for now.
=> Create ID alternatives to permission override methods in ChannelManager

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
This PR adds the long overload to OptionData#addChoice while still keeping the int overload.
This is a fix for v4 that doesn't break the ABI Signature while still allowing longs to be added as choices.
PR for v5: #1816
=> Add long overload to OptionData#addChoice while still keeping the int overload

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
This PR adds the ephemeral field to attachments.
Its now possible to send attachments with ephemeral messages
https://github.com/discord/discord-api-docs/pull/3833
=> add ephemeral field to attachment 

src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java
Closes Issue: [CommandCreateAction varargs](https://github.com/DV8FromTheWorld/JDA/projects/5#card-68160683)
Adds missing varargs to subcommand and group methods in CommandCreateAction. Also adds methods that take collections for each
=> Add Missing Varargs and Methods Accepting Collection Arguments

src/examples/java/AudioEchoExample.java, src/main/java/net/dv8tion/jda/api/entities/VoiceChannel.java
This fixes the compile error introduced with the [change of GuildVoiceState#getChannel](https://github.com/DV8FromTheWorld/JDA/commit/47123047ad24965e6602ee0fa950222036d7a31f#diff-96be8e51fe5a0b0917f345357e6267ab47f0f6634bbecbcdcbe7d6809b7632e6L124-R124) returning a new class.
Furthermore I removed unnecessary extensions from the `VoiceChannel` interface.
=> Fix compile error of AudioEchoExample

src/main/java/net/dv8tion/jda/api/audit/AuditLogKey.java
This pull request adds the `CHANNEL_REGION` AuditLogKey
=> Add CHANNEL_REGION AuditLogKey

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/Permission.java, src/main/java/net/dv8tion/jda/api/entities/Emote.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildMessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/IMemberContainer.java, src/main/java/net/dv8tion/jda/api/entities/ListedEmote.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageReference.java, src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java, src/main/java/net/dv8tion/jda/api/managers/ChannelManager.java, src/main/java/net/dv8tion/jda/api/managers/PermOverrideManager.java, src/main/java/net/dv8tion/jda/api/requests/RestAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/entities/EmoteImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/managers/EmoteManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/RestActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
Added, removed and changed several Permissions.
- Removed `Permission.MESSAGE_READ` and used the existing `Permission.VIEW_CHANNEL` instead.
- Added `Permission.MESSAGE_SEND_IN_THREADS`.
- `Permission.USE_SLASH_COMMANDS` was renamed to `Permission.USE_APPLICATION_COMMANDS`.
- `Permission.MANAGE_EMOTES` was renamed to `Permission.MANAGE_EMOTES_AND_STICKERS`.
- `Permission.MESSAGE_WRITE` was renamed to `Permission.MESSAGE_SEND`.
- `Permission.USE_PUBLIC_THREADS` was renamed to `Permission.CREATE_PUBLIC_THREADS`.
- `Permission.USE_PRIVATE_THREADS` was renamed to `Permission.CREATE_PRIVATE_THREADS`.
Notes for users (can be copy pasted for Discord):
```
---
**`Permission.MESSAGE_READ` was removed** since it is the …
```
=> Update Permissions for JDA5

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Very rarely, discord sends us guilds with missing self members. This pull request adds a check for this case and a recovery attempt. We make a gateway request to load the self member after creating the guild object, which should in theory be able to recover the self member.
=> Add check and recovery for missing self members

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
This pull request makes `OptionData#addChoice` accept a `long` instead of an `int`
=> Make OptionData#addChoice accept long instead of int

src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java
Closes Issue: #1799 
This pull request fixes exception schema parsing if the `_errors` array is top-level instead of it being on a property
=> Fix exception schema parsing if _errors array is top-level

src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmoteHandler.java
Closes Issue: #1852
Fix a NumberFormatException, that occurred when receiving a `MESSAGE_REACTION_REMOVE_EMOJI`-event.
See [here](https://github.com/DV8FromTheWorld/JDA/issues/1852) for more details.
=> fix parsed type for "message_id"

src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Closes Issue: #1872 
Fixes `override(true)` not clearing the embeds on a message. My assumption is that discord treats `null` the same way as the field not being present, hence sending an empty array fixes it.
=> Fix overriding messages with embeds and components

src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
This PR adds the ability to get an application's Privacy Policy and Terms of Service URLs from the ApplicationInfo interface.
=> Add getPrivacyPolicyUrl() and getTermsOfServiceUrl() to ApplicationInfo

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/templates/TemplateGuild.java
I found a few places where the region of a guild is missing a deprecation. This was apparently forgotten in #1622 
This is required for the v4-lts. Methods will be removed with #1818
=> Deprecated all region usages for guilds

src/main/java/net/dv8tion/jda/api/entities/User.java
this PR adds the `BOT_HTTP_INTERACTIONS` flag to the `User.UserFlag` enum. this is just a consistency PR waiting for https://github.com/discord/discord-api-docs/pull/3903 to be merged.
=> add BOT_HTTP_INTERACTIONS user flag

src/main/java/net/dv8tion/jda/api/MessageBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
This PR replaces multiple magic numbers with the Message#MAX_CONTENT_LENGTH constant.
This makes updating JDA when the content length updates easier.
Just changing the constants value and the docs should be enough.
=> Updated magic numbers to use the Message#MAX_CONTENT_LENGTH constant

README.md, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/main/java/net/dv8tion/jda/api/JDAInfo.java
With this new logic, we can publish to maven central and jitpack.
If the version is bumped (e.g. 5.0.0 -> 5.0.1), we release the artifact to maven central and upload the jars to jenkins as usual.
If the version is not bumped and we only have a new commit, we only build the jars and javadoc on jenkins and append the commit hash (abbreviated to 7 chars) to the artifact version.
For people who are interested in using snapshot builds between version bumps, you can either use jitpack to get specific commit versions or download jars from jenkins. We do not intend to publish every single commit to maven central.
=> Change publishing logic

src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
Closes Issue: #1926
this PR fixes the check in GenericMessageEvent#getGuildChannel that would always throw.
=> fix wrong check in GenericMessageEvent#getGuildChannel

src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java
Adds a missing GenericMessageEvent#getThreadChannel() to v5
=> Add GenericMessageEvent#getThreadChannel()

src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectionMenu.java, src/main/java/net/dv8tion/jda/internal/interactions/SelectionMenuImpl.java
This makes `SelectionMenu#getOptions` return an unmodifiable list. This prevents user errors such as inserting `SelectOption`s in it, which would cause bugs as some internal variables wouldn't be updated
=> Make SelectionMenu#getOptions return an unmodifiable list

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Closes Issue: #1921
When trying to get the IPermissionContainer for a thread it now gets it from the parent to stop a ClassCastException.
=> Implement parent channel fetching when checking thread permissions

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/managers/GuildManager.java, src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Closes Issue: #1932
this PR removes `GuildManager#setVanityCode` as the vanity code can't be modified using the `Modify Guild` endpoint.
=> Remove GuildManager#setVanityCode

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Closes #1947 
This PR fixes parsing of the nullable `presence` field on `Thread Members Update` event.
=> Fix parsing of the nullable presence field on Thread Members Update

src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
Fixes: [JDA Discord message](https://canary.discord.com/channels/125227483518861312/125227483518861312/920470164498157618)
I targetted `legacy/v4` as it is a bugfix, hopefully this is the correct branch.
Calling icon.getEmoji() on a null icon will throw an NPE, this will pass null if the icon is null.
=> Fix NPE when cloning guild role with null icon

src/main/java/net/dv8tion/jda/api/interactions/commands/OptionMapping.java
If `CommandInteraction#getCommandString` is called when a `MENTIONABLE` option was included, `OptionMapping#getAsUser` and `OptionMapping#getAsRole` will always throw `IllegalStateException` regardless of the type of the resolved object.
=> Fix IllegalStateException for OptionType.MENTIONABLE

src/main/java/net/dv8tion/jda/api/entities/GuildMessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/entities/PrivateChannelImpl.java
Closes Issue: #1920
Move the canTalk() method from GuildMessageChannel to MessageChannel, which calls for an implementation in PrivateChannel since GuildMessageChannel already has a default one.
For that, I simply use the condition used in the private checkBot() method
This is my first ever pull request for this repository, so please tell me if I am doing anything wrong here, ty
=> Move canTalk() from GuildMessageChannel to MessageChannel

src/main/java/net/dv8tion/jda/api/utils/SessionController.java, src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
This pull request hardcodes Discord's gateway URL.
=> Hardcode gateway url

src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java, src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
Implements the retrieveThreadMember(ById) methods including their documentation
=> Implement retrieveThreadMember

src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java
Fixes that you can't "mix" options & subcommand (groups) after adding an empty set of these complementary types.
Only updates booleans for non-empty sets.
=> Only update CommandData limiting booleans for non-empty additions

src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IThreadContainerMixin.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadChannelPaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
```
Caused by: net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
- DATE_TIME_TYPE_PARSE: Could not parse 859166905289539625. Should be ISO8601.
at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633)
at net.dv8tion.jda.internal.requests.restaction.pagination.PaginationActionImpl.getNextChunk(PaginationActionImpl.java:339)
at net.dv8tion.jda.api.requests.restaction.pagination.PaginationAction$PaginationIterator.hasNext(PaginationAction.java:663)
at java.base/java.lang.Iterable.forEach(Iterable.java:74)
Caused by: net.dv8tion.jda.api.exceptions.ContextException
at …
```
=> [Bugfix] DATE_TIME_TYPE_PARSE: Could not parse 859166905289539625. Should be ISO8601.

src/main/java/net/dv8tion/jda/api/events/guild/GuildBanEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateAvatarEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateBoostTimeEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdateNicknameEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/member/update/GuildMemberUpdatePendingEvent.java
this PR clears up some guild events' documentation wording by prepending `(and) the` to `triggering guild`, making it sound less like an action.
=> Clear up some events' documentation wording

src/main/java/net/dv8tion/jda/api/events/interaction/GenericInteractionCreateEvent.java, src/main/java/net/dv8tion/jda/api/interactions/Interaction.java, src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
this PR adds `Interaction#getUserLocale` and `Interaction#getGuildLocale`. see https://github.com/discord/discord-api-docs/pull/4265. I'm not too sure about the behavior of `getGuildLocale` because there's a separate field for the preferred guild locale (however that is still only changeable with the `COMMUNITY` feature, effectively being `Guild#getLocale`), so feel free to comment on that. this is a fix for my previous PR that I fucked up by rebasing.
=> Add Interaction#getUserLocale and Interaction#getGuildLocale

src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
this PR changes the `MessageEmbed#getUrl` docs to mention that it may represent the title url if the type of the embed is `EmbedType#RICH`.
=> Change MessageEmbed#getUrl docs to mention representing the title url

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/StageChannel.java, src/main/java/net/dv8tion/jda/api/entities/StageInstance.java, src/main/java/net/dv8tion/jda/api/managers/StageInstanceManager.java, src/main/java/net/dv8tion/jda/api/requests/restaction/StageInstanceAction.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/StageChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/StageInstanceImpl.java, src/main/java/net/dv8tion/jda/internal/managers/StageInstanceManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/StageInstanceActionImpl.java
See [Card: Request to Speak](https://github.com/DV8FromTheWorld/JDA/projects/5#card-69504918)
=> Move requestToSpeak to StageChannel

src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
Fixes the modified set for the ThreadChannelManager to correctly mark that the invitable field has been set.  This previously set the bit for LOCKED being updated.
=> Fixes setInvitable in ThreadChannelManager

src/main/java/net/dv8tion/jda/api/entities/ICategorizableChannel.java
```11:59:55.263 JDA [0 / 3] MainWS-ReadThr WebSocketClient      ERROR  Got an unexpected error. Please redirect the following message to the devs:
JDA 5.0.0-alpha.4_ce738b9
CHANNEL_UPDATE -> {"nsfw":false,"bitrate":64000,"user_limit":0,"type":2,"guild_hashes":{"metadata":{"hash":"hashere"},"channels":{"hash":"hashere"},"roles":{"hash":"hashere"},"version":1},"rtc_region":null,"permission_overwrites":[{"allow":"1049616","deny":"0","id":"x","type":1},{"allow":"0","deny":"1048576","id":"x","type":0}],"last_message_id":null,"parent_id":null,"name":"🕐 10:59am UTC","guild_id":"x","position":31,"id":"x"}
java.lang.IllegalArgumentException: ID may not be null
at …
```
=> Restore behavior of zero being passed to find category rather than null

src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
this PR overrides `ISnowflake#getTimeCreated` for `ThreadChannel` with a field that is present in a Thread payload.
=> Override ThreadChannel#getTimeCreated

src/examples/java/SlashBotExample.java, src/main/java/net/dv8tion/jda/api/interactions/commands/CommandInteractionPayload.java, src/main/java/net/dv8tion/jda/api/interactions/commands/OptionMapping.java
Adds fallback methods which can be used to more easily handle optional command arguments without needing 3 lines of code:
```java
public void onSlashCommandInteraction(SlashCommandInteractionEvent event)
{
//                              name      fallback          resolver
// null if user is not a member of the guild (fallback not used, since option is mapped to a User instance)
Member member = event.getOption("target", event::getMember, OptionMapping::getAsMember);
// null if fallback is used (getAsUser cannot be null)
User user =     event.getOption("target", null            , OptionMapping::getAsUser);
// null fallback implied
User nullable = event.getOption("target", …
```
=> Add CommandInteractionPayload#getOption fallback overloads

src/main/java/net/dv8tion/jda/api/requests/restaction/GuildAction.java
Closes Issue: #2020 
This PR is a follow-up of issue #2020 to remove an excessive non-alphanumeric check put on GuildAction.ChannelData
=> Removed excessive non-alphanumeric check

src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/utils/MemberCachePolicy.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
- Introduces method Member.isBoosting() without allocation of OffsetDateTime, using class attribute boostDate.
- Adds MemberCachePolicy.BOOSTER featuring the new method isBoosting.
=> Add Booster to memberCachePolicy

src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java
Closes Issue: #2005 
This PR fixes the max file size upload limit in MessageAction. the `byte[]` overload now correctly checks for the guilds upload limit if applicable.
=> Fix max file size limit in MessageAction

src/main/java/net/dv8tion/jda/internal/handle/GuildDeleteHandler.java
There is a bug where if you kick a bot from a guild and then re-invite it, news channels would return null if fetched from the jda instance. I don't understand it fully but there might be objects of the newsChannel left when the bot is kicked because the GuildDeleteHandler wasn't cleaning the global cache from the news channels. This change fixes that bug.
Edit: Same thing applied to stage channels and thread channels, so I added those too.
=> Add missing cache cleanup for news/stage/thread channels

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/handle/MessageDeleteHandler.java
Closes Issue: #2009
The internal handle of the Message Deletion event no longer sets the LatestMessageIdLong to 0.
=> Dont override latest message id on deletion event

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
Changes the return type to `BaseGuildMessageChannel` because it can also be a news channel.
=> Make getDefaultChannel return BaseGuildMessageChannel

src/main/java/net/dv8tion/jda/api/Region.java, src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java
Closes Issue: #1961 
this PR removes some unused regions and adds a new `MILAN` region, which is not usable at the moment, but it's possible to get it in the client. the `SOUTH_KOREA` region is not listed in the regions endpoint (or in the client for that matter), but it's still applicable. this PR also removes the `VOICE_CHANNEL_REGIONS` collection, which is useless as of v5.
=> Change some voice Regions and remove VOICE_CHANNEL_REGIONS set

src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ComponentInteractionImpl.java
Put `guild_id` into MessageContextInteractionImpl's messages as Discord doesn't provide them
Discord message context menu events do not put `guild_id` into the message payload.  This PR will put that into the payload so that the EntityBuilder constructs the correct channel type surrounding it
=> Make Messages for Interactions properly reference their channels instead of PrivateChannel

src/main/java/net/dv8tion/jda/api/entities/MessageReference.java, src/main/java/net/dv8tion/jda/api/entities/NewsChannel.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ComponentInteractionImpl.java
Discord does not provide `guild_id` on message objects. We only ever get this property on messages when they come over the Websocket Gateway. However, historically, JDA has been written to expect it and we've gotten lucky that nothing broke.
Recently we made a change to enforce nullability of `getUser` on `PrivateChannel` and restructured some code to enable this along with filling in the data whenever we receive it, which happens to happen on `MESSAGE_CREATE`. This has revealed our erroneous reliance on `guild_id` in non-gateway situations.
This PR restructured the EntityBuilder to enforce upon developers of JDA's internal code that they must either have a channel instance or define if the …
=> Restructure message creation to handle a lack of guild_id

src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java
Closes Issue: NaN (see #1951)
Cherrypicks the fix for NPE when running Role#createCopy without icon into v5
=> Fix NPE when cloning guild role with null icon (v5)

src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java
Uses user data from the interaction if the user is not already cached.
Currently the @NonNull annotation on the getUser() method may return null, if the user was not cached but the private channel was.
=> Build the User from data in the Interaction if the User was not cached.

src/main/java/net/dv8tion/jda/api/entities/Activity.java
Corrects the documentation of Activity.listening(String) such that it specifies "Listening _to_" (rather than just "Listening") as the way it's displayed in the client.
=> Correct Activity.listening documentation

src/main/java/net/dv8tion/jda/api/MessageBuilder.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java, src/main/java/net/dv8tion/jda/api/entities/WebhookClient.java, src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/MessageEditCallbackAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageUpdateActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/MessageEditCallbackActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/ReplyCallbackActionImpl.java
This PR replaces magic number with a constant for the max-embed count on messages.
Need this constant personally for a bot, thus creating this PR.
=> Replace magic embed count number to constant

src/main/java/net/dv8tion/jda/api/interactions/callbacks/IAutoCompleteCallback.java
This PR replaces two faulty link tags with value tags in the `replyChoices` methods in the `IAutoCompleteCallback` interface.
Before:
After:
=> Replace faulty link with value in replyChoices docs

src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageBulkDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionBulkRemoveHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionClearEmoteHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java, src/main/java/net/dv8tion/jda/internal/handle/MessageUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java
This handles the messages received in voice channels by discarding the events for now. The handling of those messages will be added by #2072 
Since discord will most likely extend this to stage channels in the future, these changes are useful to prevent the same issues from occurring on that transition.
=> Handle message related events from unexpected channel types

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java
This pull request adds the `required` & `autoComplete` field of Command.Option to the corresponding equals() and hashCode() functions.
=> Add required & autoComplete in Command.Option to equals() & hashCode()

src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java
Closes Issue: #2068
This is a fix for issue #2068, I had another look and noticed that in other places we get the permission container from the guild channel, so I modified the logic here to do the same. This should be fine as we already check that the channel is from a guild since we cannot remove reactions in non-guild channels. I tested that this resolves the issue I was having.
=> Fix possible ClassCastException when removing reactions in threads

src/main/java/net/dv8tion/jda/internal/entities/RoleImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildRoleDeleteHandler.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java
This improves the user experience for RoleDeleteEvent and allows `Role#getPosition` to still be usable once it's detached from cache. This position value is naturally not accurate for long, but still good enough for informational purposes at the time of deletion. Like any other entity value, this drifts over time after detaching from cache.
Additionally, this optimizes `Role#canInteract(Role)` by not re-calculating positions for both roles each time. We can completely rely on `compareTo` as this is only a relative comparison, rather than absolute positions.
=> Improve handling of Role#getPosition and canInteract

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
this PR transforms the hardcoded jump url format into a constant in the `Message` interface. this can be useful for users who need it for something else.
=> transform hardcoded jump url format into a constant

src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
This pull request adds `getTags()`, `getCustomAuthorizationUrl()`, `getPermissions()` and `getScopes()` to `ApplicationInfo`
=> Add Tags, Default Install Url, Scopes and Permissions to ApplicationInfo

src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java
See https://github.com/discord/discord-api-docs/issues/4734
All new Discord client's have dropped support for sending member mentions with !
They still accept mentions with !, it's just that sending has been removed.
See https://github.com/discord/discord-api-docs/issues/4734, or to be exact https://github.com/discord/discord-api-docs/issues/4734#issuecomment-1086156692 for more info.
=> Remove mentioning members with !

src/main/java/net/dv8tion/jda/internal/requests/ratelimit/BotRateLimiter.java
Closes Issue: [2079](https://github.com/DV8FromTheWorld/JDA/issues/2079)
Clears out empty buckets (with 0 requests) when the BotRateLimiter is stopped
=> Fix rate limiter not shutting down if there is an empty bucket at shutdown

src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/DelayRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/MapRestAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/RestActionOperator.java
Closes Issue: #2042 
This adds a try/catch abstraction to handle any exceptions from user-land operator functions.
=> Add try/catch abstraction for RestAction operators

.github/CONTRIBUTING.md, src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
This PR fixes the following typos:
- In `GatewayIntent.java`
- Changed `If an intent is not specifically mentioned to be privileged, it is not required to be on the whitelist to use if` to `If an intent is not specifically mentioned to be privileged, it is not required to be on the whitelist to use it`
- In `CONTRIBUTING.md`
- Changed point number 4 to direct users to only open pull requests to `master` (see [relevant discussion in lib-dev](https://discord.com/channels/125227483518861312/869965829024915466/965832052979150849))
=> Fix typos in GatewayIntent Javadoc and contributing guidelines

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java
this PR adds a check to `OptionData` constructor which prevents successfully creating an instance with `OptionType#UNKNOWN` (prevents things like #2100 from happening).
=> prevent creating OptionData with OptionType#UNKNOWN

src/main/java/net/dv8tion/jda/api/entities/IPermissionContainer.java, src/main/java/net/dv8tion/jda/api/entities/PermissionOverride.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/attribute/IPermissionContainerMixin.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
This removes `channel.putPermissionOverride` and `channel.createPermissionOverride` which can be replaced by `upsertPermissionOverride`. You can still clear the permissions of the override this way by using `clear(...)`.
=> Remove confusing permission override methods

src/main/java/net/dv8tion/jda/internal/utils/config/MetaConfig.java
Closes Issue: #2109
The ternary was incorrectly setting the map to null instead of the parameter.
=> Fix broken context map config

src/main/java/net/dv8tion/jda/api/entities/Guild.java
this PR adds a mention to Guild#getBoosters docs that the method requires the members to be cached.
=> mention that Guild#getBoosters requires member cache in the docs

src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java, src/main/java/net/dv8tion/jda/internal/entities/GuildVoiceStateImpl.java
The `declineSpeaker` method is also used to move speakers back to the stage audience.
=> Improve check for GuildVoiceState#declineSpeaker

src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
- Currently, `ErrorResponse#test(ErrorResponse...` produces an `EnumSet` of the responses, which it then passes to `ErroResponse#test(Collection`
- That method however, creates another `EnumSet`, which is unnecessary processing.
- To fix that, this PR will create its own predicate without calling the other method.
=> Remove unnecessary processing in `ErrorResponse#test(ErrorResponse...`

src/main/java/net/dv8tion/jda/api/managers/channel/concrete/ThreadChannelManager.java, src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ThreadChannelActionImpl.java
Discord removed the unlockable duration of three / seven days of auto archiving.
=> Remove checks for archive durations

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/ThreadChannel.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java
Closes Issue: #2092
Adds a `getStartedThread()` method to the Message object to provide a method that returns the Thread that was started from the message (if one exists).
Example:
```Java
Message message = //retrieve the message somehow
ThreadChannel thread = message.getStartedThread();
if (thread != null) {
System.out.println(thread.getName());
thread.sendMessage("Hello thread people!").queue();
}
```
=> Add Message#getStartedThread and ThreadChannel#retrieveParentMessage

src/main/java/net/dv8tion/jda/api/events/message/GenericMessageEvent.java, src/main/java/net/dv8tion/jda/api/events/message/react/GenericMessageReactionEvent.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
This PR adds a getJumpUrl method to the `GenericMessageReactionEvent`, as you had to create your own method for this before.
=> Added getJumpUrl method to GenericMessageEvent

src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/InteractionCallbackAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/MessageEditCallbackAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/ReplyCallbackAction.java, src/main/java/net/dv8tion/jda/api/utils/AttachedFile.java, src/main/java/net/dv8tion/jda/api/utils/AttachmentUpdate.java, src/main/java/net/dv8tion/jda/api/utils/FileUpload.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/InteractionCallbackImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/MessageEditCallbackActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/ReplyCallbackActionImpl.java
This changes the internal code used for handling file uploads in message requests. We are introducing a new utility class, which is planned to be utilized for both stickers and message sending.
Creating stickers:
```java
//                  name        file                                      tags
guild.createSticker("catLoser", FileUpload.fromData(new File("cat.png")), "cat", "animal").queue();
```
```java
List<AttachedFile> attached = new ArrayList<>();
// Add files to keep attached (blame discord, you have to list all in v10 if you want to add a single new file)
message.getAttachments()
.stream()
.map(AttachedFile::fromAttachment)
.forEach(attached::add);
// Add new file ontop …
```
=> Add FileUpload class

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/GuildMembersChunkHandler.java, src/main/java/net/dv8tion/jda/internal/requests/MemberChunkManager.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadChannelPaginationActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Helpers.java
Follow-up requests of ThreadChannelPaginationAction had duplicated `before` request parameters,
while discord only read the first (invalid) one provided by PaginationAction route finalization.
```
net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
- DATE_TIME_TYPE_PARSE: Could not parse 968844240228585543. Should be ISO8601.
```
=> [Bugfix] retrieving public archived threads

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
With this change, the `ChunkingFilter` no longer overwrites `MemberCachePolicy`. The reason this was originally implemented this way was due to the way chunking worked in the past. Back when it was implemented, there was no reliable way to check which chunk is the last in the sequence. Discord has since improved this API and we can now reliably chunk without checking the member count.
This change improves user-experience by disentangling the member loading from member caching.
I tested this locally and could not notice any issues with this change. However, it would be nice if others could test as well.
To recover the previous behavior, you must use `setMemberCachePolicy(MemberCachePolicy.ALL)` …
=> Do not ignore member cache policy when chunking is enabled

src/main/java/net/dv8tion/jda/api/entities/Message.java
Fixes `Message.Attachment#getProxy()`, the proxy url returns status code 415 (unsupported media type) for non-image attachments.
=> Fix Message.Attachment#getProxy()

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
This PR provides a previously missing `guildId` parameter within `Route.Stickers.DELETE_GUILD_STICKER.compile`, which previously threw an error when compiling the route.
=> Fix missing guild id when deleting guild stickers

src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Getting a Guilds channels using Guild#getChannels(boolean) always returns an empty list when giving false as the filter for excluding hidden channels always returns false due to a missing return statement. This PR fixes this by adding this missing return statement.
=> Fix filterHidden in GuildImpl#getChannels

src/main/java/net/dv8tion/jda/api/entities/MessageChannel.java
This replaces mentions of `TextChannel` in the documentation with `GuildMessageChannel`. As far as I can tell `MessageChannel#getHistory` does not support other types than TextChannel yet, but there is a TODO comment for it so I've included it.
=> Replaced occurrences of TextChannel with GuildMessageChannel

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/AbstractMessage.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Changes the return type of Message#createThreadChannel to ThreadChannelAction to allow chaining.
=> Return ThreadChannelAction instead of RestAction on Message#createThreadChannel

src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/BanPaginationActionImpl.java
Closes #2199 
This fixes pagination for `Guild#retrieveBanList`. The problem was that backwards iteration has to explicitly tell it to start before the newest ID (since it is descending rather than ascending in that case).
=> Fix ban pagination

src/main/java/net/dv8tion/jda/api/requests/restaction/CacheRestAction.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
This makes `retrieveMemberById(id).useCache(true)` always rely on cache, even when its outdated.
=> Improve usage of cache in Guild#retrieveMemberById

src/main/java/net/dv8tion/jda/api/entities/ApplicationInfo.java, src/main/java/net/dv8tion/jda/internal/entities/ApplicationInfoImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Adds access to application flags.
=> Add ApplicationInfo#getFlags

src/main/java/net/dv8tion/jda/internal/interactions/command/CommandAutoCompleteInteractionImpl.java
This caused a StackOverflowException, since getMessageChannel just calls getChannel.
=> Fix CommandAutoCompleteInteraction#getChannel

src/main/java/net/dv8tion/jda/api/requests/restaction/ChannelAction.java, src/main/java/net/dv8tion/jda/internal/entities/StageChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Closes Issue: #2208 
This PR adds support for users to set the voice region of audio channels on creation/copy. Closes #2208 
```java
// also works with `createStageChannel`
guild.createVoiceChannel("brazil").setRegion(Region.BRAZIL)  // creates a voice channel, with Brazil region
.flatmap(channel -> channel.createCopy().setName("brazil 2"))  // creates a second voice channel, also Brazil region
.queue();
```
=> Add support for setting voice region on channel creation/copy

src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
Closes Issue: [#2224](https://github.com/DV8FromTheWorld/JDA/issues/2224)
Renames `MessageCreateBuilder#fromEdit()` to `MessageCreateBuilder#fromEditData()` for consistent naming between `MessageCreateBuilder` and `MessageEditBuilder`.
=> Renamed MessageCreateBuilder#fromEdit() to fromEditData

README.md, src/examples/java/AudioEchoExample.java, src/examples/java/MessageLoggerExample.java, src/examples/java/SlashBotExample.java, src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/exceptions/InvalidTokenException.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/api/utils/SessionControllerAdapter.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/utils/InvalidTokenException.java
Replaces `LoginException` with `InvalidTokenException`
TODO:
Closes issue: https://github.com/DV8FromTheWorld/JDA/projects/5#card-75890666
=> Invalid token exception

src/examples/java/SlashBotExample.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/api/requests/restaction/AuditableRestAction.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
You can now ban with a deletion history of seconds precision (used to be only days).
For reference: discord/discord-api-docs#5219
=> Add support for ban deletion with seconds precision

src/main/java/net/dv8tion/jda/api/utils/FileProxy.java
Fixes bug with resolving parent directory of paths for `FileProxy`
```java
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
at java.base/java.nio.file.Files.provider(Files.java:105)
at java.base/java.nio.file.Files.exists(Files.java:2520)
at net.dv8tion.jda.api.utils.FileProxy.downloadToPath(FileProxy.java:202)
at net.dv8tion.jda.api.utils.FileProxy.downloadToPath(FileProxy.java:310)
at net.dv8tion.jda.api.utils.FileProxy.downloadToPath(FileProxy.java:196)
at net.dv8tion.jda.api.utils.FileProxy.downloadToPath(FileProxy.java:256)
```
Caused by `path.getParent()` being used on `Paths.get("thumbnail.jpg")` which is a relative path without …
=> Use toAbsolutePath in FileProxy#downloadToPath

src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java, src/main/java/net/dv8tion/jda/api/utils/data/DataPath.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/InteractionCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/ReadyHandler.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandInteractionPayloadImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/ContextInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/MessageContextInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/UserContextInteractionImpl.java, src/test/java/DataPathTest.java
This new util class allows to access deep nested fields with a simple path expression.
```java
long value = DataPath.getLong(object, "data.options[0].value");
```
This also allows safe-calls similar to kotlin via `?.` delimiters:
```java
long value = DataPath.getLong(object, "data?.options?[0]?.value?", 0L);
```
This would be equivalent to:
```java
long value = 0L;
DataObject data = object.optObject("data").orElse(null);
if (data != null)
{
DataArray options = data.optArray("options").orElse(null);
if (options != null)
value = options.getLong("value", 0L);
}
```
I'm sure you can see the appeal.
This is very useful in various places, and now also relevant in the case of `Event#getRawData` which …
=> Add DataPath util

src/main/java/net/dv8tion/jda/api/utils/data/etf/ExTermDecoder.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java
This slightly reduces latent memory usage and improves performance of map lookups for ETF data. Guild features are a small limited list of possible feature strings that we can intern to reduce duplication.
=> Use String#intern for guild features and atoms

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
This changes the retry handling for server errors to only retry on a few specific codes. Additionally, the retries now use an exponential backoff instead of linear.
There also were some methods which apply body and headers, which are now used instead.
=> Improve handling of server errors and fix some code duplication

src/main/java/net/dv8tion/jda/internal/entities/ThreadChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/mixin/channel/middleman/GuildChannelMixin.java, src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/managers/channel/concrete/ThreadChannelManagerImpl.java
Closes Issue: https://github.com/DV8FromTheWorld/JDA/issues/2188
Replaces PR: https://github.com/DV8FromTheWorld/JDA/pull/2190
When calling `ThreadChannel#getManager` or `ThreadChannel#delete` it is currently checked if the user has the `MANAGE_CHANNEL `permission, but the permission actually required to manage or delete a thread is `MANAGE_THREADS`.
Additionally, when the bot owns the thread, it doesn't matter whether they have `MANAGE_THREADS` or not.
=> Properly handle MANAGE_THREAD permission for managing threads

src/main/java/net/dv8tion/jda/api/requests/RestAction.java
Added ~~two~~ one new user-facing convenience method on `RestAction`, ~~`accept` and `also`~~ `onSuccess`. It represents a frequent scenario on action-chaining that otherwise requires cumbersome workarounds for the user.
The method works like `map`, but results in a `RestAction<T>`, continuing with the previous result. It just consumes the given result, but allows continuation of the action-chain:
```java
guild.retrieveMemberById(userId) // RestAction<Member>
.onSuccess(System.out::println)   // RestAction<Member>
.flatMap(any -> channel.sendMessage("Done"))
.queue()
```
This enables users to chain in `void` methods.
The workaround without this helper would be:
```java …
```
=> Added RestAction#onSuccess

build.gradle.kts
Updates the scope to compileOnly for annotation dependencies. Saves about 20kB on the fat jar artifact.
This is breaking for anyone who relied on these being provided by JDA.
=> Make annotation dependencies compileOnly

src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Fixes a regression which broke Guild#createCategory due to setting category. Instead of changing the logic for that, I made sure to only throw if the parent is not null.
=> Fix check for ChannelAction#setCategory

src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java
The message create action used a random "flags" field that was not modified anywhere. The correct field to use is "messageFlags", found in `AbstractMessageBuilder`. This fixes a bug where you could not suppress embeds on message create.
```java
// Send a message with suppressed embeds
channel
.sendMessageEmbeds(new EmbedBuilder().setDescription("whatever").build())
.setEmbedsSuppressed(true)
.queue();
// Send normal embeds
channel
.sendMessageEmbeds(new EmbedBuilder().setDescription("This should not be suppressed").build())
.queue();
```
=> fix: Use correct "flags" field for message create action

src/main/java/net/dv8tion/jda/api/entities/channel/forums/ForumTag.java
This was an oversight. Making it extend ForumTagSnowflakes allows for these tags to be applied to posts.
=> Make ForumTag extend ForumTagSnowflake

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ForumTagImpl.java, src/main/java/net/dv8tion/jda/internal/handle/ChannelUpdateHandler.java
Apparently, sometimes this is 0 instead of null.
=> Handle emoji_id sometimes being 0 instead of null

src/main/java/net/dv8tion/jda/api/interactions/commands/OptionType.java, src/main/java/net/dv8tion/jda/api/interactions/commands/localization/LocalizationFunction.java, src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java
Puts an "options" key between the command path and the option, as well as "choices" between the option and the choice
This helps reading localization files such as JSON or YAML as option names aren't on the same indent as other command-related strings, as well as making it explicit that the user is modifying an option/choice's localization
Related convo: https://discord.com/channels/125227483518861312/869965829024915466/1023634607360462938
=> Put "options" between command path and options, same for choices

src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/utils/config/AuthorizationConfig.java
`JDAImpl` was doing unnecessary checks and could had been implemented where the token comes from, so, `AuthorizationConfig`, the PR moves the `notEmpty` check there
=> Check for empty token in AuthorizationConfig, instead of JDAImpl

src/main/java/net/dv8tion/jda/api/entities/sticker/GuildSticker.java, src/main/java/net/dv8tion/jda/internal/entities/sticker/GuildStickerImpl.java
Closes #2315
This was using the wrong endpoint, causing user to always be null.
=> Fix GuildSticker#retrieveOwner

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/utils/cache/MemberCacheViewImpl.java
Closes Issue: #2291
Fixes an issue that caused `MemberCacheViewImpl#getElementsWithRoles` to return an empty list when given the public role.
=> Fix MemberCacheViewImpl#getElementsWithRoles and Guild#findMembersWithRoles ignoring the public role

src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java, src/main/java/net/dv8tion/jda/internal/entities/ForumChannelImpl.java
same as title, allows topic (guidelines) updates to be handled via events.
=> [Bugfix] Mark ForumChannel as a TopicChannelMixin

src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/utils/ShutdownReason.java
This provides the context of shutdowns to the exceptions throw by `awaitStatus`:
```
Exception in thread "main" java.lang.IllegalStateException: Was shutdown trying to await status.
Reason: You tried turning on an intent you aren't allowed to use. For more information check https://jda.wiki/using-jda/troubleshooting/#im-getting-closecode4014-disallowed-intents
at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:494)
at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:324)
at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:374)
```
=> Forward shutdown reason to awaitStatus exception

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
These webhooks should allow missing channels.
=> Fix JDA#retrieveWebhookById

src/main/java/net/dv8tion/jda/internal/handle/ThreadUpdateHandler.java
This will remove archived threads from the cache. You can use [Guild#retrieveArchivedPublicThreadChannels](https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.html#retrieveArchivedPublicThreadChannels()) to get them again.
Since thread cache is necessary to handle update events, those events will no longer function for archived threads. However, that was partially the case anyway, since archived threads were discarded already on invalidation (or startup).
=> Remove archived threads from cache

src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectInteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/StringSelectInteractionImpl.java
When clearing an entity select menu, the resolved is omitted for the interaction event. This caused parsing exceptions because of `getObject(..)` asserting it to be present.
=> Fix handling of empty select menu interactions

src/main/java/net/dv8tion/jda/api/interactions/commands/Command.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java, src/main/java/net/dv8tion/jda/api/requests/restaction/CommandCreateAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/CommandEditAction.java, src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandEditActionImpl.java
See https://support.discord.com/hc/en-us/articles/10123937946007
Docs PR: discord/discord-api-docs#5617
=> Add support for age-restricted (nsfw) commands

src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPositionableChannel.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractGuildChannelImpl.java
This improves how `getPosition` and `GuildChannel#compareTo` work. Here is the updated code output for `(guild.channels + guild.threadChannels).sorted()`, which includes threads to show comparing works between them and normal channels as expected:
=> Improve GuildChannel#getPosition and Guild#getChannels

src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/attribute/IThreadContainerMixin.java
Discord recently removed the boost gate on private thread creation, but JDA still had a check causing an erroneous short circuit.
=> Remove outdated feature check for private threads

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/entities/SystemMessage.java
Closes Issue: #2311 
Adds `Message#getApplicationId` and `Message#getApplicationIdLong` to easily tell which bot sent the message without the need to look up webhooks.
=> Add application_id support for received messages

src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java, src/main/java/net/dv8tion/jda/api/requests/restaction/pagination/ThreadMemberPaginationAction.java, src/main/java/net/dv8tion/jda/api/utils/data/DataObject.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/ThreadMembersUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ThreadMemberPaginationActionImpl.java
Closes #1991
This adds support for paginated thread members.
=> Implement thread member pagination

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Updates the Wiki URLs in `.github/ISSUE_TEMPLATE/config.yml`, `.github/CONTRIBUTING.md` and `.github/PULL_REQUEST_TEMPLATE.md` to the new ones located at https://jda.wiki
=> Update Wiki URLs to new wiki site

src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
There must have been some stealth changes on Discords part when updating a scheduled event, because in the current implementation we get an error for invalid form body when setting the location to a voice or stage channel if we do not provide null for the entity_metadata field. This was redundant before.
This PR also fixes a "bug" when changing the location to an external one without providing a new end time. It did not take into account that the event can already have an end time set **even though** it was a voice or stage channel event. This might've been a stealth change by Discord as well, because I don't remember it being possible to set the end time on voice or stage channel events. Now you can do that via the API, but not (yet?) via the UI.
=> Fix bug when updating a scheduled events location

src/main/java/net/dv8tion/jda/api/entities/channel/attribute/ISlowmodeChannel.java
Seems only logical to me to be able to use the generic manager, so you don't have to cast to 3 specific slow mode channels (Text, Thread or Forum).
```java
public static void announce(StandardGuildMessageChannel channel, Role role, MessageCreateData message, boolean slowmode)
{
if (slowmode && channel instanceof ISlowmodeChannel)
{
ISlowmodeChannel slow = (ISlowmodeChannel) channel;
ISlowmodeChannelManager<?, ?> slowMan = (ISlowmodeChannelManager<?, ?>) slow.getManager(); // currently resolves to ChannelManager and requires an unchecked cast
slowMan.setSlowmode(30).queue(v -> slowMan.setSlowmode(0).queueAfter(2, TimeUnit.MINUTES));
}
role.getManager().setMentionable(true)                  // make role …
```
=> Add generic slowmode channel manager to slowmode channel interface

src/main/java/net/dv8tion/jda/internal/managers/ManagerBase.java
Fixes an issue where `setPinned` and `setTagRequired` were not functioning as intended. The update check uses `shouldUpdate(PINNED | REQUIRES_TAG)`, which would make it require both with the previous logic.
=> Fix issues with ChannelManager#setPinned and setTagRequired

src/main/java/net/dv8tion/jda/api/interactions/commands/build/CommandData.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SlashCommandData.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandData.java, src/main/java/net/dv8tion/jda/api/interactions/commands/build/SubcommandGroupData.java, src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandCreateActionImpl.java
This moves the serialization of options into `toData()`, which removes the need to reconstruct them for getters. Additionally, I've added some more constants to replace the magic numbers in checks.
=> Improve implementation of command data

src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/AuditLogPaginationActionImpl.java
This allows using `guild.retrieveAuditLogs().reverse()`, iterating from the oldest entry to the newest. ~~(Currently broken due to wrong implementation of `?after=0` in the API)~~
Reference: discord/discord-api-docs#5821
=> Add support for reverse audit-log iteration

src/main/java/net/dv8tion/jda/api/audit/AuditLogEntry.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildAuditLogEntryCreateEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildBanEvent.java, src/main/java/net/dv8tion/jda/api/events/guild/GuildUnbanEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/handle/GuildAuditLogEntryCreateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
This event allows to easily keep track of audit log entries.
Reference: discord/discord-api-docs#5849
=> Add GuildAuditLogEntryCreateEvent

src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Closes Issue: #2405 
This fixes an issue where errors thrown by `complete()` would prevent a graceful cleanup during token validation.
=> Catch errors thrown during login validation

src/main/java/net/dv8tion/jda/api/interactions/commands/build/OptionData.java
This PR fixes `OptionData` throwing a NPE when users attempted to add choices on an option which doesn't support them.
It also prevents instantiation of `OptionData` with the subcommand(group) type, as far as i can tell, JDA does not do such thing
=> Fix NPE when adding choices on unsupported option types

README.md
The docs here are a little outdated, and the new example is more reliable.
=> Update docs for entity lifetimes

src/main/java/net/dv8tion/jda/api/events/guild/GuildBanEvent.java
This pull request fixes the documentation of GuildBanEvent where Requirements were stuck inside the "See Also" tab, also fixing the GatewayIntent link.
=> Fix docs in GuildBanEvent

src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java, src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
Closes Issue: #2455 
Setting this timeout does not make sense in our current shutdown logic. And the docs for the executor specifically say this is not a good idea. The requester shutdown will also shutdown the pool explicitly.
=> Remove timeout for rate-limit pool

src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
Slightly improves how we handle global rate-limit backoff. We were always prioritizing the global rate-limit, even when it's shorter than the bucket limit. With this change, we will always use whichever limit is greater.
I've also added implementations for hashCode and equals, to handle potential regressions with duplicated bucket instances.
=> Improve handling of global rate-limit

src/main/java/net/dv8tion/jda/api/utils/MarkdownSanitizer.java, src/test/java/MarkdownTest.java
Closes Issue: #2358 
Fixes an issue that caused quotes with leading spaces to not be escaped.
=> Properly escape quotes with leading spaces

src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java
The question "how to get forum post start message" seems to come up a lot. Most people seem to think that `retrieveParentMessage()` will give that initial message.
=> Add ThreadChannel#retrieveStartMessage

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/hooks/AnnotatedEventManager.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
Replaces #1878
This PR will incrementally update the `AnnotatedEventManager`'s registered methods when registering a listener, and throw if an annotated's method signature is invalid or an array is being passed as a listener.
Also changes internals so `JDA#addEventListener` is not called on every registered listener
=> Improve handling of method discovery in AnnotatedEventManager

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/test/java/net/dv8tion/jda/entities/MessageSerializationTest.java
Now, you can use `EmbedBuilder.fromData(json)` to create an instance of `EmbedBuilder` from a JSON object. This is simply the inverse of `MessageEmbed#toData`, which already existed.
=> Support embed deserialization from JSON data

.github/workflows/artifacts.yml
This adds a new github action workflow to automatically build and upload artifacts on each push to master.
An example run is here: https://github.com/MinnDevelopment/JDA/actions/runs/2966524280
Artifacts are retained for 90 days.
=> Use github actions to publish artifacts

.github/workflows/docs.yml
This adds a github action to deploy javadocs as github pages.
To use this the repository settings need to be updated:
1. Open [Pages Settings](https://github.com/DV8FromTheWorld/JDA/settings/pages)
2. Set the source to **GitHub Actions**
3. Optionally configure a custom domain
This is one of the first steps towards independence from jenkins.
On push to master, this will deploy the updated documentation under `dv8fromtheworld.github.io/JDA` or on the custom domain. For example, my discord-webhooks project is hosted this way on https://minndevelopment.github.io/discord-webhooks/overview-tree.html
=> Create github pages deploy for javadocs

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/SelfUserImpl.java, src/main/java/net/dv8tion/jda/internal/entities/UserImpl.java
Since discord now returns discriminators of length 1 our equality check was wrong. This caused update events to fire unintentionally.
=> Fix handling of wrong length discriminators

src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
Previously JDA would throw when attempting to change the location of a started scheduled event with an external location. The API allows changing the external location to another external location. What it does not allow is changing the location type after the event has already started. It also does not allow to change the channel of a started event if the location type is set to voice or stage. This commit corrects this and now allows editing of the external location value for a started scheduled event.
I also removed a redundant check, I don't recall why I put it there in the first place but it is not needed, so I assume I did it by mistake.
=> Fix external location value to be editable on started scheduled event

src/main/java/net/dv8tion/jda/internal/entities/automod/AutoModExecutionImpl.java
Closes Issue: #2482
This fixes an issue where `AutoModExecutionImpl` did not account for automod rules without an associated `channel_id`
=> Fix automod execution errors from rules without an associated channel

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
This erroneously assumed that clyde is the channel recipient.
=> Handle clyde in DMs correctly

src/main/java/net/dv8tion/jda/internal/handle/ThreadCreateHandler.java, src/main/java/net/dv8tion/jda/internal/handle/ThreadUpdateHandler.java
When the parent channel is missing, we should cache the thread update.
=> Fix handling of thread update for unknown parent

src/main/java/net/dv8tion/jda/api/audio/hooks/ConnectionListener.java, src/main/java/net/dv8tion/jda/api/audio/hooks/ListenerProxy.java, src/main/java/net/dv8tion/jda/internal/audio/AudioWebSocket.java
This replaces the old `onUserSpeaking` methods from the `ConnectionListener`. This behavior has changed a long time ago ([see docs pr](https://github.com/discord/discord-api-docs/pull/5576)).
=> Deprecate and replace onUserSpeaking

src/main/java/net/dv8tion/jda/api/events/message/react/MessageReactionAddEvent.java, src/main/java/net/dv8tion/jda/internal/handle/MessageReactionHandler.java
This is now available on message reaction add events. And no, it is not present on other events.
Reference: https://github.com/discord/discord-api-docs/pull/6102
=> Add the message author id to message reaction events

src/main/java/net/dv8tion/jda/api/JDA.java
* Changed the return type of "openPrivateChannelById(String)" from RestAction to CacheRestAction as it delegates to a method that returns CacheRestAction.
The return type of `JDA#openPrivateChannelById(long)` is `CacheRestAction`. However, the method `JDA#openPrivateChannelById(String)` returns `RestAction`, implying that the cache will not be used. This seems inconsistent, especially considering that the String method delegates to the long method.
Also changed the documentation of `JDA#openPrivateChannelById(String)` to clarify that the cache will be used.
=> Chage return type of method in JDA class.

src/main/java/net/dv8tion/jda/internal/interactions/command/localization/LocalizationMapper.java, src/test/java/LocalizationTest.java, src/test/resources/MyCommands_fr.properties
Fixes automatic localization adding "options" before the choice name
=> Fix choices having an "options" prefix when automatically localizing

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
Closes Issue: #2509 
According to the documentation `Message#getCategory` should return null for DMs instead of throwing an exception.
=> Fix IllegalStateException in Message#getCategory

src/main/java/net/dv8tion/jda/api/utils/FileUpload.java, src/main/java/net/dv8tion/jda/internal/utils/IOUtil.java, src/main/java/net/dv8tion/jda/internal/utils/requestbody/BufferedRequestBody.java, src/main/java/net/dv8tion/jda/internal/utils/requestbody/DataSupplierBody.java, src/main/java/net/dv8tion/jda/internal/utils/requestbody/TypedBody.java
This adds support for uploading files using source suppliers.
When JDA reads a resource to upload files in a request, it always has to keep a copy in memory in case the request fails. This is because we might have to upload the same data again if the request fails due to a rate-limit or I/O error.
This new supplier-based `FileUpload` instead creates a new readable source for each time it needs to upload the data. With this approach, we can avoid copying the entire resource into memory, and instead stream it in segments.
This optimization is especially useful if you try to upload multiple attachments or large files.
=> Add supplier based FileUpload

src/main/java/net/dv8tion/jda/api/entities/Activity.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/managers/PresenceImpl.java
Implements support for custom status in bots. This was rolled out about an hour ago on the API side and I have tested it with my own bot.
=> Add custom status support for bots

src/main/java/net/dv8tion/jda/api/entities/Activity.java
I added support for ``ActivityType.CUSTOM_STATUS`` to use in ``Activity.of(...)`` .
=> Added support for custom statuses

src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java
The contract of [`Object#equals`](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Object.html#equals(java.lang.Object)) specifies:
> It is _symmetric_: for any non-null reference values `x` and `y`, `x.equals(y)` should return `true` if and only if `y.equals(x)` returns true.
This should hold when calling `equals` on an instance of `RichCustomEmojiImpl` and `CustomEmojiImpl`.
This is because `CustomEmojiImpl` [allows any `CustomEmoji`](https://github.com/discord-jda/JDA/blob/c0582c5f397517d42bf73f156c1bf89147771aa4/src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java#L103) and checks the id while `RichCustomEmojiImpl` [expects a …
=> fix symmetricity of CustomEmojiImpl/RichCustomEmojiImpl#equals

src/main/java/net/dv8tion/jda/internal/managers/channel/ChannelManagerImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java
Closes Issue: https://github.com/discord-jda/JDA/issues/2537
So, with the following piece of code jda throws an error: 
```java
public static void main(String[] args) {
Guild guild =...;
guild.createStageChannel("name").setNSFW(true).setSlowmode(100).queue();
guild.createVoiceChannel("name").setNSFW(true).setSlowmode(100).queue();
}
```
Which should not happen, because discord supports NSFW & Text in Stage channels.
=> Allow slowmode & nsfw in Stage Channels

src/main/java/net/dv8tion/jda/internal/requests/Requester.java
Changed the ```applyHeaders``` method in the ```Requester``` class, so that custom headers with the same name in custom requests override the headers applied by default. This is useful if you want to override the "Authorization" header for example in a custom OAuth2 request, that needs another value for this header. The previous behaviour in this case caused there to be two "Authorization" headers in the request, which in turn lead to a HTTP 400 error being returned by the Discord API.
=> Allow override of headers applied by default

src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java, src/main/java/net/dv8tion/jda/internal/interactions/component/EntitySelectMenuImpl.java, src/test/java/net/dv8tion/jda/interactions/SelectMenuTests.java
This adds support for setting up to 25 default values for a EntitySelectMenu.
Reference: https://github.com/discord/discord-api-docs/pull/6442
=> Add default_values support

src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
Fixed that `EntitySelectMenu#createCopy` didn't copy `DefaultValues`,
=> Fix createCopy not copying DefaultValues

src/main/java/net/dv8tion/jda/api/utils/data/DataArray.java
`DataArray.fromCollection(Arrays.asList("definitely not a timestamp")).getOffsetDateTime(0)` throws a MissingFormatArgumentException
=> Fix MissingFormatArgumentException in DataArray#getOffsetDateTime

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/validate.yml
This PR corrects some links in `.github`:
* `https://github.com/DV8FromTheWorld/JDA` -> `https://github.com/discord-jda/JDA`
* `https://ci.dv8tion.net/job/JDA/` -> `https://ci.dv8tion.net/job/JDA5/`
* `https://help.github.com/*` -> `https://docs.github.com/*`
* Other
One of the main problems is outdated documentation (`https://ci.dv8tion.net/job/JDA/javadoc/`) in issue templates config and a redirects some `https://help.github.com/*` links to `https://support.github.com/` main page.
=> Fix outdated links in .github

src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageCreateActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageEditActionImpl.java
Fixes: #2571
Webhooks set `thread_id` in the request body when it's actually a route query param.
=> Fix webhook send & edit where the thread ID was set

src/main/java/net/dv8tion/jda/internal/requests/restaction/WebhookMessageCreateActionImpl.java
https://github.com/discord-jda/JDA/pull/2572 didn't remove the `else` from the `threadMetadata` if-block when it should've
=> Fix else if for threadMetadata being on avatarUrl after #2572

src/main/java/net/dv8tion/jda/api/entities/channel/ChannelType.java, src/main/java/net/dv8tion/jda/api/entities/channel/concrete/GroupChannel.java
This PR adds the expected interface type to `ChannelType`, as well as a method to retrieve channel types from an interface type, and `GroupChannel` for Group DMs
=> Add interface type to channel types

src/main/java/net/dv8tion/jda/api/entities/channel/ChannelField.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/ICategorizableChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPermissionContainer.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPositionableChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/concrete/ThreadChannel.java, src/main/java/net/dv8tion/jda/api/entities/channel/unions/DefaultGuildChannelUnion.java, src/main/java/net/dv8tion/jda/api/events/guild/override/PermissionOverrideUpdateEvent.java, src/main/java/net/dv8tion/jda/api/requests/restaction/PermissionOverrideAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/WebhookMessageEditAction.java, src/main/java/net/dv8tion/jda/internal/entities/ThreadMemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ThreadChannelImpl.java, src/main/java/net/dv8tion/jda/internal/handle/TypingStartHandler.java, src/main/java/net/dv8tion/jda/internal/handle/VoiceStateUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/PermissionOverrideActionImpl.java
There were a lot of very old todo comments that I have removed. I also applied changes where necessary when a TODO needed to be addressed.
=> Remove outdate todo comments and update outdated logic in thread channels

src/main/java/net/dv8tion/jda/api/interactions/components/text/TextInput.java
Adds support for resetting min/max length in TextInput.Builder
=> Add support for resetting min/max length in TextInput.Builder

src/main/java/net/dv8tion/jda/api/requests/SequentialRestRateLimiter.java
It seems that sometimes buckets are no longer reachable and still handling a request. This ensures that requests are always moved into a reachable bucket after encountering a rate-limit.
=> Fix orphaned rate-limit buckets

src/main/java/net/dv8tion/jda/api/utils/messages/MessageEditData.java
This was using the wrong indexing, which resulted in update failures.
=> Fix incorrect index used in attachment update requests

src/main/java/net/dv8tion/jda/api/EmbedBuilder.java, src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java
Discord changed their API in regards to embed fields. It will now return errors when you send JSON with more than 25 fields defined.
This PR adds two things:
1. It adds a new `MAX_FIELD_AMOUNT` constant set to 25
2. It adds a check in `EmbedBuilder#build()` for if the number is above the max allowed, at which point it throws an `IllegalStateException`
=> Add check for max number of fields in EmbedBuilder

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/StageInstance.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IPermissionContainer.java, src/main/java/net/dv8tion/jda/api/entities/channel/attribute/IThreadContainer.java, src/main/java/net/dv8tion/jda/api/entities/channel/concrete/Category.java, src/main/java/net/dv8tion/jda/api/interactions/components/LayoutComponent.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectInteraction.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessageEditData.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/ForumChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/MediaChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/NewsChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/TextChannelImpl.java, src/main/java/net/dv8tion/jda/internal/utils/cache/ChannelCacheViewImpl.java, src/main/java/net/dv8tion/jda/internal/utils/cache/ShardCacheViewImpl.java, src/main/java/net/dv8tion/jda/internal/utils/cache/UnifiedCacheViewImpl.java
Prevents users from mutating returned lists, as they may think it does something
* Return unmodifiable lists where documented
* Replace `Collections.unmodifiableList` with the `Helpers.toUnmodifiableCollection` collector
* Return unmodifiable lists in `StringSelectInteraction#getSelectedOptions` ([previously undocumented](https://github.com/discord-jda/JDA/commit/67f2e6287e3b349814ee5db7856fcd86c8211266#diff-0d53ea747f80e12f1598e5f987916b1ce28054cf7a3ca5eefaf12d8427b0babeL45-R55)) and `Guild#getBoosters`
=> Return immutable lists when documented

src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java
the `JDA` interface has the generic type set for the dependency on `IGuildChannelContainer`, the ShardManager interface however, does not have this causing the following compile error when using `ShardManager#getChannelById`
=> Add missing generic type to shardmanager

src/main/java/net/dv8tion/jda/api/entities/MessageEmbed.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Adds a field to the `MessageEmbed.VideoInfo` class containing the proxied video url.
=> Add missing proxy url field to the MessageEmbed.VideoInfo class

src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java
This used to delete the message instead of editing the flags
=> Fix suppressing embeds on messages with webhooks

src/main/java/net/dv8tion/jda/api/requests/restaction/MessageCreateAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java
Adds support for the new `enforce_nonce` field on the message create endpoint. This enables automatic deduping of messages sent to channels. JDA will now automatically set a unique random nonce on every message, unless a user defined nonce is specified instead.
Reference: https://github.com/discord/discord-api-docs/pull/6647
=> Add support for enforce_nonce

src/main/java/net/dv8tion/jda/api/entities/BulkBanResponse.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/api/requests/Route.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Adds support for the new bulk-ban endpoint.
Reference: https://github.com/discord/discord-api-spec/commit/aeb7e2c173bb701743f4d24f75dc3fc4affd4b17
=> Add support for bulk banning users

src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/AutoCompleteCallbackActionImpl.java, src/main/java/net/dv8tion/jda/internal/utils/Checks.java
This fixes a format exception when a long/double choice value is too large
=> Fix format specifiers when adding invalid choices

src/main/java/net/dv8tion/jda/internal/requests/restaction/operator/FlatMapRestAction.java
Closes Issue: [#2635](https://github.com/discord-jda/JDA/issues/2635)
This make sure the predicate of FlatMapRestAction is considered with complete or submit.
=> Fix FlatMapRestAction predicate with complete or submit

src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java
Closes Issue: 2650
I tried to add a member over guild.addMember() and then I got the error 50178 and I did not found it in the errorresponse.java and now I added it
=> Add USER_MUST_BE_VERIFIED ErrorResponse

src/main/java/net/dv8tion/jda/api/Permission.java
Removes a long-time deprecated permission and adds the currently missing permissions.
Reference: https://github.com/discord/discord-api-docs/issues/6802
=> Update permission enum

.github/CONTRIBUTING.md, README.md
This rewrites the current README of JDA. Since this README has been around for such a long time, it needed some rework for the current state of the library. I've also heavily reduced the size of the README.
=> Rewrite JDA readme

src/main/java/net/dv8tion/jda/api/interactions/commands/CommandInteractionPayload.java
When printing a command string, in an autocomplete interaction, an `IllegalStateException` could occur when an entity is in that command, as Discord does not send resolved entities there
=> Fix `CommandInteractionPayload#getCommandString` in autocomplete interactions

src/main/java/net/dv8tion/jda/api/managers/channel/attribute/IPostContainerManager.java, src/main/java/net/dv8tion/jda/api/managers/channel/middleman/StandardGuildMessageChannelManager.java
Add missing `setTopic` in post container managers
=> Add `IPostContainerManager#setTopic`

src/main/java/net/dv8tion/jda/internal/requests/WebSocketClient.java
Updates the trace of the websocket client when a RESUMED event is received
=> Also use _trace from resumed event

src/main/java/net/dv8tion/jda/api/entities/Guild.java
This fixes an error in the documentation where it was stated that `useCache(true)` must be used to always make a new request, which is not the case.
=> fix(docs): use useCache(false) if you want to make a request

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/VoiceChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/ChannelMixin.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/AudioChannelMixin.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/GuildChannelMixin.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/GuildMessageChannelMixin.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/middleman/MessageChannelMixin.java
Closes #2678
Makes checks for channel access consistent.
=> Make channel access checks consistent

src/main/java/net/dv8tion/jda/api/exceptions/ErrorResponseException.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/interactions/InteractionCallbackImpl.java
Improves the meaning of 'Unknown interaction' errors and adds several tips on how to solve them.
Depends on https://github.com/discord-jda/JDA-Website/pull/56
=> Improve Unknown Interaction error responses

src/main/java/net/dv8tion/jda/internal/utils/config/ThreadingConfig.java
Closes #2696
Fixes incorrect handling of elastic pool shutdown.
=> Fix automatic shutdown for elastic pool

src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java
This is required as the voice state is not sent with, for example, interactions.
=> Document `GuildVoiceState#getChannel()` requires the member cache

src/main/java/net/dv8tion/jda/api/entities/TeamMember.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/TeamMemberImpl.java
Adds [team member roles](https://discord.com/developers/docs/topics/teams#team-member-roles), for example, may be useful to get team members without read-only members.
=> Add `TeamMember.RoleType`

src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/SelectMenu.java, src/main/java/net/dv8tion/jda/api/interactions/components/selections/StringSelectMenu.java
Adds an abstract `createCopy` method in the `SelectMenu` interface. This allows to create a copy of a SelectMenu without knowing the actual type
=> Add abstract `createCopy` method in `SelectMenu`

src/main/java/net/dv8tion/jda/internal/interactions/component/TextInputImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalImpl.java
It fixes the deserialization of some interaction components. Actually, I identified two classes that are deserializing in a wrong way.
**ModalImpl**: isn't using custom_id if available. When converting to data, it saves the id as custom_id
**TextInputImpl**: serializes minimum length as min_length but actually uses min_**L**ength
=> Fix deserialization of interaction components

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/utils/Once.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Adds an helper method to listen for an event, once.
```java
final Duration timeout = Duration.ofSeconds(5);
event.reply("Reply in " + TimeFormat.RELATIVE.after(timeout) + " if you can!")
.setEphemeral(true)
.queue();
event.getJDA().listenOnce(MessageReceivedEvent.class)
.filter(messageEvent -> messageEvent.getChannel().getIdLong() == event.getChannel().getIdLong())
.filter(messageEvent -> messageEvent.getAuthor().getIdLong() == event.getUser().getIdLong())
.timeout(timeout, () -> {
event.getHook().editOriginal("Timeout!").queue();
})
.submit()
.onSuccess(messageEvent -> {
event.getHook().editOriginal("You sent: " + messageEvent.getMessage().getContentRaw()).queue();
});
```
=> Add `JDA#listenOnce`

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
The `stickers` field in the Guild object is marked optional in the [docs](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure). It never is in practice, but is omitted by https://github.com/Gelbpunkt/gateway-proxy if you disable the sticker cache, making it incompatible.
=> Handle guild stickers array as optional in EntityBuilder#createGuild

src/main/java/net/dv8tion/jda/internal/audio/AudioPacket.java
With the new update (v5.1.0) that uses the new voice encryption modes, when the bot receives audio from regular users (not bots) it throws opus decoder errors in the debug logs.
The issue is that the header extension (present in user's audio packets) is not being stripped from the encoded (but decrypted) audio packet.
This PR fixes that by offseting the decrypted audio ByteBuffer by `4 * extension length in the RTP header` .
=> Remove extension from received audio packets

src/main/java/net/dv8tion/jda/api/utils/Once.java
Users are not required to use the return value
=> Remove `@CheckReturnValue` from Once.Builder.subscribe

src/main/java/net/dv8tion/jda/internal/entities/automod/AutoModResponseImpl.java
While rewriting a bot from Discord.js to Discord JDA, it was discovered that `AutoModResponseImpl` always returns 0 and null for `customMessage`, `timeoutDuration` and `channel`, respectively, despite these values being set.
Upon investigation, it was found that these values are being accessed incorrectly. They are actually nested within a sub-object called `metadata`.
This pull request addresses the issue by correctly accessing the `custom_message`, `duration_seconds` and `channel_id` values from the `metadata` object in `AutoModResponseImpl`.
- Updated `AutoModResponseImpl` to access `custom_message`, `duration_seconds` and `channel_id` from the `metadata` object.
- Ensured that the correct values are now …
=> Fix parsing error for AutoModResponse

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/utils/FileUpload.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateBuilder.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateData.java, src/main/java/net/dv8tion/jda/api/utils/messages/MessageCreateRequest.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/utils/message/MessageCreateBuilderMixin.java, src/test/java/net/dv8tion/jda/test/assertions/restaction/RestActionAssertions.java, src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
This adds support for sending voice messages.
```java
channel.sendFiles(
FileUpload.fromData(audioFile)
.asVoiceMessage(MediaType.parse("audio/ogg"), waveform, 10.5)
).queue();
```
The `waveform` must be a low frequency sampling of the audio file, with at most 256 samples.
=> Support sending voice messages

src/main/java/net/dv8tion/jda/internal/managers/ScheduledEventManagerImpl.java
[documentation]: https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-valid-guild-scheduled-event-status-transitions
The check `status != ScheduledEvent.Status.SCHEDULED && getScheduledEvent().getStatus() != ScheduledEvent.Status.ACTIVE` is not correct.
According to Discord [documentation] you can set ACTIVE to COMPLETED, but if the event was ACTIVE, the `check` was always false and throwing error.
New checks:
- Current status should be different than COMPLETED or CANCELED
- If current status is SCHEDULED, the new one can be only ACTIVE or CANCELED
- If current status is ACTIVE, the new one can be only COMPLETED
I also updated the first check which verifies the new …
=> Fix ScheduledEventManagerImpl::setStatus

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageReference.java, src/main/java/net/dv8tion/jda/api/entities/messages/MessageSnapshot.java, src/main/java/net/dv8tion/jda/api/requests/ErrorResponse.java, src/main/java/net/dv8tion/jda/api/requests/restaction/MessageCreateAction.java, src/main/java/net/dv8tion/jda/api/utils/messages/AbstractMessageBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java, src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
This adds support for message forwarding and handling forwarded message snapshots.
=> Add support for message forwarding

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/events/guild/update/GuildUpdateSafetyAlertsChannelEvent.java, src/main/java/net/dv8tion/jda/api/hooks/ListenerAdapter.java, src/main/java/net/dv8tion/jda/api/managers/GuildManager.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/handle/GuildUpdateHandler.java, src/main/java/net/dv8tion/jda/internal/managers/GuildManagerImpl.java
Added getSafetyAlertsChannel allowing you to get the channel to which Discord sends alerts to.
=> Added Safety Alerts Channel

src/main/java/net/dv8tion/jda/api/entities/ScheduledEvent.java, src/main/java/net/dv8tion/jda/internal/entities/ScheduledEventImpl.java, src/test/java/net/dv8tion/jda/test/entities/scheduledevent/ScheduledEventTest.java
Added the `getJumpUrl` method to the `ScheduledEvent` interface, and implemented it in `ScheduledEventImpl` class (the only implementation of `ScheduledEvent`).
=> Add `ScheduledEvent::getJumpUrl`

src/main/java/net/dv8tion/jda/internal/requests/restaction/MessageCreateActionImpl.java, src/test/java/net/dv8tion/jda/test/restaction/MessageCreateActionTest.java
This fixes the handling of `setMessageReference((String) null)`. The previous release introduced a bug that caused this code to serialize invalid request bodies.
=> Fix handling of passing null to setMessageReference

src/main/java/net/dv8tion/jda/api/JDA.java
Fix typo in JDA#isAutoReconnect javadocs that I found when reading JDA's sopurce code... Previously it was `USed` so I fixed it to `Used`, yeah, that's it.
=> Fix typo in JDA#isAutoReconnect javadocs

src/main/java/net/dv8tion/jda/api/entities/SkuSnowflake.java, src/main/java/net/dv8tion/jda/api/events/interaction/command/GenericCommandInteractionEvent.java, src/main/java/net/dv8tion/jda/api/events/interaction/component/GenericComponentInteractionCreateEvent.java, src/main/java/net/dv8tion/jda/api/interactions/Interaction.java, src/main/java/net/dv8tion/jda/api/interactions/callbacks/IPremiumRequiredReplyCallback.java, src/main/java/net/dv8tion/jda/api/interactions/components/LayoutComponent.java, src/main/java/net/dv8tion/jda/api/interactions/components/buttons/Button.java, src/main/java/net/dv8tion/jda/api/interactions/components/buttons/ButtonStyle.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/InteractionCallbackAction.java, src/main/java/net/dv8tion/jda/api/requests/restaction/interactions/PremiumRequiredCallbackAction.java, src/main/java/net/dv8tion/jda/internal/entities/SkuSnowflakeImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/component/ButtonImpl.java, src/main/java/net/dv8tion/jda/internal/utils/ComponentsUtil.java, src/test/java/net/dv8tion/jda/test/interactions/ButtonTests.java, src/test/java/net/dv8tion/jda/test/util/ComponentsUtilTest.java
Implements changes of https://discord.com/developers/docs/change-log#premium-apps-new-premium-button-style-deep-linking-url-schemes.
Deprecated the premium reply callback, which are replaced with premium buttons.
=> Add premium buttons

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/emoji/ApplicationEmoji.java, src/main/java/net/dv8tion/jda/api/entities/emoji/CustomEmoji.java, src/main/java/net/dv8tion/jda/api/entities/emoji/Emoji.java, src/main/java/net/dv8tion/jda/api/entities/emoji/EmojiUnion.java, src/main/java/net/dv8tion/jda/api/managers/ApplicationEmojiManager.java, src/main/java/net/dv8tion/jda/api/requests/Route.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/ApplicationEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/CustomEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/RichCustomEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/entities/emoji/UnicodeEmojiImpl.java, src/main/java/net/dv8tion/jda/internal/managers/ApplicationEmojiManagerImpl.java, src/test/java/net/dv8tion/jda/test/restaction/CreateApplicationEmojiTest.java
Supersedes https://github.com/discord-jda/JDA/pull/2712 with a cleaned up commit list and implementation of freya022's change requests.
Implements this api-docs PR: https://github.com/discord/discord-api-docs/pull/7010.
=> Add support for Application Emoji

src/main/java/net/dv8tion/jda/api/events/emoji/EmojiAddedEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/EmojiRemovedEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/GenericEmojiEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/package-info.java, src/main/java/net/dv8tion/jda/api/events/emoji/update/EmojiUpdateNameEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/update/EmojiUpdateRolesEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/update/GenericEmojiUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/emoji/update/package-info.java, src/main/java/net/dv8tion/jda/api/events/sticker/GenericGuildStickerEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/GuildStickerAddedEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/GuildStickerRemovedEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/package-info.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/GenericGuildStickerUpdateEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateAvailableEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateDescriptionEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateNameEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/GuildStickerUpdateTagsEvent.java, src/main/java/net/dv8tion/jda/api/events/sticker/update/package-info.java, src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java, src/main/java/net/dv8tion/jda/api/utils/cache/CacheFlag.java
Updates the intent to match Discord's name, will be clearer for #2753
=> Replace `GatewayIntent#GUILD_EMOJIS_AND_STICKERS` with `GUILD_EXPRESSIONS`

src/main/java/net/dv8tion/jda/api/JDABuilder.java, src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManagerBuilder.java, src/test/java/net/dv8tion/jda/test/JDABuilderTest.java
If one of the two overlapping intents is missing, it was disabled due to `complementOf`.
=> Correctly handle disabled intent in setEnabledIntents

src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java
Handle user in `EntityBuilder#createApplicationEmoji` as optional, and use self-user if it was created by `JDA#createApplicationEmoji`
=> Handle user in EntityBuilder#createApplicationEmoji as optional

src/main/java/net/dv8tion/jda/api/interactions/components/selections/EntitySelectMenu.java
=> Fix EntitySelectMenu Doc

src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/PollVotersPaginationActionImpl.java, src/test/java/net/dv8tion/jda/test/entities/message/PollVotersPaginationTest.java
Corrects the default max and initial limits of the *Get Answer Voters* endpoint handled in `PollVotersPaginationActionImpl.java` from 1000 to 100 as specified in the [docs](https://discord.com/developers/docs/resources/poll#get-answer-voters). Simply updates the values in its constructor.
Without updating the limit before execution, the request always fails. Because `PollVotersPaginationActionImpl` is a `PaginationAction`, users can temporarily correct it by chaining `.limit(100)` to their request. Example:
```java
pollMessage.retrievePollVoters(answerID).limit(100).queue();
```
=> Fixing Get Poll Answers endpoint limit from 1000 to 100

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Moved the permission check to where an `AudioChannel` is present as to prevent false exceptions.
=> Check mute/deafen permissions using the channel

src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractGuildChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/middleman/AbstractStandardGuildChannelImpl.java, src/test/java/net/dv8tion/jda/test/entities/EntityManagerTest.java
Closes #2756
Changes the order of cache checks, using the guild as the source of truth. This means that whenever a channel is created, it will definitely be in the guild's cache. If a channel is created in an uncached guild, the `channel.getGuild()` automatically updates its reference to a cached guild anyway.
=> Fix channel cache lock handling

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/emoji/ApplicationEmoji.java
=> Rename `ApplicationEmoji#APPLICATION_EMOJI_CAP` -> `MAX_APPLICATION_EMOJIS`

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/requests/Route.java, src/main/java/net/dv8tion/jda/internal/entities/EntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
Discord recently added an API endpoint to get a user's voice state in a guild (https://discord.com/developers/docs/resources/voice).
Adds `Guild#retrieveMemberVoiceState`, `Guild#retrieveMemberVoiceStateById(long)` and `Guild#retrieveMemberVoiceStateById(String)` that send a request and create a new `GuildVoiceState` if not already cached.
Also makes changes to `EntityBuilder` to allow the creation of voice states from JSON and `Route` for the new endpoint.
=> Add `Guild#retrieveMemberVoiceState`

src/main/java/net/dv8tion/jda/api/entities/channel/concrete/PrivateChannel.java, src/main/java/net/dv8tion/jda/internal/entities/InteractionEntityBuilder.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/detached/DetachedPrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/mixin/concrete/PrivateChannelMixin.java
Closes Issue: #2817
Since Discord now sends recipients of Friend DMs, assumptions on how to detect friend DMs failed, this is now fixed.
Additionally:
- If the recipient is absent, a warn will be logged and a detached channel will be used
- Bot DMs from interactions will now target the interaction caller, this should be considered as a fix
- Detached private channels will now be able to return an `User` in some situations
- A new method `PrivateChannel#retrieveOpenPrivateChannel()` was added, this is intended for cases where the user wants the bot to *attempt to* send a DM to the friend on which the interaction was called
- This is necessary as interactions started in friend DMs don't open a channel between the bot and the …
=> Fix assumptions in friend DM interactions 

src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/PrivateChannelImpl.java, src/main/java/net/dv8tion/jda/internal/entities/channel/concrete/detached/DetachedPrivateChannelImpl.java
Closes Issue: #2819
Superclass methods are prioritized from interfaces, this PR brings back the getters in their classes and calls the interface method explicitly
=> Fix `PrivateChannel#getName` returning `null`

src/main/java/net/dv8tion/jda/api/entities/Guild.java
The docs at `Guild#unban(UserSnowflake)` do not include the possible `ErrorResponse.UNKNOWN_BAN` that can be returned by Discord, when the provided user is not banned from the Guild.
=> Include possible ErrorResponse at Guild#unban Javadoc.

src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java, src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java
Now returns the correct proxy type.
=> Fix `FileProxy#withClient` return types

src/main/java/net/dv8tion/jda/internal/requests/restaction/order/OrderActionImpl.java
Fixes `IndexOutOfBoundsException` when an user attempts to use `OrderAction#moveTo` or `OrderAction#swapTo` without first selecting an entity
=> Add missing exceptions when attempting to move entities before selecting

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/entities/MessageReaction.java, src/main/java/net/dv8tion/jda/api/entities/channel/middleman/MessageChannel.java, src/main/java/net/dv8tion/jda/internal/entities/ReceivedMessage.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/pagination/ReactionPaginationActionImpl.java
Currently, there is no way to get users that reacted with super reactions even though [Discord API](https://discord.com/developers/docs/resources/message#get-reactions) supports it.
This PR adds a way to get super reaction users via `MessageReaction#retrieveUsers(MessageReaction.ReactionType)`
=> Add a way to retrieve users that used super reaction

src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandEditActionImpl.java
Closes Issue: #2805
Fixes the checks in CommandEditAction to no longer assume type is slash.
=> Fix checks in CommandEditAction

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/utils/AttachmentProxy.java, src/main/java/net/dv8tion/jda/api/utils/FileProxy.java, src/main/java/net/dv8tion/jda/api/utils/ImageProxy.java, src/main/java/net/dv8tion/jda/api/utils/NamedAttachmentProxy.java
Makes re-uploading attachments easier.
=> Add `downloadAsFileUpload` to file proxies

src/main/java/net/dv8tion/jda/api/entities/Message.java, src/main/java/net/dv8tion/jda/api/interactions/InteractionHook.java
Removes the parts about ephemeral messages from the InteractionHook and Message docs that are wrong
=> remove wrong ephemeral part from javadocs

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/CommandDataImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/command/CommandImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/CommandEditActionImpl.java, src/test/java/net/dv8tion/jda/test/IntegrationTest.java, src/test/java/net/dv8tion/jda/test/restaction/CommandEditActionTest.java, src/test/resources/net/dv8tion/jda/test/restaction/CommandEditActionTest_testEditMessageCommandById.json, src/test/resources/net/dv8tion/jda/test/restaction/CommandEditActionTest_testEditSlashCommandById.json, src/test/resources/net/dv8tion/jda/test/restaction/CommandEditActionTest_testEditUserCommandById.json
Closes Issue: #2838
We now always require knowing the type of the command we edit. Otherwise our checks and serialization can't work properly. By default, the now deprecated `editCommandById` will assume `Command.Type.SLASH` to avoid breaking existing code.
=> Fix editCommandById

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/Member.java, src/main/java/net/dv8tion/jda/internal/entities/MemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/SelectMenuMentions.java, src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedMemberImpl.java, src/main/java/net/dv8tion/jda/internal/entities/mentions/AbstractMentions.java, src/main/java/net/dv8tion/jda/internal/utils/PermissionUtil.java, src/main/java/net/dv8tion/jda/internal/utils/cache/MemberCacheViewImpl.java, src/test/java/net/dv8tion/jda/test/util/PermissionUtilTest.java
Closes Issue: #2840
Add `Member#getUnsortedRoles` to avoid the overhead of sorting the role list, when the order is not relevant. This is now used by `getMembersWithRoles` and permission checks.
=> Add Member#getUnsortedRoles

src/main/java/net/dv8tion/jda/api/requests/restaction/AbstractThreadCreateAction.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ForumPostActionImpl.java, src/main/java/net/dv8tion/jda/internal/requests/restaction/ThreadChannelActionImpl.java
This adds the ability to set the slowmode when creating a thread channel or forum post. Just like [`ChannelAction.setSlowmode`](https://github.com/discord-jda/JDA/blob/b1f2e2873db1a95ae6da34c9d6479accadcd3fa1/src/main/java/net/dv8tion/jda/internal/requests/restaction/ChannelActionImpl.java#L215), the slowmode can be set when creating forum or thread channels. This utilizes the `rate_limit_per_user` value in the [Start Thread](https://discord.com/developers/docs/resources/channel#start-thread-without-message) endpoints.
=> Add `AbstractThreadCreateAction#setSlowmode`

src/main/java/net/dv8tion/jda/api/entities/WebhookClient.java, src/main/java/net/dv8tion/jda/internal/requests/IncomingWebhookClientImpl.java
Make `IncomingWebhookClient` use `with_components=true` query param. This allows users to send non-interactive message components like link buttons. Also needed for Components V2
=> Add  `with_components=true` query param to WebhookClient requests

src/main/java/net/dv8tion/jda/api/entities/Guild.java, src/main/java/net/dv8tion/jda/api/entities/GuildVoiceState.java, src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java, src/main/java/net/dv8tion/jda/internal/entities/detached/DetachedGuildImpl.java
This PR allows users to move/kick voice members without requiring them to be cached.
I also updated some documentation that mentioned `MemberCachePolicy#VOICE`, as it is not necessary anymore
=> Require a `UserSnowflake` in `moveVoiceMember` and `kickVoiceMember`

src/main/java/net/dv8tion/jda/api/JDA.java, src/main/java/net/dv8tion/jda/api/entities/User.java, src/main/java/net/dv8tion/jda/api/sharding/ShardManager.java, src/main/java/net/dv8tion/jda/internal/JDAImpl.java
Changes the parameter type of `JDA#getMutualGuild` to `Collection<UserSnowflake>` instead of `Collection<User>` (Same for the vararg overloads and the corresponding methods in ShardManager).
=> Make JDA#getMutualGuilds accept UserSnowflake instead of User objects

src/main/java/net/dv8tion/jda/api/requests/Route.java
The old route used by Discord to delete guilds was the `[POST] /guilds/{guild_id}/delete`, but according to their [Documentation](https://discord.com/developers/docs/resources/guild#delete-guild), the `[DELETE] /guilds/{guild_id}` is the new correct route to be used. While it behaves the same way, this endpoint follows better REST conventions.
=> Use `DELETE_GUILD` route according to the Discord Docs

src/main/java/net/dv8tion/jda/api/components/textinput/TextInput.java
The latest changes missed the `TextInput.Builder` custom ID setter, this PR fixes that.
=> Deprecate and replace `TextInput.Builder#setId` with `setCustomId`

src/main/java/net/dv8tion/jda/api/components/Component.java, src/main/java/net/dv8tion/jda/api/components/ModalTopLevelComponent.java, src/main/java/net/dv8tion/jda/api/components/ModalTopLevelComponentUnion.java, src/main/java/net/dv8tion/jda/api/components/label/LabelChildComponent.java, src/main/java/net/dv8tion/jda/api/components/label/LabelChildComponentUnion.java, src/main/java/net/dv8tion/jda/api/components/selections/EntitySelectMenu.java, src/main/java/net/dv8tion/jda/api/components/selections/SelectMenu.java, src/main/java/net/dv8tion/jda/api/components/selections/StringSelectMenu.java, src/main/java/net/dv8tion/jda/api/components/textdisplay/TextDisplay.java, src/main/java/net/dv8tion/jda/api/interactions/modals/ModalMapping.java, src/main/java/net/dv8tion/jda/internal/components/selections/EntitySelectMenuImpl.java, src/main/java/net/dv8tion/jda/internal/components/selections/SelectMenuImpl.java, src/main/java/net/dv8tion/jda/internal/components/selections/StringSelectMenuImpl.java, src/main/java/net/dv8tion/jda/internal/components/textdisplay/TextDisplayImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/InteractionImpl.java, src/main/java/net/dv8tion/jda/internal/interactions/modal/ModalInteractionImpl.java
This allows `EntitySelectMenu` and `TextDisplay` in modals and moves the `required` property to `SelectMenu`.
See https://github.com/discord/discord-api-docs/pull/7804
=> Add entity selects and text displays in modals
